### PR TITLE
Removed error from runInitSequence method

### PR DESCRIPTION
**Pull request by akarshan96**
Fixes issue #175 

Changes: 
- Called `initializeVariables()` and `runInitSequence` method in the constructor.
- Instead of calling `y.clear`, reinitialised `y` in [this](https://github.com/fossasia/pslab-android/blob/master/app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java#L2584) line to remove the error.
@viveksb007 @asitava1998 can you please check this with your device.
Screenshots for the change: 
none

### CODE REVIEW

**Comment by viveksb007** [comment]
@akarshan96 Could you provide link of apk for testing too?

**Comment by CloudyPadmal** [comment]
@viveksb007 is there a method we can use to make Travis run in our fork and generate apk like in the parent repo?

**Comment by viveksb007** [comment]
If by parent repo means main fossasia repo, then NO you can't run travis on your repo and create an apk in main fossasia repo. But there is a way to generate apk after a PR has been made to main fossasia repo.

**Comment by akarshan96** [comment]
@viveksb007 [this](https://drive.google.com/file/d/0B423XEmWL9vKTHc4cFJUZEhnczA/view?usp=sharing) is the link for the apk.

**Comment by viveksb007** [comment]
@akarshan96 the app crashes when opened without connecting pslab device. Put initialisation code inside ```if``` condition of device connected.

**Comment by akarshan96** [comment]
@viveksb007 made the change, the [link](https://drive.google.com/file/d/0B423XEmWL9vKTHc4cFJUZEhnczA/view?usp=sharing) to the latest apk.

**Comment by asitava1998** [comment]
@akarshan96  The new apk seems alright to me. I didn't face any issues.

**Comment by viveksb007** [comment]
@akarshan96 Its working fine on my phone too. Just some bytes are dropped sometimes. We would try to shift communication part to another thread, so there is no lag in UI thread.

**Pull request merged**
