### PR TITLE
Fixed the flawed logic in DACChannel (#15)

### PR DESCRIPTION
**Pull request by akarshan96**
replaced slope + offset with slope * v +offset under ApplyCalibration method. Resolved the issue mentioned in #15.

### CODE REVIEW

**Comment by mariobehling** [comment]
Please add link to the issue in the description of pull requests.

Please read my recent post about best practices: http://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/

Thanks.

**Comment by akarshan96** [comment]
@mariobehling thanks for sharing a very informative blog, I have edited the description and mentioned the link of the issue I am referring.

**Comment by mariobehling** [comment]
@viveksb007 @akarshan96 Great. Please start to peer-review each others contributions. Cheers.

**Comment by viveksb007** [comment]
@akarshan96 close this PR as this commit is included in your latest PR.

**Pull request closed without merging**
