### PR TITLE
fix: solved issue of crashing in capacitance measurement

### LINKED ISSUE #1376: App crash in multimeter
**Actual Behaviour**

According to crash reports in Google Play, there is a crash causing due to following reasons;
> Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago. Wait queue length: 10. Wait queue head age: 7224.2ms.)

**Expected Behaviour**

This kind of says that the click event was too quick for it to process. May be adding a lock once clicked on READ button until a fetch is complete would fix it. @abhinavraj23 any suggestions?

**Steps to reproduce it**

> Not available. Captured from crash logs

**LogCat for the issue**

```
  at android.hardware.usb.UsbDeviceConnection.native_bulk_request (Native method)
  at android.hardware.usb.UsbDeviceConnection.bulkTransfer (UsbDeviceConnection.java:250)
  at android.hardware.usb.UsbDeviceConnection.bulkTransfer (UsbDeviceConnection.java:232)
  at io.pslab.communication.CommunicationHandler.read (CommunicationHandler.java:132)
  at io.pslab.communication.PacketHandler.getVoltageSummation (PacketHandler.java:126)
  at io.pslab.communication.ScienceLab.getCapacitance (ScienceLab.java:2250)
  at io.pslab.communication.ScienceLab.getCapacitance (ScienceLab.java:2211)
  at io.pslab.activity.MultimeterActivity$4.onClick (MultimeterActivity.java:178)
  at android.view.View.performClick (View.java:6305)
  at android.view.View$PerformClick.run (View.java:24840)
```

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

@abhinavraj23 can you take this up?

### PR DESCRIPTION
**Pull request by abhinavraj23**
Fixes #1376 

**Changes**: 
There was an infinity loop in capacitance measurement, changed it to a finite loop, also handled null capacitance value in MultimeterActivity

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: [Compress the `app-debug.apk` file into a `<feature>.rar` or `<feature>.zip` file and upload it here]
[capacitance.apk.zip](https://github.com/fossasia/pslab-android/files/2300242/capacitance.apk.zip)

### CODE REVIEW

**Comment by cweitat** [comment]
Tested and it is still not working as intended.
Spammed read button a lot of times and thereafter "Cannot Measure" appears

**Comment by abhinavraj23** [comment]
@cweitat I have made changes in the code and have updated the apk, please review. There should not be any problem now, atleast the issue of app crashing as mentioned in #1376 is solved completely :+1:

**Comment by cweitat** [comment]
@abhinavraj23 Theoretically, if the multimeter is set to constant reading then this problem would have been eliminated. Probably at a refresh rate of 1 second or faster. And a hold function to replace read button. 

Anyway will try the apk soon and feedback

**Comment by abhinavraj23** [comment]
@cweitat Sure I will make those change, but for now we need to solve the issue of crashing, that is why I have made this PR. I will implement the auto-read feature in my subsequent PRs :+1:

**Comment by cweitat** [comment]
@abhinavraj23 yup. got your point. Thanks :)

**Comment by abhinavraj23** [comment]
@cweitat @CloudyPadmal @harsh-2711 @Avjeet Please review it :+1:

**Comment by cweitat** [comment]
Not crashing anymore

**Pull request merged**
