### PR TITLE
[WIP]Google maps option added

### LINKED ISSUE #1739: Option to use OSM or Google Map
**Actual Behaviour**
Currently we are only using OSM to plot locations. However Google maps is not open source so FDroid does not allow to release 

**Expected Behaviour**
Add option for OSM or Google Map on Play Store app and just OSM in FDroid.

**Steps to reproduce it**
N/A

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by ho-dor**
Fixes #1739

**Changes**: Created two flavours fdroid and playstore and changes made in playstore flavour

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [ ] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [ ] I have requested reviews from other members

### CODE REVIEW

**Comment by ho-dor** [comment]
This manifest merger error is really frustrating. No idea what is going wrong.

**Comment by neel1998** [comment]
Do we really need to create a whole new sensorListAdapter class?

**Comment by ho-dor** [comment]
Yes. That is where the main decision is taken between OSM and Google Map and if I don't create a new SensorListAdapter and add GoogleMap condition in main itself then there will be error in fdroid build.
If you have any better ideas, please share.

**Comment by neel1998** [comment]
Can't we have a separate class with methods to plot map data...And call that class from SensorListAdapter... So we only need to create 2 version of that map class , since rest of logic of SensorListAdaptet class is same...That would reduce the redundancy a lot.Does it make sense?

**Comment by neel1998** [comment]
@CloudyPadmal please share your views

**Comment by ho-dor** [comment]
@neel1998 something like now?

**Comment by neel1998** [comment]
@ho-dor yes. Doesn't make more sense now?. Will have to look for Travis still

**Comment by ho-dor** [comment]
It's that same issue , manifest merge.

**Pull request closed without merging**
