### PR TITLE
feat: add Httphandler class

### LINKED ISSUE #1926: Add HTTPHandler to communicate with ESP
**Actual Behaviour**
Currently there is no httphandler

**Expected Behaviour**
Add a httphandler like communicationHandler to control all the http communications with esp

**Steps to reproduce it**
N/A

**LogCat for the issue**
N/A

**Screenshots of the issue**
N/A

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by neel1998**
Fixes #1926 

**Changes**: added http handler class 

**Screenshot/s for the changes**: 
N/A

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [ ] I have requested reviews from other members

**APK for testing**: 
N/A

### CODE REVIEW

**Comment by neel1998** [comment]
**Current Architecture:**
currentArchitecture

**New Architecture:**
newArchitecture

@CloudyPadmal as shown in the above diagram we can add a new WIFI pathway to existing architecture. I have made two new functions ```commonRead()``` and ```commoWrite()``` in ```PacketHandler``` class... This will be the only point where the two architectures will diverge. I think this architecture is quite neat, and since we are not making any changes in the ScienceLab class we won't require to change a hell lot of code for wifi communication, which would also reduce the redundancy. This is still WIP. But kindly share your views. Thanks

**Comment by CloudyPadmal** [comment]
Yes this is the architecture proposed. Before going any further, better check if it works as intended with everything integrated (both ESP and USB).

**Comment by neel1998** [comment]
@CloudyPadmal yes. I have already tested the new architecture for USB path and it is working as expected. So that's a good sign.

**Comment by CloudyPadmal** [comment]
Let's use labels instead of change of titles

**Comment by neel1998** [comment]
@CloudyPadmal  I have tested the wifi path on a dummy server. The following path in the architecture to communicate over wifi was able to make get/post request to a server,

ESPFragment -> Initial Connection -> HttpAsyncTask -> HttpHandler -> HttpCallback

I think we can merge this basic architecture and then develop further on top of it.

**Pull request merged**
