### PR TITLE
Creates Inductive Reactance Experiment

### PR DESCRIPTION
**Pull request by asitava1998**
Fixes issue #543 

Changes:
* Creates the inductive reactance experiment

Screenshots for the change: 
[app.zip](https://github.com/fossasia/pslab-android/files/1241067/app.zip)

### CODE REVIEW

**Comment by CloudyPadmal** [comment]
Hi @asitava1998 ! Would we be able to reuse the same dialog box for this experiment and RC Phase Shift experiment? They are similar, aren't they? :)

**Comment by asitava1998** [comment]
@CloudyPadmal Yes. I will reuse it. I created the issue #570 for the same. Once, these PRs are merged, all the common files will be reused.

**Comment by asitava1998** [comment]
@CloudyPadmal @viveksb007 @akarshan96 Can you guys review it quickly? After this PR is merged, I can start handling the issues of common files and strings.

**Comment by asitava1998** [comment]
@viveksb007 I have resolved the conflicts. Thanks

**Pull request merged**
