### PR TITLE
Fixes #486 : Lemon Cell Experiment

### LINKED ISSUE #486: Implement Lemon Cell Experiment
**Actual Behaviour**

Lemon Cell experiment is not implemented in the saved experiments

**Expected Behaviour**

Lemon cell experiment needs to be implemented in the saved experiments

**Steps to reproduce it**

1. Open app
2. Go to `Saved Experiments`
3. Check the experiment under `School Level`

**LogCat for the issue**

> Not available

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by CloudyPadmal**
Fixes issue #486 

Changes: 
- Implemented experiment setup to perform lemon cell experiment

Screenshots for the change: 
fix

APK for testing:
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1218307/app-debug.apk.zip)

### CODE REVIEW

**Comment by CloudyPadmal** [comment]
Done @viveksb007 ! :)

**Comment by asitava1998** [comment]
The Travis CI build has failed.

**Comment by viveksb007** [comment]
I outlined the problem in #476 . Same error in both PRs.

**Comment by CloudyPadmal** [comment]
Hi @viveksb007 and @asitava1998 ! I've made the changes! :)

**Comment by CloudyPadmal** [comment]
Thanks guys for the review! :+1:

**Pull request merged**
