### PR TITLE
Add Indonesian Language

### LINKED ISSUE #2078: Add Language - Indonesian
**Actual Behaviour**
The app currently does not support the Indonesian language.

**Expected Behaviour**
We should add this as an option for many users who know this language.

**Would you like to work on the issue?**

- [x] Yes

### PR DESCRIPTION
**Pull request by pranavkarthik10**
Fixes #2078

**Changes**:
I added a new language in the form of the Indonesian language by creating and updating a new strings.xml for the new language.

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [ ] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

### CODE REVIEW

**Comment by Sid911** [comment]
@pranavkarthik10 do you know Indonesian? how can you verify the mean the correct thing 😕 ...  I am pretty sure there are like a million problems with google translate. That is the reason there aren't that many languages in all the websites because of verification of meaning. You may ask some person in community belonging to Indonesia to verify 😇

**Comment by pranavkarthik10** [comment]
@Sid911 You are definitely right, some of my friends know Indonesian so I asked them for help along with a little from google translate. All of the paragraphs and larger sentences are from a native speaker. Thanks.

**Comment by CloudyPadmal** [comment]
I wonder if we should accept these translations related PRs from non-native speakers :thinking:

**Comment by pranavkarthik10** [comment]
@CloudyPadmal Definitely, here are some screenshots, I have also attached the generated apk with this comment. Don't worry about the native speakers issue, I can assure that the translations in my PR are mostly from the native speakers that I know.  
Screenshot_20200117-170227_PSLab
Screenshot_20200117-170314_PSLab
Screenshot_20200117-170251_PSLab

[pslab generated apk.zip](https://github.com/fossasia/pslab-android/files/4079813/pslab.generated.apk.zip)

**Comment by CloudyPadmal** [comment]
Hello @pranavkarthik10 , could we get any native speaker to verify the content in this PR itself?

**Comment by pranavkarthik10** [comment]
@CloudyPadmal commits have been squashed. As I said before I have tried my best to verify the content with some native speakers I know. Would love if you could merge as soon as possible due to time constraints for GCI.

**Comment by pranavkarthik10** [comment]
@mariobehling @CloudyPadmal please review :)

**Comment by cweitat** [comment]
No native speaker to vet

**Pull request closed without merging**
