### PR TITLE
New Experiment added: Amplitude Modulation

### PR DESCRIPTION
**Pull request by ThisIsNSH**
Fixes issue : #763

Changes: New experiment markdown is added and implemented with its schematic.

Screenshots for the change: 
ampmod

APK for testing: [app-debug.zip](https://github.com/fossasia/pslab-android/files/1822564/app-debug.zip)

### CODE REVIEW

**Comment by ThisIsNSH** [comment]
@CloudyPadmal @akarshan96 @viveksb007 please review.

**Comment by akarshan96** [comment]
@ThisIsNSH, create an issue and mention it in this PR too.

**Comment by ThisIsNSH** [comment]
This PR is in reference with the issue #763

**Comment by ThisIsNSH** [comment]
whatsapp image 2018-03-21 at 18 01 24
@akarshan96  please review and suggest changes if required.

**Comment by ThisIsNSH** [comment]
Definitely @CloudyPadmal. I will maintain the similar look.

**Pull request closed without merging**
