### PR TITLE
fix: changed scroll view with custom scroll view for power source

### LINKED ISSUE #1313: bottomsheet dont slide up in power source
**Actual Behaviour**

bottom sheet not sliding in power source activity

**Expected Behaviour**

State here what the feature should enable the user to do.

**Steps to reproduce it**

Change scroll view of power source activity

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by Avjeet**
Fixes #1313 

**Changes**: 
Replaced normal scroll view with custom scroll view which I have created for this issue previously

**Screenshot/s for the changes**: 

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [ ] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [ ] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**:
[power_btm.zip](https://github.com/fossasia/pslab-android/files/2242667/power_btm.zip)

### CODE REVIEW

**Comment by CloudyPadmal** [comment]
@Avjeet in Sony devices, swiping up gets Google Assistant open. Also the scrolling behavior is not working in my device anymore. 
powersource

**Comment by CloudyPadmal** [comment]
@abhinavraj23 did you test the apk?

**Comment by abhinavraj23** [comment]
Yes @CloudyPadmal In my device it was working fine

**Comment by CloudyPadmal** [comment]
@abhinavraj23 I see. Mine I couldn't scroll up or down.

**Comment by Avjeet** [comment]
@CloudyPadmal I think it only doesnt support sny devices but all other are working so should merge this.

**Comment by CloudyPadmal** [comment]
If this is merged I can't use power source instrument. @Avjeet What you are saying doesn't make any sense. Why should we change a functional feature to a limited feature?

**Comment by Avjeet** [comment]
@CloudyPadmal But I haven't removed the info icon from menu bar so the user can still open the guide and I have done this to make the feature consistent throughout the app.

**Comment by Avjeet** [comment]
@CloudyPadmal oh sorry I didn't see that before, ok don't merge this PR for now and I will find a sony device try to debug this until let this PR remain open.

**Comment by CloudyPadmal** [comment]
@Avjeet shall we close this PR for now and reopen it when you find a Sony device and make a fix?

**Comment by Avjeet** [comment]
Yeah sure

**Pull request closed without merging**
