### PR TITLE
fft output of ch1 working fine

### LINKED ISSUE #1415: Fourier Transform in Oscilloscope
**Actual Behaviour**

Fourier transform analysis in PSLab oscilloscope is not working

**Expected Behaviour**

Frequency analysis of input signals need to be displayed correctly in the Fourier Transform section in oscilloscop

**Steps to reproduce it**

Check out Fourier transform analysis in oscilloscope with a sine wave or any kind of signal fed into oscilloscope channels

**LogCat for the issue**

> Not applicable

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by neel1998**
Fixes #1415 

**Changes**: Fourier Transform output generated for channel 1

**Screenshot/s for the changes**: 

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 
[oscilloscope_fft_new.zip](https://github.com/fossasia/pslab-android/files/3282499/oscilloscope_fft_new.zip)

@CloudyPadmal  kindly have a look at this. There is small issue, even if we unselect fourier transform checkbox the original wave isn't plotted. I will handle this issue in further commits.

### CODE REVIEW

**Comment by CloudyPadmal** [comment]
Nice work @neel1998 . Can you try to address the issues pointed out by codacy?

**Comment by neel1998** [comment]
@CloudyPadmal  i have solved the lagging and memory leak issue and now ch1 - fft toggling is working smooth. Please check the updated APK.

**Comment by mariobehling** [comment]
If you want PRs to be reviewed you should not mark a PR [WIP] usually.

**Comment by neel1998** [comment]
@mariobehling  sorry . It was WIP earlier. After my last commit it is good to be reviewed. I will change the title

**Pull request merged**
