### PR TITLE
feat: Layout for new instrument Compass

### PR DESCRIPTION
**Pull request by Vikum94**
First steps for issue #1136 

**Changes**: New layout for the compass intrument

**Screenshot/s for the changes**: 
screenshot_2018-07-04-15-34-51-290_org fossasia pslab

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 
[compass_layout.zip](https://github.com/fossasia/pslab-android/files/2139725/compass_layout.zip)

[updated_compass_layout.zip](https://github.com/fossasia/pslab-android/files/2162768/updated_compass_layout.zip)

### CODE REVIEW

**Comment by Vikum94** [comment]
@CloudyPadmal @harsh-2711 @Avjeet @abhinavraj23 Please review the layout for the new Compass instrument. Thanks!

**Comment by harsh-2711** [comment]
@Vikum94 This compass doesn't look good. Maybe you can standardize the compass to something like this 
compass

**Comment by Vikum94** [comment]
@harsh-2711 @CloudyPadmal Will do the necessary changes soon.

**Comment by Avjeet** [comment]
Resolve the conflicts with this PR

**Comment by Vikum94** [comment]
[updated_compass_layout.zip](https://github.com/fossasia/pslab-android/files/2162768/updated_compass_layout.zip)
@Avjeet @harsh-2711 @abhinavraj23 @CloudyPadmal Please review the new layout. Thanks!

**Comment by Vikum94** [comment]
@CloudyPadmal Actually, the tick boxes are to calculate and find the magnetic north. All three values will be displayed regardless of the tick boxes.

**Comment by CloudyPadmal** [comment]
Ahh got it! :+1:

**Comment by Avjeet** [comment]
@Vikum94 i thin k you should use svg for pin also because it is a large image and may blur out on large screens. @CloudyPadmal What do you say?

**Comment by CloudyPadmal** [comment]
@Avjeet yes that's a good suggestion!

**Comment by CloudyPadmal** [comment]
This PR is inactive, @harsh-2711 @Avjeet @abhinavraj23 would you like to continue working on this one?

**Comment by cweitat** [comment]
@CloudyPadmal @harsh-2711 wants to take over this. have already assigned him to #1136 . We can close this

**Pull request closed without merging**
