### PR TITLE
Fix main screen layout issue on tablets, #2117

### PR DESCRIPTION
**Pull request by CodeWithSouma**
@mariobehling @CloudyPadmal 
## Fixes issue #2117 
 Change nav header __height__

main screen layout issue

### Apk:-
[apk.zip](https://github.com/fossasia/pslab-android/files/5331649/apk.zip)

### CODE REVIEW

**Review by CloudyPadmal — CHANGES_REQUESTED** [review]
Please provide screenshots and APK file to test. Also don't modify the PR template and add your own. Please follow what's on the template.

**Comment by CodeWithSouma** [comment]
> Please provide screenshots and APK file to test. Also don't modify the PR template and add your own. Please follow what's on the template.

main screen layout issue

### Apk:-
[apk.zip](https://github.com/fossasia/pslab-android/files/5331649/apk.zip)

**Comment by CloudyPadmal** [comment]
> > Please provide screenshots and APK file to test. Also don't modify the PR template and add your own. Please follow what's on the template.
> 
> main screen layout issue
> 
> ### Apk:-
> [apk.zip](https://github.com/fossasia/pslab-android/files/5331649/apk.zip)

Please add these to the PR main message.

**Review by CloudyPadmal — CHANGES_REQUESTED** [review]
The right way to do this is to use a dimens.xml file for tablet views. We don't do that on the main file. Please refer to Android development guides and see how it's done.

**Comment by CloudyPadmal** [comment]
Fixed by #2134 addressing all the layouts

**Pull request closed without merging**
