### PR TITLE
Fixes #523 : AC Generator Experiment

### LINKED ISSUE #523: Implement AC Generator Experiment
**Actual Behaviour**

AC Generator experiment is not implemented in saved experiments.

**Expected Behaviour**

The experiment needs to be implemented in the saved experiments under school level experiments

**Steps to reproduce it**

1. Open app
2. Go to `Saved Experiments`
3. Select `School Level` and `AC Generator`

**LogCat for the issue**

> Not available

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by CloudyPadmal**
Fixes issue #523 

Changes: 
- Implemented AC generator experiment

Screenshots for the change: 
acgen

APK for testing:
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1228566/app-debug.apk.zip)

### CODE REVIEW

**Comment by jithinbp** [comment]
We probably need to include a voltage range selection combobox. Induced voltages can have quite low amplitudes depending on what magnets and solenoids are available with students, so we need a little more flexibility here.
Or we can use CH3 , and ask users to set their own gain manually using resistors. CH1 is preferred though.

**Comment by CloudyPadmal** [comment]
Hi @jithinbp ! That's a very good suggestion! I'll add a combo box and depending on the selection I will set the y axis to limit within that range. That would be good right? :)

**Comment by jithinbp** [comment]
That would be perfect. thanks!

**Comment by CloudyPadmal** [comment]
New APK:
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1231567/app-debug.apk.zip)

Screenshot:
newac

**Comment by CloudyPadmal** [comment]
Thanks alot @jithinbp :blush: :+1:

**Comment by CloudyPadmal** [comment]
Thanks @asitava1998 !

**Pull request merged**
