### PR TITLE
Fixes #418 Defined all versions into a single ext{} collective field

### LINKED ISSUE #418: Writing all gradle dependencies, fields' values in a single gradle collective field
**Actual Behaviour**

Currently, there are over 10 dependencies that the app enlists in the build.gradle file. The readability and maintenance of the versions of these dependencies within the string format, mainly when version change is required, is difficult.

**Expected Behaviour**

Mentioning all the dependencies version in a separate file (project.gradle) in the form of a list of variables, will lay out a level of abstraction as to what the dependencies are (build.gradle), and what are their corresponding versions (project.gradle). This feature will be implemented by writing all dependencies' versions in project.gradle within ext{...} field, and then incorporating them with the respective dependencies using string interpolation method.

**Would you like to work on the issue?**

I will work to correct this issue.

screen shot 2017-08-03 at 9 53 31 pm
screen shot 2017-08-03 at 9 53 14 pm
screen shot 2017-08-03 at 9 52 39 pm

### PR DESCRIPTION
**Pull request by robillo**
**Fixes issue** #418 Writing all gradle dependencies, fields' values in a single gradle collective field

**Description:**
Mentioning all the dependencies version in a separate file (project.gradle) in the form of a list of variables, will lay out a level of abstraction as to what the dependencies are (build.gradle), and what are their corresponding versions (project.gradle). This feature will be implemented by writing all dependencies' versions in project.gradle within ext{...} field, and then incorporating them with the respective dependencies using string interpolation method.
screen shot 2017-08-03 at 9 53 14 pm
screen shot 2017-08-03 at 9 53 31 pm
screen shot 2017-08-03 at 9 52 39 pm

### CODE REVIEW

**Comment by viveksb007** [comment]
Hi @robillo 
Thanks for sending the PR and showing interest in the project.
All PRs should be associated with corresponding Issue. Please go through the guidelines 
once https://docs.google.com/document/d/1E4kNgrOSw64R2IAG45JSIgQL9Yxia-mG2dqlRcrUo-U/edit

**Comment by robillo** [comment]
Hi @viveksb007 thank you for your guidance.
I went through the document as you said. 
I had opened an issue regarding the same PR, and updated the description of the same to link to the issue.

**Comment by CloudyPadmal** [comment]
Good work @robillo ! I cloned from your branch and tested it! It works well! Have you missed changing the `testCompile 'junit:junit:4.12'` part? :)

**Comment by robillo** [comment]
Thank you @CloudyPadmal for pointing out the missed out change, I have corrected that as well. :)

**Pull request merged**
