### PR TITLE
fix: issue of rounding off the decimal numbers

### LINKED ISSUE #917: Numbers are not rounded off properly in ControlActivity
**Actual Behaviour**

Some of the numbers in the Edit Text widget are not being rounded off properly as so huge length numbers are shown

**Expected Behaviour**

All the numbers should be rounded off properly

**Steps to reproduce it**

Go to Advanced section of Control Instrument and then set the Duty cycle in Configure PWM section

**LogCat for the issue**

Not applicable

**Screenshots of the issue**

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by harsh-2711**
Fixes #917 

Changes: Fixed the issue of rounding off numbers and setting stepsize in the Advanced section of ControlActivity

Screenshots for the change: 

APK for testing: 
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2039553/app-debug.zip)

### CODE REVIEW

**Comment by Avjeet** [comment]
I don't think we need these changes because I am making complete wave generator module from control advanced.

**Comment by CloudyPadmal** [comment]
@Avjeet will you be able to reuse this code? If not this can be closed.

**Comment by Avjeet** [comment]
Yeah i can reuse this.

**Comment by CloudyPadmal** [comment]
Great! :+1:

**Pull request merged**
