### PR TITLE
Fix #2063 Misaligned buttons fix.

### LINKED ISSUE #2063: Misaligned buttons
**Describe the bug**

In the "Generate Config File", the buttons for instrument and time interval are misaligned and are partially cut out.

**To Reproduce**

1. Open the tabs to the right
2. Open "Generate Config File" screen
**Expected behavior**

The buttons should not be misaligned and out of place.
**Screenshots**

Screenshot_20200107-072353

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | OnePlus 6|
|Android Version|   10.0 |

**Additional context**

**Would you like to work on the issue?**

- [ ] Yes
- [x] No
- Other:

### PR DESCRIPTION
**Pull request by angmas1**
Fixes #2063 

**Changes**: Fixed layout misalignment issue.

**Screenshot/s for the changes**: 
WhatsApp Image 2020-01-09 at 22 40 51

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: [Compress the `app-debug.apk` file into a `<feature>.rar` or `<feature>.zip` file and upload it here]

### CODE REVIEW

**Comment by angmas1** [comment]
@CloudyPadmal please review

**Comment by 991rajat** [comment]
@angmas1 Hey In my device there is a misalignment of the instrument spinner.

Device: Moto E2
Android 7.1.2

Screenshot_20200113-233630

**Comment by Sid911** [comment]
@angmas1 Please resolve Conflits and make the changes requested above 😀

**Comment by angmas1** [comment]
Just checked with latest development branch, the changes I suggested have already been made. Hence, closing PR.

**Pull request closed without merging**
