### PR TITLE
Added Long Press functionality to remaining instruments

### LINKED ISSUE #1687: Add the long press functionality to other instruments like in Power Source
**Actual Behaviour**

No message appears on long press in other instruments like in Power Source "Show Guide".

**Expected Behaviour**

"Show Guide message should appear on long press of "Show Guide" item.

**Steps to reproduce it**

Go to Power Source and long press "?" symbol

**LogCat for the issue**

Not applicable

**Screenshots of the issue**

Not applicable

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by ho-dor**
Fixes #1687 

**Changes**: Changes made in 3 instruments which didn't have long press functionality like other instruments  This brings consistency in all instruments.

**Screenshot/s for the changes**:
Screenshot_20190419-122353_PSLab

Screenshot_20190419-122413_PSLab
Screenshot_20190419-122424_PSLab

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [ ] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 
[Uploading app-debug.zip…]()

### CODE REVIEW

**Comment by neel1998** [comment]
@CloudyPadmal  kindly verify the need of this functionality in these and other devices as well. I think "?" itself is self explanatory and we don't require such long press tool tip.

**Comment by ho-dor** [comment]
@Avjeet @abhinavraj23 @CloudyPadmal please review this

**Comment by ho-dor** [comment]
@cweitat please review

**Comment by ho-dor** [comment]
@abhinavraj23 @cweitat please review

**Comment by neel1998** [comment]
@abhinavraj23 @cweitat is this required?

**Pull request merged**
