### PR TITLE
fix #2020: Alignment of "Time Interval" dropdown

### LINKED ISSUE #2020: Alignment of "Time Interval" dropdown ;Addition of 'back' button and colour contrast of instrument screen
1. - The drop-down in the time interval in "Generate Config File" is not properly aligned initially.
      The dropdown containing sec, min, hr and day is not properly aligned.
2. - There is no back button anywhere on the 'sensors' screen. When we open the Sensors in 
       the instrument(home screen), there is no option to go back to the main menu on the UI.
3. - The color contrast of the home screen is not decent. The colors are too bright and it pains in 
      eyes. 

To Reproduce the first bug;
1. Go to the "Generate Config File" section in the navigation bar.
2. See error -->The dropdown corresponding to the "Time Interval". You will be able to see the dropdown not properly aligned

To Reproduce the second Bug;
1. Go to the "Sensors" in the instruments section.
2. See error-->There is no back button anywhere in that section to return back to the home screen.

**Screenshots**
Bug-1
Bug-2
Color contrast

**Smartphone Info:**
|Device          |[Redmi Note-5 Pro]|
|Android Version|[Android 10]|

**Additional context**
Please choose a decent color contrast for the home screen.

**Would you like to work on the issue?**
 -[No]

### PR DESCRIPTION
**Pull request by dheerajkotwani**
Fix First steps for issues #2020: Alignment of "Time Interval" dropdown

**Changes**: Made the Alignment of Time Interval and instrument dropdown properly

**Screenshot/s for the changes**
alignment_pslab

**Checklist**: 
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: [Compress the `app-debug.apk` file into a `<feature>.rar` or `<feature>.zip` file and upload it here]

### CODE REVIEW

**Comment by cweitat** [comment]
Where is the colour change that you mentioned in the issue? Was it done? But don't just just the colour without furthur discussion as this affects the entire app

**Comment by dheerajkotwani** [comment]
@cweitat I had made the alignment of the dropdowns properly and didn't changed any color or theme for now as I don't think it is required.

**Comment by dheerajkotwani** [comment]
okay @CloudyPadmal will make the changes

**Comment by dheerajkotwani** [comment]
Screenshot

**Comment by dheerajkotwani** [comment]
@CloudyPadmal please check it.

**Pull request merged**
