### PR TITLE
Creates Capacitive Reactance Experiment

### PR DESCRIPTION
**Pull request by asitava1998**
Fixes issue #542 

Changes:
* Creates the Capacitive Reactance

Screenshots for the change: 
[app.zip](https://github.com/fossasia/pslab-android/files/1237886/app.zip)

### CODE REVIEW

**Comment by CloudyPadmal** [comment]
Hi @asitava1998 ! You can reuse the diode_setup xml view for this experiment view as well since it uses a similar view! :)

**Comment by viveksb007** [comment]
@asitava1998 Please update the PR by reusing the layout and resolving conflicts.

**Comment by asitava1998** [comment]
@viveksb007 @CloudyPadmal  I will update this and rest of the PRs by reusing the layout. :+1:

**Comment by viveksb007** [comment]
@asitava1998 update PRs one by one, as merging anyone would create conflict in another.

**Comment by asitava1998** [comment]
@CloudyPadmal @viveksb007 I have updated this PR. The `diode_setup.xml` has been reused.

**Pull request merged**
