### PR TITLE
fix: Smoothed the data line and changed some graph properties in Lux Meter instrument

### LINKED ISSUE #1170: Luxmeter graphs are not smooth
**Actual Behaviour**

In the Luxmeter instrument, the resulting graph is full of spikes.

**Expected Behaviour**

The graph needs to be a continuous, smooth function. Current one goes to zero frequently.
PS: This was made priority high as this is need to be fixed for data logging to have values that make sense.

**Steps to reproduce it**

Observe Luxmeter instrument graphs

**LogCat for the issue**

> Not available

**Screenshots of the issue**

device-2018-07-02-063950

**Would you like to work on the issue?**

@Vikum94

### PR DESCRIPTION
**Pull request by harsh-2711**
Fixes #1170 

**Changes**:

- Smoothed the data plot in Lux Meter

- Removed the data points from the graph which overlapped the data plot

- Changed the width of the data plot line so that it is completely visible

- Changed the high limit for Lux Meter to turn red

- Changed the onscreen visible data limit in the graph

**Screenshot/s for the changes**:
screenshot_20180716-194756

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2198946/app-debug.zip)

### CODE REVIEW

**Comment by woshikie** [comment]
image
LGTM

**Comment by woshikie** [comment]
Is it possible to plot more often, rather than once a second? It feels laggy

**Comment by harsh-2711** [comment]
@CloudyPadmal Changes done. Please remove conflicts tag. Also updated the apk after resolving merge conflicts.

**Comment by harsh-2711** [comment]
@woshikie We can plot thrice a second at most. But then the plot won't be smooth as there will be three data points at a single second. So, I think the current implementation is good.

**Comment by harsh-2711** [comment]
@woshikie @abhinavraj23 @CloudyPadmal @cweitat @Avjeet Please review

**Pull request merged**
