### PR TITLE
fix: improved lux meter with features

### LINKED ISSUE #1427: Improve Luxmeter and make design consistent
- Lux Meter Settings -> Configuration
- Map: Data points are not showing, need to add markers
- Consider having consistent design
- Export is not including all fields
- Enable GPS by default
- take out “Statistics”. Add Max, Min, Avg below graph.
- Device view and playback view should look the same

### PR DESCRIPTION
**Pull request by CloudyPadmal**
Fixes #1427 

**Changes**: 

In this PR, I have created an abstract sensor class `PSLabSensor` which holds all the necessary functions and templates needed by each sensor. Lux Meter can be taken as an example to design other sensors to have a uniform layout and a theme.

- [X] Lux Meter Settings -> Configuration
- [x] Map: Data points are not showing, need to add markers
- [X] Consider having consistent design
- [X] Export is not including all fields
- [X] Enable GPS by default
- [X] Take out “Statistics”. Add Max, Min, Avg below graph.
- [X] Device view and playback view should look the same

**Screenshot/s for the changes**: 

| Instrument view | Lux meter configs | Sample log file | Sample Markers | Readings on Map |
| -------- | --------- | -------- | -------- | -------- |
|  |  |  |  |  |

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [X] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [X] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [X] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [X] My code does not contain any extra lines or extra spaces
- [X] I have requested reviews from other members

**APK for testing**: 
[NewLuxMeter.apk.zip](https://github.com/fossasia/pslab-android/files/2560759/NewLuxMeter.apk.zip)

### CODE REVIEW

**Comment by CloudyPadmal** [comment]
Please test the APK and update here on what needs to be fixed and changed. Thanks! :)

**Comment by harsh-2711** [comment]
@CloudyPadmal In the first screenshot that you uploaded, the main reading of the gauge is overlapping with the meter readings. So can we do something about it?

**Comment by CloudyPadmal** [comment]
@harsh-2711 yes good point. I'll see if I can make an offset. @cweitat yes there was a location permission error. I've fixed that. Will update this one soon.

**Comment by CloudyPadmal** [comment]
@cweitat @harsh-2711 I've updated the PR with changes.

**Comment by CloudyPadmal** [comment]
I've completely fixed the issue #1427 and the apk is the current one. Please have a look.

**Comment by cweitat** [comment]
@CloudyPadmal have a look at codacy

**Pull request merged**
