### PR TITLE
refactor: deleted control section codes

### LINKED ISSUE #965: Remove the control section codes
**Actual Behaviour**

Now the control section is now split into power source,multimeter and wave generator but still its code is there.

**Expected Behaviour**

The control section code should be removed.

**Steps to reproduce it**

Delete it from code-base.

**LogCat for the issue**

Not applicable

**Screenshots of the issue**

Not applicable

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by abhinavraj23**
Fixes #965 

Changes:Deleted all the codes of control section

Screenshots for the change: 
Not applicable

APK for testing: [Compress the *.apk file into a rar or zip file and upload it here]
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/2066926/app-debug.apk.zip)

### CODE REVIEW

**Comment by CloudyPadmal** [comment]
Code removal is good but I have a little concern. They contain code implementation of power source, multimeter and wage generator. Would it be easier for us to refer to that code when implementing the feature in new instruments?

What are your concern about that?
- @abhinavraj23 - multimeter
- @Avjeet - wave generator

**Comment by abhinavraj23** [comment]
I don't have any problem from my side @CloudyPadmal

**Comment by harsh-2711** [comment]
@abhinavraj23  no need to remove code until all the instruments are ready as these codes are handy when making a new layout

**Comment by Avjeet** [comment]
@CloudyPadmal don't remove the code now I need the control activity for implementation we can remove after the completion of the first milestone

**Comment by CloudyPadmal** [comment]
Yes we'll drop this for now.

**Pull request closed without merging**
