### PR TITLE
Fix the crash on opening of ROBOTIC ARM

### PR DESCRIPTION
**Pull request by suman-somu**
**Fixes** #2280 

**Changes**: 

changed from android to androidx packages
- 

**Screen shots for the changes**: 

https://user-images.githubusercontent.com/75962762/140631318-32d84040-9bc0-41b6-9ad8-443d4924b931.mp4

**Checklist**: 
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding any value.
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`.
- [x] I have reformatted code and fixed indentation in every file included in this pull request
- [x] My code does not contain any extra lines or extra spaces.
- [x] I have requested reviews from maintainers.

### CODE REVIEW

**Comment by suman-somu** [comment]
@CloudyPadmal 
i have changed the andoid packages to androidx of the robotic arm 
i think, this should have been done in the pr #2254 , but might be missed. 
can you please review this pr .
thank you.

**Review by CloudyPadmal — APPROVED** [review]
Thank you for the PR! :+1:

**Comment by suman-somu** [comment]
you r welcome :D

**Comment by suman-somu** [comment]
@CloudyPadmal 
also, do will i close the issue ( which is fixed in this pr) or it will close automatically or something else ?

**Comment by CloudyPadmal** [comment]
It should be closed when referred here. Strangely it hasn't. Let me close it.

**Comment by suman-somu** [comment]
yeah .

okay

**Pull request merged**
