### PR TITLE
feat: added text inputs for Position offsets

### LINKED ISSUE #2478: Oscilloscope: Text inputs for the Position Controls feature
**Actual Behaviour**
Currently, we can only set values for X & Y offsets using _FloatSeekBars_ in the _DataAnalysisFragment_ only.

**Expected Behaviour**
We can add the functionality to input the offset values using _EditTexts_ in the fragment, as discussed in our weekly GSoC meet and as suggested by @marcnause in #2471. This would certainly improve the capabilities of the feature, as _FloatSeekBars_ can only select a specified set of values.

**Steps to reproduce it**
N/A

**LogCat for the issue**
N/A

**Screenshots of the issue**
N/A

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by AsCress**
Fixes #2478 
Enhances the Position Controls feature by adding functionality to manually input offset values using _EditTexts_. 
This is done in such a way that the current user experience of the app does not get affected.

## Changes 
- app/src/main/java/io/pslab/fragment/DataAnalysisFragment.java
- app/src/main/res/layout/position_controls.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml

## Screenshots / Recordings  
Here, is a demo of this enhancement - 

https://github.com/fossasia/pslab-android/assets/125425881/dbb8eb2c-a1bb-4057-a067-ef968d47d5a3

**Note**:
I have **purposely** not set maximum and minimum limits for the values inputted through the _EditTexts_. This does not interfere with the current functioning of this feature and has been done solely to provide more control over the measurements to the user.

**Checklist**: 
- [x] **No hard coding**: I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard coding any value.
- [x] **No end of file edits**: No modifications done at end of resource files `strings.xml`, `dimens.xml` or `colors.xml`.
- [x] **Code reformatting**: I have reformatted code and fixed indentation in every file included in this pull request.
- [x] **No extra space**: My code does not contain any extra lines or extra spaces than the ones that are necessary.

Comments on this @marcnause @CloudyPadmal ?

### CODE REVIEW

**Comment by marcnause** [comment]
@AsCress I have added some code which hides the cursor after input is done. It would be great if you could have a look and check if the change is OK.

I also noticed that it is possible to input very long numbers. Do you know any easy way to limit the length?
Screenshot_20240613-232532

**Comment by AsCress** [comment]
@marcnause Thanks for testing ! I've added limits to the offset values. Should work fine now.

**Review by CloudyPadmal — APPROVED** [review]
Looks nice! By the way, in the PR body, "Changes" section is for a brief summary of what the PR is about, not the file names..

**Review by marcnause — APPROVED** [review]

**Comment by AsCress** [comment]
> Looks nice! By the way, in the PR body, "Changes" section is for a brief summary of what the PR is about, not the file names..

@CloudyPadmal Thanks for reviewing and your comments! I'll keep that in mind.

**Pull request merged**
