### PR TITLE
Changes in SavedExperiments file

### PR DESCRIPTION
**Pull request by harsh-2711**
Fixes issue #632 

Changes: Removed Toast Message and added the case of resistance measurement experiment and Piezo Buzzer experiment

### CODE REVIEW

**Comment by harsh-2711** [comment]
@CloudyPadmal  Please review

**Comment by CloudyPadmal** [comment]
@harsh-2711 thanks for the PR! It looks good! :+1: Can you squash the commits into one?

**Comment by viveksb007** [comment]
@harsh-2711 Issue #632 is about Implementing Resistance Measurement Experiment.
This PR doesn't fixes the Issue as you have mention in PR description. Please don't provide false/incomplete information in PR description.

**Comment by akarshan96** [comment]
@harsh-2711 either close this PR or make necessary changes since it is not resolving the mentioned issue.

**Comment by CloudyPadmal** [comment]
Same PR as #750

**Pull request closed without merging**
