### PR TITLE
docs: updated fastlane metadata files

### LINKED ISSUE #1914: Update metadata in fdroid deployment
**Actual Behaviour**

Description files and icon are missing in fastlane directory for fdroid metadata

**Expected Behaviour**

Need them to be updated

**Steps to reproduce it**

Check fastlane metadata directory

**LogCat for the issue**

> Not available

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by CloudyPadmal**
Fixes #1914 

**Changes**: 
- Updated full_description, short_description files
- Added icon
- Added change logs for last two versions

**Screenshot/s for the changes**: 
> Not available

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [X] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [X] I have requested reviews from other members

**APK for testing**: 
> Not available

### CODE REVIEW

**Comment by neel1998** [comment]
@CloudyPadmal wave fitting and xy plot for waves is also working in oscilloscope now. I am not sure whether we need to inlcude that or not. Rest looks good.

**Comment by CloudyPadmal** [comment]
@neel1998 content was extracted from previous releases. Not new.

**Comment by adityastic** [comment]
@neel1998 you can make changes to the description or changelogs when uploading a new version so they get uploaded to playstore whenever we push to master

**Comment by CloudyPadmal** [comment]
These are for Fdroid.

**Pull request merged**
