### PR TITLE
Add documentation for Gyroscope

### PR DESCRIPTION
**Pull request by pranavkarthik10**
I completely explained the Gyroscope instrument in documentation form along with screenshots to accompany it. Added images to the respective folder and referenced them in the markdown.

### CODE REVIEW

**Comment by pranavkarthik10** [comment]
@adityastic @nikit19 @mariobehling Would love your thoughts on this!

**Comment by adityastic** [comment]
@CloudyPadmal @neel1998 please have a look

**Comment by pranavkarthik10** [comment]
@mariobehling Please review! 😊

**Comment by pranavkarthik10** [comment]
@NishithP2004 That is due to the images not being added yet. After PR is merged the path will work properly.

**Comment by NishithP2004** [comment]
Please correct me if I'm wrong, but isn't the PSLab documentation located in another repo with site (https://docs.pslab.io/)

**Comment by pranavkarthik10** [comment]
I believe docs are available in both repositories, the other repo is just starting out now.

**Comment by pranavkarthik10** [comment]
@CloudyPadmal @neel1998 @adityastic @nikit19 @mariobehling Please review this and merge

**Comment by NishithP2004** [comment]
@pranavkarthik10 Please add your documentation [here](https://github.com/Fossasia/pslab-documentation)

**Comment by NishithP2004** [comment]
It's clearly mentions in the task description.

**Comment by pranavkarthik10** [comment]
Thanks, I have created a PR accordingly https://github.com/fossasia/pslab-documentation/pull/57.

**Comment by pranavkarthik10** [comment]
@CloudyPadmal @neel1998 @nikit19 Please review and merge

**Comment by cweitat** [comment]
Can you create and link a issue description to this PR?

**Comment by pranavkarthik10** [comment]
@cweitat Sorry about that, I have created the issue now #2059. Would love if you could review and merge! :)

**Comment by pranavkarthik10** [comment]
Closing due to merged PR fossasia/pslab-documentation#57.

**Pull request closed without merging**
