### PR TITLE
docs: icon for developers added

### LINKED ISSUE #2189: Add icon for developers in About us.
**Actual Behaviour**

Currently in about us section there is no icon for Developers and "Connect with us" heading can be made better.

**Expected Behaviour**

Add a developers icon  and improve the visibility/appearance  of "Connect with us " text .

**Screenshots of the issue**

### PR DESCRIPTION
**Pull request by sakshi-1604**
Fixes #2189
Screenshot_1613022496

### CODE REVIEW

**Review by CodeWithSouma — COMMENTED** [review]
That's fine but can you change this icon with a simple user icon

**Comment by sakshi-1604** [comment]
ok..I will do that by today
Should I make a new pull request for that  or commit new changes in this pull request??

**Comment by sakshi-1604** [comment]
I have made follwing change..
Is it Okay now?
Screenshot_1613191018

**Review by CodeWithSouma — APPROVED** [review]
Looks good to me. @CloudyPadma sir  you can marge it

**Comment by sakshi-1604** [comment]
@CloudyPadmal     
please review

**Review by CloudyPadmal — APPROVED** [review]

**Pull request merged**
