### PR TITLE
fix: Accelerometer Record Crash Fixed #1465

### LINKED ISSUE #1465: Crashes when recording data on Accelerometer instrument and run Power Source
**Actual Behaviour**

It crashes when I record data in the accelerometer and run power source.
Doesn't work graphics at "sensors" and multimeter (nothing happens when I run it)

**Expected Behaviour**
Multimeter should work. The application should not crash.

**Would you like to work on the issue?**

Yes
screenshot_pslab_20181210-103438

### PR DESCRIPTION
**Pull request by ho-dor**
Fixes #1465 

**Changes**: Accelerometer Data, Settings Fragment added and Adapter Removed
**Screenshots for the changes**:
screenshot_20190106-143727_pslab
screenshot_20190106-143736_pslab
screenshot_20190106-143740_pslab

**Checklist**: 

- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [ ] No modifications are done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2796229/app-debug.zip)

### CODE REVIEW

**Comment by ho-dor** [comment]
@CloudyPadmal  please review.

**Comment by CloudyPadmal** [comment]
@ho-dor nice work! But the branch in this PR seems a lot behind from current development branch. Please update your working branch and update the PR.

**Comment by CloudyPadmal** [comment]
Also provide screenshots for the changed made

**Comment by ho-dor** [comment]
@CloudyPadmal I will do so in a few days as my semester exams are going on.  Thank You.

**Comment by cweitat** [comment]
Take note of Codacy and also the conflict file

**Comment by ho-dor** [comment]
Sorry for the mistake @CloudyPadmal . I am still learning git and will learn these details soon.

**Comment by CloudyPadmal** [comment]
I understand. First you need to set the current branch tracking the main repo. Add upstream link first and then track the branch. Follow these steps.
1. git remote add upstream https://github.com/fossasia/pslab-android.git
2. git checkout development
3. git branch -u upstream/development
4. git fetch upstream
5. git pull
- now resolve conflicts and merge the changes if any
6. git reset --soft upstream/development
7. git add (relevant files)
8. git commit -m 'message'
9. git push -f origin development

Here I assumed development is the branch you're working on. Let me know if there's any issue.

**Comment by ho-dor** [comment]
I have followed the above steps by following internet . Is there an issue
with this PR as well ? I have fetched and updated my repo today only before
updating this PR .
And Yes , I am working on the development branch.

**Comment by cweitat** [comment]
@ho-dor please see Codacy, fix things, especially the unused imports.

**Comment by CloudyPadmal** [comment]
@ho-dor if you followed the steps, after the force push, there should be a commit after my message. Strange.

**Comment by CloudyPadmal** [comment]
This PR reverts all the previously merged PRs for some time. Hence added the invalid label. Fix it by following the steps provided using an active internet connection may be.

**Comment by ho-dor** [comment]
@CloudyPadmal  I meant to say that I had followed these steps before creating this PR but I must have missed some steps. But now I have followed the above steps and updated this PR.
\

**Comment by ho-dor** [comment]
@cweitat I fixed the codacy problem of Log statements and unused imports but missed some of them, I have updated it now.

**Comment by CloudyPadmal** [comment]
@ho-dor please follow these [steps](https://github.com/fossasia/pslab-android/pull/1521#issuecomment-452393940). I don't understand why it's so hard. This PR is stalling 4000 line changes?

**Comment by ho-dor** [comment]
@CloudyPadmal The Travis/CI error is happening because there is no BaroData model in my local repo . So , I tried pulling the changes from upstream to my local repo using 
git fetch upstream
git checkout development
git pull https://github.com/fossasia/pslab-android.git development
git merge upstream/development

But all the commands return "Already up to date". But I can see that I don't have files in my local repo like BaroData.
How to solve this ? Thanks.

**Comment by CloudyPadmal** [comment]
I've been telling for days, Try following the **exact** commands and steps stated above without any modifications.

**Comment by ho-dor** [comment]
All the updates I have made in this PR have been by following the exact steps and I have been doing it for days . The repo shows "Already upto date" even if I don't have BaroData file in my local repo . that is why I used the different commands to resolve the error

**Comment by CloudyPadmal** [comment]
@ho-dor can you show me where is `git merge upstream/development` in the steps I have given?

**Pull request closed without merging**
