### PR TITLE
Modified Oscilloscope UI to include selection of plotting data from in-built Mic

### LINKED ISSUE #325: modify Oscilloscope UI to include selection of plotting data from in-built Mic
**Actual Behaviour**

Currently there is no provision in Oscilloscope UI to select in-built Mic.

**Expected Behaviour**

Oscilloscope UI should provide option to select in-built mic.

**Steps to reproduce it**

Applications -> Oscilloscope

**LogCat for the issue**

NA

**Screenshots of the issue**

NA

**Would you like to work on the issue?**

Nope @akarshan96 could handle it better.

### PR DESCRIPTION
**Pull request by akarshan96**
Fixes #325 
Changes: 
-Added option for inbuilt mic in Oscilloscope

Screenshots for the change: 

screenshot_1500232844

### CODE REVIEW

**Comment by viveksb007** [comment]
@akarshan96 I think we should put mic and in-built mic in a spinner for selection. We can create a custom spinner of checkboxes. What do you think?

**Comment by CloudyPadmal** [comment]
Or a `Switch Button`?

**Comment by asitava1998** [comment]
Switch button will be a good option, custom spinner as mentioned by Vivek is also a good idea as an extra line makes the UI non-uniform.

**Comment by akarshan96** [comment]
@viveksb007 let me try adding it. I will compare both custom spinner and switch and send the screenshots

**Comment by akarshan96** [comment]
@viveksb007 @asitava1998 @CloudyPadmal, how about this?
screenshot_1500278749

**Comment by viveksb007** [comment]
Looks good 👍

**Comment by akarshan96** [comment]
This is another approach for the same, see which one is better @viveksb007 @asitava1998 @CloudyPadmal  
screenshot_1500271692

**Comment by viveksb007** [comment]
First one looks better as it doesn't cover screen at any point.

**Comment by CloudyPadmal** [comment]
Nice work @akarshan96 ! A little question, does it need a checkbox in the spinner? also a header?

**Comment by viveksb007** [comment]
@akarshan96 could you please provide an apk for testing?

**Comment by akarshan96** [comment]
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1155115/app-debug.apk.zip)

@viveksb007 here is the apk, but when I tried to implement it further I noticed that the checkbox can't able to retain the checks in the checkbox. I am still trying to do that

**Comment by viveksb007** [comment]
@akarshan96 tested the apk
two things
- Disable default ```CH1``` selection, its not solving any purpose and hindering in try other things with oscilloscope activity
- On selecting option by clicking on select Mic, label still says select Mic instead of the option that I selected. Suppose I selected ```In-build Mic```, it still says Select Mic, it should change to ```In-built Mic```.
If its posing any difficulty you could create normal spinner with 2 values ```Mic``` and ```In-built Mic``` and a checkbox beside it. When checkbox is checked, it would take input from whatever is selected in spinner.
Hope its clear. Thanks

**Comment by akarshan96** [comment]
@viveksb007 I have made the changes. 
Apk link: [app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1155374/app-debug.apk.zip)

screenshot_1500370603

**Comment by viveksb007** [comment]
@akarshan96 Yeah looks good. Just one thing I tested with pslab device and it isn't plotting mic input from pslab device. you need to make corresponding changed in monitoring thread too.

**Comment by akarshan96** [comment]
@viveksb007 made the suggested changes.
Apk:
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1155687/app-debug.apk.zip)

**Pull request merged**
