### PR TITLE
fix: Crash of app on opening Configurations of Accelerometer and Multimeter Activity

### PR DESCRIPTION
**Pull request by imrajat7**
**Fixes**: #1416 

**Changes**: Changes in Accelerometer and Multimeter activity by adding putExtra with the intent for both the activities.

**Screenshot/s for the changes**: 
ss1
ss2

**Checklist**:
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2502322/app-debug.zip)

### CODE REVIEW

**Comment by imrajat7** [comment]
@CloudyPadmal Are you talking about the title of the PR ?

**Comment by CloudyPadmal** [comment]
No, the "Settings" should be "Configurations"

**Comment by imrajat7** [comment]
Ok, I will correct it.

**Comment by imrajat7** [comment]
@CloudyPadmal I made the changes as suggested. Please let me know if any other changes required.

**Pull request merged**
