### PR TITLE
docs: update readme with new app link

### LINKED ISSUE #1317: Update readme with Google Play app link
**Actual Behaviour**

New app with `org.pslab` package name is now online.

**Expected Behaviour**

Replace the existing banners for Google Play in readme file with the new one.

**Steps to reproduce it**

Check Google Play link in Readme file

**LogCat for the issue**

> Not available

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by CloudyPadmal**
Fixes #1317 

**Changes**: 
- Replaced `org.fossasia.pslab` with `org.pslab`

**Screenshot/s for the changes**: 
> Not available

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [X] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [X] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [X] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [X] My code does not contain any extra lines or extra spaces
- [X] I have requested reviews from other members

**APK for testing**: 
> Not available

### CODE REVIEW

**Comment by CloudyPadmal** [comment]
Thank you @asitava1998 :)

**Comment by Avjeet** [comment]
@CloudyPadmal Could you replace one image having a dialog box with a screenshot showing bottom sheet in this PR only.

**Comment by CloudyPadmal** [comment]
@Avjeet please refer to the issue this PR is resolving.

**Comment by CloudyPadmal** [comment]
Thank you @Avjeet ! :+1:

**Pull request merged**
