### PR TITLE
Update wave generator UI

### LINKED ISSUE #1832: Make UI of Wave Generator more comprehensible
**Actual Behaviour**
User can not exactly understand the use of different buttons and mode from current UI

**Expected Behaviour**
Make the UI more comprehensible. Show those buttons which are related to the current mode (square/pwm) . The buttons will toggle upon changing the mode

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by neel1998**
Fixes #1832

**Changes**: show controls of only the mode which is selected , i.e square mode or PWM mode

**Screenshot/s for the changes**: 

### PWM mode

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**:  
[wave_ui.zip](https://github.com/fossasia/pslab-android/files/3387818/wave_ui.zip)

### CODE REVIEW

**Comment by CloudyPadmal** [comment]
I guess this is still WIP right? Different button sizes, different paddings, margins.

**Comment by neel1998** [comment]
@CloudyPadmal  have a look at this. I have removed the set button, now every time freq, duty, phase is changed, it will be set automatically.

**Comment by neel1998** [comment]
@CloudyPadmal thanks for the review. I will try making the UI as much user friendly as possible. Regarding SQR1 on the first screen we allow user to generate one SQR wave in square mode as well...That's why I kept it there

**Comment by CloudyPadmal** [comment]
We'll break it as Analog and Digital. Otherwise it's a mixed up.

**Comment by neel1998** [comment]
So one screen should only have Wave1 and Wave2 options (analog) and other will ha e SQR1,SQR2,SQR3,SQR4.. (digital)?

**Comment by CloudyPadmal** [comment]
Yes

**Comment by neel1998** [comment]
@CloudyPadmal i have updated the UI. Please check the edited screenshots and apk. Thanks

**Comment by CloudyPadmal** [comment]
@neel1998 ok let's first sketch it on a piece of paper and start from that. 

Different sized buttons with no pattern at all. :( Does it look nice to you?

**Comment by neel1998** [comment]
Arrangement looks better than before. We can think something for button size

**Comment by CloudyPadmal** [comment]
CC: @cweitat @woshikie

**Comment by cweitat** [comment]
What I see is there's too much space wasted at the buttons. You can cluster all buttons on the right side like what Padmal has posted. We can keep the slider at the bottom. 

Unused buttons for different modes means the buttons should be hidden instead of disabled. 

@woshikie opinions?

**Comment by neel1998** [comment]
@cweitat on it.

**Comment by neel1998** [comment]
@CloudyPadmal  @cweitat please have a look at this new layout. About hiding buttons the unused buttons, i think it would look weird leaving blank space in between, and changing sizes of other buttons accordingly to fill the gap would also not look good according to me.

**Comment by CloudyPadmal** [comment]
At least make the padding between buttons similar. Move "Phase" to same side. Read the points I've given again.

**Comment by neel1998** [comment]
@CloudyPadmal

**Comment by CloudyPadmal** [comment]
> @neel1998
> 
>     1. Can we have similar dimensions for the buttons?
> 
>     2. What does `SQR1` doing in the first screen?
> 
>     3. What are the two `Freq` buttons?
> 
>     4. Do the titles match? Waveform and Digital??? Not Analog and Digital?
> 
>     5. First screen has Phase on left side. On the second screen phase on right side.
> 
>     6. Lot of space wasted on the black area. You can get an idea on how to set layout using real devices.
> 

Read all the points and see if it's done. I dunno it's very hard to make you understand things. For days you're working on a UI

**Comment by neel1998** [comment]
@CloudyPadmal  I have also been working on bluetooth and csv meta data issues.

Except the 1st point , others are satisfied I think. For the similar dimension of the buttons, i can make them same but that would leave lots of white space, bcz in analog mode there are only 2 buttons : wave 1 and wave 2 and in digital there are 4 buttons, if i reduce size of wave buttons , it will leave white space on both sides. Still if you want i can make that change

**Comment by cweitat** [comment]
It's also okay to keep the buttons same size. I don't understand why do you need to always fill the screen?

Main point of the buttons is that as long as it is not too small for the user to press, it's sufficient.

**Comment by CloudyPadmal** [comment]
Last time I'm going to comment on this. It's getting really annoyed.

 **READ THIS**
>     5. First screen has Phase on left side. On the second screen phase on right side.

**Comment by neel1998** [comment]
@CloudyPadmal  i am really sorry. I thought you were saying about the positions of the phase buttons. That's why i changed those. Sorry for the incovinience. Will change the text in black screen.

**Comment by neel1998** [comment]
@CloudyPadmal  really very sorry for the delay . Will not happen from the next time

**Comment by cweitat** [comment]
Did you saw my remarks?

**Comment by neel1998** [comment]
@cweitat i saw your remark. But after moving buttons to right, i thought they are looking proper. But if you think rectangle standard buttons would look good i can change it. But that wouldn't keep the alignment in the whole layout.

**Comment by CloudyPadmal** [comment]
Where's the triangular waveform button now?

**Comment by neel1998** [comment]
> Where's the triangular waveform button now?

The sine wave and triangular wave buttons toggle.

**Pull request merged**
