### PR TITLE
Fixes #266 : Add Advanced Control UI xml to layout-hdpi

### LINKED ISSUE #266: Add Advanced Control UI to layout-hdpi folder
**Actual Behaviour**

`fragment_control_advanced.xml` file is not available in the layout-hdpi folder. This causes deformations in some devices with screen size of hdpi

**Expected Behaviour**

The file should be available in the layout-hdpi folder to ensure that the specific layout file will be rendered in hdpi screens

**Steps to reproduce it**

1. Open app
2. Go to `Applications`
3. Select `Control` and go to `Advanced` section using a device with hdpi screen (This might not observable in some cases, in such a case use a different model with hdpi screen)

**LogCat for the issue**

> Not available

**Screenshots of the issue**

scr

**Would you like to work on the issue?**

Yes! I can send the PR with the fix soon! :+1:

### PR DESCRIPTION
**Pull request by CloudyPadmal**
Fixes issue #266 

Changes: 
- Added `fragment_control_advanced.xml` file to layout-hdpi. This ensures that all devices with hdpi screens will use the layout instead of the xhdpi layout 

Screenshots for the change: 
Screen

APK for testing:
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1119700/app-debug.apk.zip)

### CODE REVIEW

**Comment by akarshan96** [comment]
Hi @CloudyPadmal, I am getting this layout on my device. The z of 5kHz is not in the same line.
Thanks.

screenshot_2017-07-07-19-23-01-377_org fossasia pslab

**Comment by CloudyPadmal** [comment]
Hello @akarshan96 ! Thanks for checking! :+1: What is the screen size of your device? :)

**Comment by CloudyPadmal** [comment]
@akarshan96 Can you have a look at this [apk](https://github.com/fossasia/pslab-android/files/1131387/app-debug.apk.zip)? :)

**Comment by akarshan96** [comment]
@CloudyPadmal the problem is solved now 👍

**Comment by CloudyPadmal** [comment]
That's awesome @akarshan96 !! :100: Thanks a lot for the review guys! :blush:

**Comment by CloudyPadmal** [comment]
Thanks guys for the review! :+1: :100:

**Pull request merged**
