### PR TITLE
save graph function added to compass, gyroscope and accelerometer

### LINKED ISSUE #1705: Implement save graph function for accelerometer
**Actual Behaviour**
Currently save graph function is not implemented for accelerometer

**Expected Behaviour**
Simpleng the save graph function like barometer and lux meter

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by neel1998**
Fixes #1705 #1709 #1712

**Changes**:Implemented saveGraph function to gyroscope, compass and gyroscope

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**:
[save_graph.zip](https://github.com/fossasia/pslab-android/files/3184114/save_graph.zip)

@ho-dor  @Smit2010  @CloudyPadmal  kindly review

### CODE REVIEW

**Comment by cweitat** [comment]
Conflict

**Comment by neel1998** [comment]
@cweitat i have resolved the conflicts. Kindly check

**Comment by neel1998** [comment]
@cweitat  @CloudyPadmal  kindly review

**Comment by ho-dor** [comment]
@neel1998 is your branch updated ? The accelerometer configuration changes are not reflected in your apk.

**Comment by neel1998** [comment]
@ho-dor  I made this PR before those changes were merged. Since they are in differernt file they won't cause any trouble with changes in this PR.

**Comment by ho-dor** [comment]
@neel1998 can you tell me where is the option to save the graph in gallery ? Can't seem to find it .

**Comment by neel1998** [comment]
Open a log in DataloggerActivity..there with play button , there is a button with save image I'm the actionbar.

**Comment by ho-dor** [comment]
But in my device it is not saving the graph in gallery . It is showing the same message which is shown when we record data . @Smit2010  can you please verify.

**Comment by neel1998** [comment]
It is stored in the same folder where your logs are stored as jpeg. Please check there

**Comment by neel1998** [comment]
Kindly go through code once to understand of this function is implemented

**Comment by ho-dor** [comment]
Ok . I got it . I was confused because the Todo in the code mentioned save in gallery.

**Comment by neel1998** [comment]
@CloudyPadmal @cweitat please review

**Comment by cweitat** [comment]
@neel1998  fix codacy 
https://app.codacy.com/app/woshikie/pslab-android/commit?cid=359270568&fileBranchId=12751500#newIssuesView

**Comment by neel1998** [comment]
@cweitat  @mariobehling  i think this can be merged

**Pull request merged**
