### PR TITLE
Fixed the guide re-open issue in accelerometer

### LINKED ISSUE #1459: Unable to open the guide from bottom of the screen of Accelerometer
**Actual Behaviour**

When we try to re-open the guide from the bottom of the screen, it isn't opening

**Expected Behaviour**

When we slide up from the bottom of the screen, the guide should re-open

**Steps to reproduce it**

Open the Accelerometer and slide up from the bottom of the screen

**LogCat for the issue**

Not Applicable

**Screenshots of the issue**

Not Applicable

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by ho-dor**
Fixes #1459

**Changes**: onTouchEvent method added in the AccelerometerActivity

**Screenshot/s for the changes**: 
accelerometer

**Checklist**: 
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications are done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 

[accelerometer_guide_re-open.zip](https://github.com/fossasia/pslab-android/files/2660334/accelerometer_guide_re-open.zip)

### CODE REVIEW

**Comment by ho-dor** [comment]
Please review @CloudyPadmal @cweitat @abhinavraj23

**Comment by ho-dor** [comment]
Can anyone help me as to why one of the checks is failing? I am not able to understand the error.

**Comment by CloudyPadmal** [comment]
@ho-dor 
```
/home/travis/build/fossasia/pslab-android/app/src/main/java/io/pslab/activity/AccelerometerActivity.java:324: error: cannot find symbol
    public boolean onTouchEvent(MotionEvent event) {
                                ^
  symbol:   class MotionEvent
  location: class AccelerometerActivity
```

**Comment by CloudyPadmal** [comment]
@ho-dor do not add `[` `]` brackets in the PR message body. Please follow the template. Thanks.

**Comment by ho-dor** [comment]
@CloudyPadmal @abhinavraj23  can you please help me with the travis CI error . Could not find what is wrong with the MotionEvent symbol as it is working fine in android studio and working in the app.

**Comment by CloudyPadmal** [comment]
The import statement is not in the code you pushed.

**Pull request closed without merging**
