### PR TITLE
Migrate to Kotlin DSL & Misc. Improvements

### PR DESCRIPTION
**Pull request by theimpulson**
## Changes 
- Migrate to new Int only Sdk version properties
- Enable Java language 11 features
- Migrate Gradle files to new Kotlin DSL
- Set appropriate namespace for the project

## Screenshots / Recordings  

Not applicable

**Checklist**: 
- [x] **No hard coding**: I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard coding any value.
- [x] **No end of file edits**: No modifications done at end of resource files `strings.xml`, `dimens.xml` or `colors.xml`.
- [x] **Code reformatting**: I have reformatted code and fixed indentation in every file included in this pull request.
- [x] **No extra space**: My code does not contain any extra lines or extra spaces than the ones that are necessary.

### CODE REVIEW

**Comment by theimpulson** [comment]
@bessman could you please review (and merge) this PR when possible?

**Comment by bessman** [comment]
@CloudyPadmal do you have time to take a look?

**Comment by CloudyPadmal** [comment]
Hi @theimpulson,

Thank you for the PR!

I'm wondering if migrating to Kotlin might potentially disrupt current development. Perhaps we could push these new changes to a new branch? I can create one right away. ▶️ kotlin
Can you please rebase the PR to `pslab-android/kotlin`?

My knowledge on Kotlin is 0%. The build passes, so I guess the PR is OK!

On a separate note, the current Java-based app requires some updates to ensure it runs again on Google Play Store. Given this task, I'm a bit uncertain about attempting to migrate 39890 **_lines_** of code singlehandedly.

<details> 
  <summary>In case you wonder how I got the number of lines of code 😃 </summary>
   <pre>git ls-files | grep '\.java' | xargs wc -l</pre>
</details>

**Comment by CloudyPadmal** [comment]
@mariobehling FYI

**Comment by theimpulson** [comment]
> Hi @theimpulson,
> 
> Thank you for the PR!
> 
> I'm wondering if migrating to Kotlin might potentially disrupt current development. Perhaps we could push these new changes to a new branch? I can create one right away. ▶️ kotlin Can you please rebase the PR to `pslab-android/kotlin`?
> 
> My knowledge on Kotlin is 0%. The build passes, so I guess the PR is OK!
> 
> On a separate note, the current Java-based app requires some updates to ensure it runs again on Google Play Store. Given this task, I'm a bit uncertain about attempting to migrate 39890 **_lines_** of code singlehandedly.
> In case you wonder how I got the number of lines of code 😃

Thanks, I don't mind rebasing but I am afraid that would just result in the code being unused for a certain period of time and the branch maintainer/contributor will have to keep it updated with the current branch as an additional burden. Kotlin is now the future and is interoperable with Java. I think this is high time to migrate to it to avoid incurring more tech debt. Keeping Kotlin code in the main branch will allow new contributors and maintainers to write code in Kotlin instead of Java. As I proposed in the matrix chat, I can create the migration PRs individually with a small codebase (for easy review). This PR for instance is standalone.

If you would still prefer me to rebase it against the kotlin branch, please let me know and I will do so.

**Comment by CloudyPadmal** [comment]
Let's wait for @mariobehling 's input on this.

**Review by CloudyPadmal — APPROVED** [review]

**Pull request merged**
