### PR TITLE
feat: added programmatic support for orientation change to the Wave Generator screen

### LINKED ISSUE #2434: Wave Generator: unit of phase is lost after orientation change
**Actual Behaviour**

When the orientation is changed, the unit of the phase offset is lost and `null` is displayed instead.

**Expected Behaviour**

The correct unit is always displayed for every value under any circumstances.

**Steps to reproduce it**

1. Open the app
2. Change to Wave Generator screen
3. Tap button labeled "Wave 2"
4. Tap button labeled "Phase"
5. Set value for phase via seekbar
6. Change orientation of the phone

**Screenshots of the issue**

image

**Would you like to work on the issue?**

Maybe.

### LINKED ISSUE #2435: Wave Generator: value for phase offset is set on orientation change, even if user has entered none
**Actual Behaviour**

After orientation change a values is set for phase offset on orientation chnage, even if user has not entered any value.

**Expected Behaviour**

Displayed values should always reflect input of user (or default values).

**Steps to reproduce it**

1. Open app
2. Choose Wave Generator
3. Tap Frequency button
4. Set frequency via seekbar
5. Change orientation of device

**Screenshots of the issue**

image

Maybe.

### PR DESCRIPTION
**Pull request by AsCress**
Fixes #2434, fixes #2435 and any other issues that were arising when the orientation of the Wave Generator screen was changed, including data loss, etc.

## Changes 
- app/src/main/java/io/pslab/activity/WaveGeneratorActivity.java

**Checklist**: 
- [x] **No hard coding**: I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard coding any value.
- [x] **No end of file edits**: No modifications done at end of resource files `strings.xml`, `dimens.xml` or `colors.xml`.
- [x] **Code reformatting**: I have reformatted code and fixed indentation in every file included in this pull request.
- [x] **No extra space**: My code does not contain any extra lines or extra spaces than the ones that are necessary.

### CODE REVIEW

**Comment by AsCress** [comment]
@marcnause This should fix all the issues that were arising on changing the orientation of the Wave Generator screen.

**Comment by AsCress** [comment]
This yet needs some work to properly integrate with the newly created layouts for horizontal orientation.

**Comment by AsCress** [comment]
@marcnause Now all the issues regarding change in orientation should be fixed. Can you test it please ?

**Comment by marcnause** [comment]
@AsCress Looking good, but I found one case where data is not displayed after orientation change, even though the data is not lost. It's the frequency of a digital wave. It is displayed again once the "Frequency"-button is tapped.

The buttons also behave a little bit odd, but I will write new tickets for that since I think it is out of scope here.


https://github.com/fossasia/pslab-android/assets/11596220/166ea8df-0442-4d00-9983-f08f4a27dd98

**Comment by AsCress** [comment]
@marcnause Fixed it. Should be displaying correctly now.

**Comment by marcnause** [comment]
@AsCress Yes, the frequency value is displayed correctly now. 

I am sorry, I just noticed something I did not notice before: 

If you 

1. Open the app
2. Choose Wave Genarator
3. Tap "Digital" button
4. Tap "Freq" button
5. Set frequency via slider
6. Change screen orientation
7. Change screen orientation again
8. Tap "Freq" button

the progress of the seekbar is not set / set to the minimal value.

I would expect the frequency which is correctly displayed, to also be set in the seekbar once the "Freq" button is tapped.

(Sorry, no video this time, Android Studio always cuts off the end of the recorded video. 🤬)

**Comment by AsCress** [comment]
@marcnause That's a nice suggestion. I've fixed that and I also noticed that the freq/phase/duty buttons were getting automatically selected upon rotation, fixed that too. Please inform me if you notice any other issue, or feel that something shouldn't be the way it is.
Also, I noticed that this was happening because initially in the app, a common frequency was set for all the PWM buttons (i.e., all the buttons, SQR1, SQR2, SQR3, SQR4 would remain at a single frequency at a time). I was wondering why that was set that way, I don't know if it is due to some hardware limitation or something.
However, since we have now changed the buttons to support different frequencies, I was wondering did you test these with the PSLab device, if it can actually generate different frequencies at different outputs for the SQR1, SQR2, SQR3 and SQR4 buttons ?

**Comment by marcnause** [comment]
@AsCress I checked the comments in the PSlab Python Library again and in [line 371 of https://github.com/fossasia/pslab-python/blob/development/pslab/instrument/waveform_generator.py](https://github.com/fossasia/pslab-python/blob/development/pslab/instrument/waveform_generator.py#L371) it says:

> Frequency in Hz. Shared by all outputs.

So it seems to be a limitation of the hardware.

**Comment by AsCress** [comment]
@marcnause Right. So then we should ideally configure the app to calibrate frequencies for all the channels and set it to a single frequency.

**Comment by AsCress** [comment]
@mariobehling @CloudyPadmal This PR can now be reviewed and merged.

**Comment by marcnause** [comment]
@AsCress Could you please run code reformat (Ctrl + Alt + L)  on app/src/main/java/io/pslab/activity/WaveGeneratorActivity.java? There are a few lines missing some spaces after `if` and `switch`.

Apart from that the screen works as expected now. 👍

**Comment by AsCress** [comment]
@marcnause Done. I've reformatted the code.

**Review by marcnause — APPROVED** [review]

**Pull request merged**
