### PR TITLE
Time interval units issue solved.

### PR DESCRIPTION
**Pull request by nsharmahack3r**
Fixes #[

#2188 . Note: This will automatically closes the issue.

**Changes**: [Add here what changes were made in this issue and if possible provide links.]

**Screenshot/s for the changes**: Screenshot_1612907455

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: [[feature.zip](https://github.com/fossasia/pslab-android/files/5954541/feature.zip)]

### CODE REVIEW

**Review by asaikarthikeya — APPROVED** [review]
Squash the commits .

**Comment by nsharmahack3r** [comment]
Hi I am new to open source. And by mistake, I closed the pull request instead of squashing. Will that cause trouble ?

**Comment by nsharmahack3r** [comment]
How do I squash the commits ?

**Comment by CodeWithSouma** [comment]
> How do I squash the commits ?

please check the [README](https://github.com/fossasia/pslab-android/blob/development/README.md) on you can find how to git squash?

**Review by CodeWithSouma — APPROVED** [review]
Looks good to me

**Comment by CloudyPadmal** [comment]
We opt to do a make over. Closing this trivial fix.

**Pull request closed without merging**
