### PR TITLE
Fixes #420 : Checks final voltage and initial voltage

### LINKED ISSUE #420: Current experiments do not check initial and final value differences
**Actual Behaviour**

In the current implementations of saved experiments, do not validate to see if the initial voltages are lesser or greater (BJT (less) and FET (great))

**Expected Behaviour**

Initial values should be matched with final values. Otherwise they will result in a negative step size which will cause an infinity for loop

**Steps to reproduce it**

1. Open app
2. Go to `Saved Experiments`
3. Choose `BJT CB Characteristics` experiment
4. Set initial value higher than final value and start experiment to observe

[Result could decrement for loop exiting variable](https://github.com/fossasia/pslab-android/blob/master/app/src/main/java/org/fossasia/pslab/experimentsetup/TransistorCBSetup.java#L148)

**LogCat for the issue**

> Not available

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

Yes! I will implement a common method to overcome this as I am implementing FET related experiments at the moment.

### PR DESCRIPTION
**Pull request by CloudyPadmal**
Fixes issue #420 

Changes: 
- Added a check to final voltage values when they are set to function parameters

Screenshots for the change: 

fix

### CODE REVIEW

**Comment by CloudyPadmal** [comment]
APK for testing:

[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1199744/app-debug.apk.zip)

**Comment by CloudyPadmal** [comment]
Thanks a lot @viveksb007 for the review! I was wondering what if we put a slider here instead of an edit text? :thinking:

**Comment by viveksb007** [comment]
I think EditText is better. Slider actually is difficult to adjust to specific values and we don't need it continuously. Its one time input to start experiment.

**Comment by CloudyPadmal** [comment]
Yea that's a very good point! :+1:

**Pull request merged**
