### PR TITLE
Fix #1603 pin layout option removed from faq/about fragment

### LINKED ISSUE #1603: Unnecessary actionbar menu in FAQ and About us Activity
**Actual Behaviour**
Currently the action bar menu in FAQ and about us activity have "show pin layout option"

**Expected Behaviour**

FAQ and About activity don't require option to show pin layout
**Steps to reproduce it**
Open FAQ / About Us activity

**Screenshots of the issue**
screenshot_20190308-025800
screenshot_20190308-025754

**Would you like to work on the issue?**
yes

### PR DESCRIPTION
**Pull request by neel1998**
Fixes #1603 
**Changes**:Removed unnecessary menu items from FAQ / about fragment. 
**Screenshot/s for the changes**:
screenshot_20190308-122601
screenshot_20190308-122555

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

### CODE REVIEW

**Comment by neel1998** [comment]
@harsh-2711  @cweitat  please review

**Comment by harsh-2711** [comment]
@neel1998 What is the need to remove the pin layout option? I think keeping the toolbar uniform provides a good UI. Also, the pin layout suits more in the FAQ section so that the user can follow the instructions side by side. What do you think?

**Comment by neel1998** [comment]
@harsh-2711 I understand your points. But still I don't find it useful in case of about page. We can keep it for FAQ if you want

**Comment by harsh-2711** [comment]
I think it should be uniform. @cweitat @CloudyPadmal What do you say?

**Comment by mariobehling** [comment]
Change not needed atm. Please help to focus on functionality issues of actual instruments as well as implementing data logging (recording in all instruments).

**Pull request closed without merging**
