### PR TITLE
Created figures for electrical experiment

### LINKED ISSUE #712: Figures missing in many saved experiments
**Actual Behaviour**

In many saved experiments it has been mentioned "as shown in the figure" but the figure is missing

**Expected Behaviour**

The figures should appear

**Screenshots of the issue**

screenshot_20180210-010555

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by abhinavraj23**
Changes: Added figures for the electrical experiment. Partially fixed #712'

Screenshots for the change: 
electricalexperiment

### CODE REVIEW

**Comment by CloudyPadmal** [comment]
Can you provide the APK please? PR looks good!

**Comment by abhinavraj23** [comment]
Thank you @CloudyPadmal. Do you require the regular debug apk or a signed apk??

**Comment by CloudyPadmal** [comment]
@abhinavraj23 Yes please! Because it includes modifications to the application!

**Comment by abhinavraj23** [comment]
[app-debug.zip](https://github.com/fossasia/pslab-android/files/1734491/app-debug.zip)

**Comment by abhinavraj23** [comment]
@CloudyPadmal this is the regular debug apk

**Comment by abhinavraj23** [comment]
Thank you @CloudyPadmal

**Comment by abhinavraj23** [comment]
Please merge it and close the PR so that I will be able to do more PRs

**Comment by CloudyPadmal** [comment]
@abhinavraj23 you can continue fixing other issues. Each PR needs to be at least reviewed by two reviewers.

**Comment by abhinavraj23** [comment]
Wasn't knowing that, thank you @CloudyPadmal

**Pull request merged**
