### PR TITLE
Implemented Graph in SensorFragmentTSL2561

### PR DESCRIPTION
**Pull request by akarshan96**
Fixes issue #403 

Screenshots for the change: 

tsl

### CODE REVIEW

**Comment by viveksb007** [comment]
@akarshan96 ```Lux``` on Y-axis is luminous intensity right? So SI unit candela (cd) can  be added to Y-axis label. 
And Please edit the PR template accordingly.

**Comment by asitava1998** [comment]
@akarshan96 The sensor actually measures `Illuminance` of a surface and not the luminous intensity. The unit is Lux. [https://www.sparkfun.com/products/12055](https://www.sparkfun.com/products/12055)

**Comment by akarshan96** [comment]
Okay @asitava1998. Can I write just `Illum.` instead of  `Illuminance` occupies more space even when rotated?

**Comment by akarshan96** [comment]
Made the requested changes, sharing the screenshot.

yom

**Pull request merged**
