### PR TITLE
feat: Added CCS811 Digital Gas Sensor

### PR DESCRIPTION
**Pull request by AsCress**
Adds support for the **CCS811 Digital Gas Sensor**.

The **CCS811** is an ultra-low-power digital gas sensor for monitoring indoor air quality (IAQ). It is designed to detect a wide range of volatile organic compounds (VOCs) and measure carbon dioxide (CO2) levels in the atmosphere. Here are some features:

**1. VOC Detection:** The CCS811 sensor can detect a wide variety of volatile organic compounds (VOCs), including alcohols, aldehydes, ketones, and organic acids.
**2. CO2 Sensing:** In addition to VOC detection, the CCS811 sensor is equipped with a built-in carbon dioxide (CO2) sensor. It can measure CO2 levels in the atmosphere
**3. Dynamic Baseline Correction (DBC):** The sensor employs dynamic baseline correction algorithms to compensate for sensor drift over time. This ensures long-term stability and accuracy in VOC and CO2 measurements
**4. On-Chip Processing:** The CCS811 sensor includes on-chip processing capabilities, allowing it to perform real-time data processing and output calibrated air quality measurements directly to the host microcontroller.

## Changes 
- The UI for the sensor (_sensor_ccs811.xml_) is developed akin to the UI for the existing sensors, providing raw data and graphical plots in a clear and user-friendly manner.
- The sensor activity (_SensorCCS811.java_) follows on a similar pattern as the already present sensors.
- A dedicated communication library for the sensor (_CCS811.java_) is developed using the existing one in the python repository as a reference.

## Screenshots / Recordings  
N/A

**Checklist**: 
- [x] **No hard coding**: I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard coding any value.
- [x] **No end of file edits**: No modifications done at end of resource files `strings.xml`, `dimens.xml` or `colors.xml`.
- [x] **Code reformatting**: I have reformatted code and fixed indentation in every file included in this pull request.
- [x] **No extra space**: My code does not contain any extra lines or extra spaces than the ones that are necessary.

**Note:-**
I haven't been able to test this because I don't have this sensor as of yet. 
@marcnause Could you please help me with testing this ?

## Summary by Sourcery

Introduce support for the CCS811 digital gas sensor, including a dedicated communication library and a user interface for displaying sensor data. This addition allows for monitoring indoor air quality by detecting VOCs and measuring CO2 levels.

New Features:
- Add support for the CCS811 digital gas sensor, enabling detection of volatile organic compounds (VOCs) and measurement of carbon dioxide (CO2) levels.

Enhancements:
- Develop a user interface for the CCS811 sensor, providing raw data and graphical plots in a user-friendly manner similar to existing sensors.

### CODE REVIEW

**Comment by marcnause** [comment]
I was able to test the sensor, but I did not get valid values (see screenshot). I also attached the log messages: [logcat.txt](https://github.com/user-attachments/files/16576038/logcat.txt)

**Comment by AsCress** [comment]
@marcnause Thank you very much for testing with the sensor ! I guess there is an issue with the configuring procedure of the sensor, which is causing the sensor to show these junk values. I'll push an update to this PR soon.

**Comment by AsCress** [comment]
@marcnause Could you please once test with the sensor again ?

**Comment by marcnause** [comment]
I have tested with the new version. The displayed values match the values from the previous screenshot.

I have attached a new log file: [log.txt](https://github.com/user-attachments/files/16590936/log.txt)

**Comment by marcnause** [comment]
I checked that my sensor is working OK with an Arduino and it worked fine (after connecting `WAK` to `GND`, as indicated in e.g. https://www.makershop.de/wp-content/uploads/2018/09/ccs811-air-quality-sensor-1.jpg).

With PSLab and the app still get the values from the previous screenshot. I checked the bytes in `CCS811.getRaw()` and `data.get(0)`, `data.get(1)`, `data.get(2)`, `data.get(3)` all seem to be `0xFD` for some reason.

Logcat: [log.txt](https://github.com/user-attachments/files/16618887/log.txt)

**Comment by AsCress** [comment]
@marcnause Thank you very much for the log files. The sensor now seems to communicate well with the app (the IDs are read correctly and there are no errors in the logs shared by you). However, I see that the raw values read are still wrong. This possibly could be do to a wrong configuration of the sensor which I have now fixed in this PR. Could you please once again test with the sensor (with the `WAK` pin connected to the `GND` of the PSLAB), and share me the results that you get along with the log files ?

**Comment by marcnause** [comment]
It's working! 🥳

First screenshot shows the data of the sensor without me doing anything. The second screenshot shows the output of the sensor when I breath on it. The values are pretty much identical to the ones I get when using the sensor with an Arduino.

**Review by marcnause — APPROVED** [review]
@AsCress Do you still have anything to add to this PR or should I test anything additional or is the PR ready to be merged?

**Comment by AsCress** [comment]
@marcnause Great news! 😂 Thank you very much for testing ! I think this is now ready to be merged.

**Pull request merged**
