### PR TITLE
feat: Added SensorGraphViewActivity to visualize and export data in CSV format

### LINKED ISSUE #1346: no activity to visualize stored recorded data in realm for each measurement
**Actual Behaviour**

the data recorded for each measurement is being saved into realm database but cannot be viewed

**Expected Behaviour**

There should be activity to visualize the data in form of graph and show the location of recording on map.

**Steps to reproduce it**

Create SensorGraphViewActivity

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by Avjeet**
Fixes #1346 
Note: This pr should only be merged after PR #1323

**Changes**: 

Added SensorGraphViewActivity including features:
   - Show graph of recorded data,  time and date of recording and Map showing the location
   - menu item to simulate the graph and to save the data into the CSV file.
 
**Screenshot/s for the changes**: 
UI of Activity

CSV file saved[Updated]
image

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 
[graph.zip](https://github.com/fossasia/pslab-android/files/2280430/graph.zip)

### CODE REVIEW

**Comment by mariobehling** [comment]
Thanks. Please change:
* date to 09 Aug 2018
* add column with exact time of start of recording
* add column with exact time of end of recording
* add Timezone
* add Android device information columns e.g. name of device, brand/version of device, Android version

**Comment by Avjeet** [comment]
@mariobehling @cweitat Added the info in CSV file.

**Comment by cweitat** [comment]
@Avjeet hi, what Mario meant was to add a column name "Start Time" and "End Time" with the exact time as data, not "exact time of end of recording" as column name. Date is not changed. And Timezone, without capital Z

**Comment by Avjeet** [comment]
@cweitat I have made all the changes see the screenshot please merge PR #1305 so that I generate apk with updated icons.

**Comment by cweitat** [comment]
@Avjeet fix codacy thanks

**Comment by Avjeet** [comment]
@cweitat fixed codacy

**Pull request merged**
