### PR TITLE
fix: deg text to symbol.

### LINKED ISSUE #1967: Add degree symbol to wavegenerator
**Actual Behaviour**

Current UI has `deg` to indicate degrees

**Expected Behaviour**

Use correct symbol instead

**Steps to reproduce it**

Check out Wave generator UI

**LogCat for the issue**

> Not available

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

Beginner issue

### PR DESCRIPTION
**Pull request by XDivergent**
Fixes #1967 

**Changes**: [deg was written as text changed to its symbol (\u00b0) ]

**Screenshot/s for the changes**: 
Screenshot_1567363396

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [ ] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [ ] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 
[app-fdroid-debug.apk.zip](https://github.com/fossasia/pslab-android/files/3563800/app-fdroid-debug.apk.zip)

### CODE REVIEW

**Comment by neel1998** [comment]
@XDivergent check the coach. It is solvable

**Comment by neel1998** [comment]
@XDivergent follow the naming convention for the PR title. [Tag]: <title>
In your case it should be 
fix: deg test to symbol.

**Comment by XDivergent** [comment]
> @XDivergent thanks for the PR. check the codacy. It is solvable

Can you help in solving this? I am new to these processes.
I am not understanding why it is showing switch does not contain a break. There is a break.

**Comment by neel1998** [comment]
> > @XDivergent thanks for the PR. check the codacy. It is solvable
> 
> Can you help in solving this? I am new to these processes.
> I am not understanding why it is showing switch does not contain a break. There is a break.

Yes I just saw . I don't know why codacy is giving this error. !!. I think this PR can be merged. @CloudyPadmal @cweitat please check

**Pull request merged**
