### PR TITLE
Partially fixes #251 : Main Control UI

### LINKED ISSUE #251: UI for Control is buggy
**Actual Behaviour**

Non-Uniform UI for Control Main

**Expected Behaviour**

Should be uniform for all screens.

**Steps to reproduce it**

Open Control Main

**LogCat for the issue**

NA

**Screenshots of the issue**

screenshot_2017-06-29-22-46-44-474_org fossasia pslab

screenshot_2017-06-29-22-46-58-506_org fossasia pslab

**Would you like to work on the issue?**

@asitava1998 @CloudyPadmal I think you guys should re-think about your approach to make UI for Control. No need to put everything in same line. You can put everything beautifully in Card-Type View with proper padding of individual elements. Like in arbitrary wavefrom generator in advance control there is no way to set frequency of only W1.

### PR DESCRIPTION
**Pull request by CloudyPadmal**
Fixes issue #251 partially

Changes: 
- Added xml file for xhdpi screen support

Screenshots for the change: 

| HDPI | XHDPI |
| ------- | ------- |
| hdpiimage | xhdpi |

APK for testing:
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1115135/app-debug.apk.zip)

### CODE REVIEW

**Comment by viveksb007** [comment]
@CloudyPadmal I tested the apk, UI for Control is okay now.
If we could improve **Arbitrary waveform generator** of **Advanced Control** in this PR. That would be great. Because Square isn't readable in spinner. Like if we remove that frequency range and apply that as constraint input on EditText. That would give enough space for Inc/Dec widget and Spinner. What do you think?

**Comment by CloudyPadmal** [comment]
Thanks a lot for the review :)  That's a great thought Vivek! I will look in to the Advanced  section and fix the ui issue there soon and send a commit to this branch! :+1:

**Comment by CloudyPadmal** [comment]
Hello @viveksb007 ! I've edited the current UI `Advanced` section as follows

| HDPI | XHDPI |
| ------- | -------- |
| hdpi | xhdpi |

Updated APK for testing! [app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1117284/app-debug.apk.zip)

**Comment by viveksb007** [comment]
@CloudyPadmal I tested the apk. Its okay but background of titles like ```Arbitrary Wave Generator``` looks a bit odd. It was okay before with white background and with default gravity.
Rest we can wait for other devs opinion.

**Comment by asitava1998** [comment]
@CloudyPadmal  I tested the apk and it's good to go with for this PR.
We can keep always keep coming up with better designs in the future.

**Comment by CloudyPadmal** [comment]
Hey guys! Thanks alot for the reviews! @viveksb007 in 3rd row in `Arbitrary Waveform Generator`, should I add a spinner for sine and square waves?

**Comment by viveksb007** [comment]
@CloudyPadmal I don't know about its requirement, if it would contribute in configuring the device then its okay.
@asitava1998 would tell that better.
And I think we can merge this one an continue with improvements in later PRs.

**Comment by asitava1998** [comment]
@CloudyPadmal  The phase is meant for `setSqrs` method. So, we won't require any spinner for phase. 
Even I feel, this PR is ready to be merged.

**Comment by CloudyPadmal** [comment]
Thanks a lot guys!!!

**Pull request merged**
