### PR TITLE
Fix #1662 location coordinates issue solved

### LINKED ISSUE #1662: No Location data stored in CSV even though "include location data" option is checked
**Actual Behaviour**

Even if user has selected to add location data in .csv logs, the latitude and longitude columns have zero values in generated csv

**Expected Behaviour**
The current values of latitude and longitude should be included in csv when "include location data" option is checked.

**Steps to reproduce it**

Go to any instruments. (eg. Lux meter) select "include location data" option in configuration menu. Record some data. Check the generated .csv file

**Would you like to work on the issue?**
yes

### PR DESCRIPTION
**Pull request by neel1998**
Fixes #1662 

**Changes**: removed `locationReady` boolean from `GPSLogger` class because it was never set to true because `onLocationChanged` callback is not called always

**Screenshot/s for the changes**:
Screenshot_20190406-103724

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [ ] I have requested reviews from other members

### CODE REVIEW

**Comment by neel1998** [comment]
@CloudyPadmal  kindly review

**Comment by Smit2010** [comment]
@neel1998 Shouldn't the latitude and longitude indicate a direction? For eg. 17.43734112 N

**Comment by neel1998** [comment]
@Smit2010  i am not sure whether we need this or not. @CloudyPadmal  can you please look into it

**Comment by neel1998** [comment]
@cweitat  can you please review this

**Comment by neel1998** [comment]
@abhinavraj23  kindly review

**Comment by neel1998** [comment]
@CloudyPadmal kindly check the attached apk.
[location.zip](https://github.com/fossasia/pslab-android/files/3169800/location.zip)

**Pull request merged**
