### PR TITLE
Fixes #536: Distance Measurement experiment

### LINKED ISSUE #536: Implement Distance Measurement experiment
**Actual Behaviour**

Experiment related to distance measurement using sonar sensors hasn't been implemented

**Expected Behaviour**

The experiment needs to be implemented in saved experiment

**Steps to reproduce it**

1. Open app
2. Go to `Saved Experiments`
3. Select `School Level` experiments
4. Open `Distance Measurement` experiment

**LogCat for the issue**

> Not available

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by CloudyPadmal**
Fixes issue #536 

Changes: 
- Implemented distance measurement experiment

Screenshots for the change: 
distance

APK for testing:
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1234659/app-debug.apk.zip)

### CODE REVIEW

**Comment by viveksb007** [comment]
@CloudyPadmal It is based on ultrasonic sensor. Where are you checking if sensor is connected and does user know how it is to be connected?

**Comment by CloudyPadmal** [comment]
Hi @viveksb007 ! Yes it uses HCSR04/06 sensor and the connectivity is illustrated in the `Experiment Doc` tab. I referred this [file](https://github.com/fossasia/pslab-desktop-apps/blob/development/psl_res/GUI/Z_SCHOOL_LEVEL/A_voltage_fundamentals/Z_DISTANCE.py) in the implementation. Is there a way to check if the sensor is connected or not? I'm not sure about a method!

**Comment by jithinbp** [comment]
Hey, It's not an I2C sensor, so you can't make an absolute check if it is connected or not.
You could try checking the state of ID1; it should be low if no trigger pulse was provided via SQR1.
You could also try to get a reading; There should be some sort of input pulse received ( even a timeout pulse is acceptable because the sensor may be pointed at an open space ) .

Working principle of the sensor:
+ send a short trigger pulse, and measure the width of the output pulse from the sensor. The pulse goes high when the sound wave is sent out, and comes back to low when a reflected wave is received/timeout occurs.  distance = speed of sound * time taken/2

**Comment by CloudyPadmal** [comment]
@jithinbp That's a great idea! :100: Thank you ! :smiley: I'll add a check to that! :+1:

**Comment by viveksb007** [comment]
@CloudyPadmal Please resolve merge conflicts due to transition to `switch` from `if`.

**Comment by CloudyPadmal** [comment]
Hi @viveksb007 ! Resolved them! :)

**Comment by CloudyPadmal** [comment]
Oops! Yes @viveksb007 ! They were deleted in the merge conflict resolution! Now I've added them again! :)

**Pull request merged**
