### PR TITLE
 action bar in About Us activity

### PR DESCRIPTION
**Pull request by NamanRawat1**
Fixes issue #630 

Updated Apk-
[app-debug.zip](https://github.com/fossasia/pslab-android/files/1345230/app-debug.zip)

Screenshots for the change: 
screenshot_2017-09-28-22-13-49-079_org fossasia pslab

### CODE REVIEW

**Comment by viveksb007** [comment]
@NamanRawat1 we need a arrow for user to get back to `MainActivity`.

**Comment by NamanRawat1** [comment]
Done with arrow thing

**Comment by NamanRawat1** [comment]
screenshot_2017-09-29-10-40-35-555_org fossasia pslab

**Comment by CloudyPadmal** [comment]
Hi @NamanRawat1 ! Why is the heading font color has turned to black?

**Comment by NamanRawat1** [comment]
@CloudyPadmal  fix the color and send updated apk above.
screenshot_2017-09-29-18-15-33-799_org fossasia pslab 2

**Comment by viveksb007** [comment]
@NamanRawat1 colour of arrow and title should be same.

**Comment by NamanRawat1** [comment]
screenshot_2017-09-30-22-13-17-840_org fossasia pslab

updated apk-
[about us.zip](https://github.com/fossasia/pslab-android/files/1346594/about.us.zip)

**Comment by NamanRawat1** [comment]
Is it fine now? @CloudyPadmal @viveksb007

**Pull request merged**
