### PR TITLE
fixes #624 update app screenshots in readme

### LINKED ISSUE #624: update app screenshots in the readme
**Actual Behaviour**

currently app screenshots in readme are old.

**Expected Behaviour**

App screenshots in readme should be updated.

**Steps to reproduce it**

NA

**LogCat for the issue**

NA

**Screenshots of the issue**

NA

### PR DESCRIPTION
**Pull request by nikit19**
Fixes issue #624 

Changes: Add updated screenshots

### CODE REVIEW

**Comment by asitava1998** [comment]
@nikit19  The Travis CI build has failed.  Please look into it. 
Two of the screenshots named `screenshot_1.png` and `screenshot_multilevel_experimentlist.png` are essentially the same.  For the screenshot named `screenshot_initialization.png`, the previous one was better as it showed the initialization process. Rest are good. 👍

**Comment by nikit19** [comment]
@asitava1998  size of my screenshots and the ones that were there earlier are different. So if I don't change all of them , earlier ones appear smaller. So what should I do ?

**Comment by asitava1998** [comment]
@nikit19  Share a screenshot in the comments here, of the README file with your new set of images in it. If the file looks okay, there is no problem in accepting your images.

Please get the build of Travis to pass. This is important

**Comment by nikit19** [comment]
screenshot from 2017-09-14 17-41-08
screenshot from 2017-09-14 17-41-24

**Comment by nikit19** [comment]
@asitava1998 can you give me a little hint what should I do to fix it ?
I see this line in the report
org.fossasia.pslab.MainActivityTest > checkingAllFragments[test(AVD) - 5.1.1] FAILED

**Comment by viveksb007** [comment]
@nikit19 I have restarted the build, it would fix as there was no change in the code.
About replacing initialisation screenshot, if previous ones are of smaller size, then you can scale down new screenshots to match the dimensions of previous screenshots.

**Comment by nikit19** [comment]
p1
p2
@viveksb007 is it fine now?

**Comment by asitava1998** [comment]
@nikit19  The README file looks fine 👍

**Pull request merged**
