### PR TITLE
Fixes #738 : Animation timing resolved

### LINKED ISSUE #738: Animation not working properly
**Actual Behaviour**

When going from one page to another, the texts overlap on each other due to bad timings of animation.

**Expected Behaviour**

First, the text of current page should fade and then the text of new page should come up.

**Steps to reproduce it**

1. Go to applications from side menu

2. Switch to Saved Experiments tab from the side menu

**LogCat for the issue**

No LogCat

**Screenshots of the issue**

screenshot_20180227-131047 1

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by ThisIsNSH**
Fixes issue #738  

Changes: New animation files added to prevent animation overlapping while activity transition.

Screenshots for the change: None

### CODE REVIEW

**Comment by CloudyPadmal** [comment]
Looks good @ThisIsNSH ! Can you upload the APK file to test this out?

**Comment by ThisIsNSH** [comment]
[apk.zip](https://github.com/fossasia/pslab-android/files/1783325/apk.zip)
Hey @CloudyPadmal please check the apk.

**Comment by ThisIsNSH** [comment]
@viveksb007 @asitava1998 @akarshan96 please review

**Comment by akarshan96** [comment]
@ThisIsNSH I have tested the apk and the changes work fine. Can you please squash the commits?

**Comment by ThisIsNSH** [comment]
@akarshan96 I have squashed the commits please review.

**Pull request merged**
