### PR TITLE
WIP #1719 layout to control servo of robotic arm created

### LINKED ISSUE #1719: Servo motor control option
**Actual Behaviour**

PSLab device can be used to control a robot arm set with 4 servo motors. Currently it is done by writing a Python script and there is no option in PSLab Android app to do so. This feature is requested by Marco

**Expected Behaviour**

Implement a tool giving an option to control servo motors using Android app.

**Steps to reproduce it**

> Not available

**LogCat for the issue**

> Not available

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

Add this to GSoC timeline. Developer who takes over this issue needs to understand how servo motors work and how to use PWM pins of PSLab device to control them.

### PR DESCRIPTION
**Pull request by neel1998**
Fixes #1719 

**Changes**: Created a layout to control servo

**Screenshot/s for the changes**: 

robotic_arm_psl

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**:
[robotic_arm.zip](https://github.com/fossasia/pslab-android/files/3192477/robotic_arm.zip)

@CloudyPadmal @mariobehling @adityastic kindly have a look at this. I thought it would be much easier to control 4 servo in landscape mode , that's why implemented this layout. As @mariobehling  suggested i have added circular view to control angle of servo

### CODE REVIEW

**Comment by mariobehling** [comment]
This is illogical. Please refer to the picture below. Some servos can move 180 degress, some 360 degrees. We can go into detail here later. But, please implement circles.

circle-41073_960_720

**Comment by mariobehling** [comment]
46331197-angle-45-360-degrees-circle-icons-geometry-math-signs-symbols-full-complete-rotation-arrow-flat-icon

**Comment by neel1998** [comment]
@mariobehling  i was thinking we had servo that rotates 0-180 degress that's why i made this design . I will change it and make a new layout today :)

**Comment by neel1998** [comment]
@mariobehling  @CloudyPadmal  @adityastic kindly have a look at this new layout
Screenshot_20190518-181620

**Comment by neel1998** [comment]
@mariobehling @CloudyPadmal  kindly have a look the new layout in previous comments. Thanks

**Comment by mariobehling** [comment]
Is it possible to enter the numbers manually as well by tapping on the number field? Please ensure this is working too.

**Comment by neel1998** [comment]
@mariobehling right now I haven't added that. I was waiting for you to confirm the basic layout, after that i will add additional features

**Comment by mariobehling** [comment]
Thanks. I think the basic layout is good. I see that you introduce a new color in the app. I don't remember that any other instrument uses blue. But, we can work on details later. Please implement the direct number entering functionality.

After that please continue working on the instrument. Details are here: https://github.com/fossasia/pslab-android/issues/1734

**Comment by cweitat** [comment]
You can refer to the knobs used at Power Source instrument

**Comment by neel1998** [comment]
@mariobehling  @CloudyPadmal  @cweitat  I have created a new Layout for the servo controller. I have made the layout in a way that user won't need to scroll make it convenient to control the servos . Also i have made the parameters of the layouts dynamic so it would adjust based on device screen size. The drag and drop of the servo is working fine as seen in gif. I will make  the timeline more precise in another PR. kindly have a look




(separation in first 2 timeline is not properly visible in gif i don't know why, kindly refer to the screenshot)

[robotic_arm_new.zip](https://github.com/fossasia/pslab-android/files/3207870/robotic_arm_new.zip)

**Comment by neel1998** [comment]
@mariobehling since i have changed the whole layout, i think it would be better not to split this PR. I will make separate PRs for now onward changes

**Comment by neel1998** [comment]
@mariobehling  regarding the editable degree values, i am still working on it, because keyboard in the landscape mode is not responding very well.But i will figure out it really soon.

**Comment by mariobehling** [comment]
Thank you. Let's get other parts done in follow up PRs.

**Pull request merged**
