### PR TITLE
refactor: update screenshots

### LINKED ISSUE #1325: Update readme with latest screenshots
**Actual Behaviour**

Current read me file has outdated UI screens

**Expected Behaviour**

They need to be updated with latest UI

**Steps to reproduce it**

Check Readme file for screenshots

**LogCat for the issue**

> Not available

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by CloudyPadmal**
Fixes #1325 

**Changes**:
- Updated readme with latest screens

**Screenshot/s for the changes**: 
updatescreens

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [X] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [X] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [X] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [X] My code does not contain any extra lines or extra spaces
- [X] I have requested reviews from other members

**APK for testing**: 
> Not available

### CODE REVIEW

**Comment by harsh-2711** [comment]
@CloudyPadmal Please update the Lux Meter, Accelerometer and Compass Instruments screenshots too.

**Comment by CloudyPadmal** [comment]
@harsh-2711 these readme screenshots are to show just a preview. No need to show every single screen.

**Comment by harsh-2711** [comment]
@CloudyPadmal But I think we can update Lux Meter screenshot as the one shown in the current screenshot isn't correct as the data lines aren't smooth and also it doesn't contain the new functionality of menu in the toolbar. Rest looks good to me.

**Comment by CloudyPadmal** [comment]
Ahh yes the menu bar is missing. Shall we put the one in your PR as the current one has a floppy disk icon?

**Comment by CloudyPadmal** [comment]
Screenshot of Luxmeter was updated

**Pull request merged**
