### PR TITLE
Added Language To PSLab Android App

### LINKED ISSUE #2014: Languages support
### **Would you like to work on the issue?**
**yes**

### PR DESCRIPTION
**Pull request by aryanguls**
Fixes #2014 

**Changes**: For the purpose of this merge request I have decided to add arabic as another language to the PSLab android app to further improve the selection of languages available to users.

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [ ] I have requested reviews from other members

**APK for testing**: [Compress the `app-debug.apk` file into a `<feature>.rar` or `<feature>.zip` file and upload it here]

### CODE REVIEW

**Comment by aryanguls** [comment]
@mariobehling @hpdang Mentors please review and merge as and when possible.

**Comment by aryanguls** [comment]
@nikit19 Sir please also review as and when possible.

**Comment by CloudyPadmal** [comment]
Hello @aryanguls , are you a native speaker in both the languages submitted? Please provide an APK file to test the features and also remember to post some screenshots

**Comment by aryanguls** [comment]
No sir @CloudyPadmal I myself am not fluent but owing to the fact that google translate can sometimes be wrong I asked my linguistics teacher at school to check the changes I had made and as she is fluent in these languages. I thus chose Polish and Arabic as languages to be added. Thus the changes I have made have been verified.

**Comment by aryanguls** [comment]
@CloudyPadmal The APK File is : 
[app-fdroid-debug.zip](https://github.com/fossasia/pslab-android/files/4077760/app-fdroid-debug.zip)
Screenshot (461)
Sir this a screenshot of the app working in arabic.

**Comment by aryanguls** [comment]
@CloudyPadmal Sir please review and accept merge request as and when possible.

**Comment by aryanguls** [comment]
@CloudyPadmal @mariobehling @hpdang @nikit19 Mentors please review.

**Comment by Sid911** [comment]
I am not sure but these language should be check by someone who knows it before making into the repo.. I am pretty sure there might be someone in community who can verify this.. @aryanguls you could find someone from that region and ask them to verify it on this pr 😇

**Comment by aryanguls** [comment]
I have checked with my linguistics teacher who is fluent in Thai, Polish and Russian but as Russian is already added so i asked her to help me with adding Thai and polish. So she made the required changes and then I added it to the file.
She is a certified source.

**Comment by aryanguls** [comment]
No I myself am not fluent but owing to the fact that google translate can sometimes be wrong I asked my linguistics teacher at school to check the changes I had made and as she is fluent in these languages I thus chose Polish and Arabic as languages to be added. Thus the changes I have made have been verified.

**Comment by CloudyPadmal** [comment]
Hello @aryanguls , what @Sid911 is saying is we need to see some proof in this PR itself saying all the content are accurate.

**Comment by aryanguls** [comment]
@CloudyPadmal As I have already gotten it checked once and due to shortage of time could you get it reviewed as soon as possible as the deadline for submitting tasks is coming soon and then I wont have time to submit this.

**Comment by aryanguls** [comment]
@CloudyPadmal Sir I have rechecked the language concerns by another external source and he too has said that the doc seems fine. Could you please merge the request as soon as possible as the deadline for google code-in is fast approaching.

**Comment by cweitat** [comment]
@aryanguls ask the external source to leave a comment here

**Pull request closed without merging**
