### PR TITLE
Thermometer logo improved and Gyroscope svg

### PR DESCRIPTION
**Pull request by ho-dor**
Fixes #First steps for issues #1770 

**Changes**: Thermometer logo improved 

**Screenshot/s for the changes**:
Screenshot_20190610-004741_PSLab

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [ ] I have requested reviews from other members

**APK for testing**: 
[svg.zip](https://github.com/fossasia/pslab-android/files/3269857/svg.zip)

### CODE REVIEW

**Comment by ho-dor** [comment]
I have created the logo for thermometer thus far . I want to know what can be the design for robotic arm and gyroscope . Any suggestions ? @neel1998 @adityastic @CloudyPadmal

**Comment by neel1998** [comment]
I think current gyroscope logo looks fine . Just convert it to svg

**Comment by CloudyPadmal** [comment]
@ho-dor use templates from this repo https://github.com/fossasia/pslab-artwork. These circular svgs need to have extending lines to match with the other lines. Have a look at previous icons you'll get the idea..

**Comment by ho-dor** [comment]
I have added the gyroscope svg as well and improved the thermometer svg . For robotic arm , it will take time as it is taking a lot of time to create the write path datas for these . So , I will open a new issue and PR for that as and when the design will be final and the path data will be created , hence , I have removed the WIP tag

**Pull request merged**
