### PR TITLE
feat:Adding a guide message home screen

### LINKED ISSUE #1577: A start message for guiding new users
**Actual Behaviour**

No message appears on home screen when the user starts the application.

**Expected Behaviour**
A start message should appear to guide new users.

**Would you like to work on this issue**
Yes

### PR DESCRIPTION
**Pull request by riyasingh1004**
Fixes #1577

**Screenshot/s for the changes**: 

screenshot_2019-03-06-19-27-19-78 1

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [ ] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 

[MainActivity.zip](https://github.com/fossasia/pslab-android/files/2937454/MainActivity.zip)

### CODE REVIEW

**Comment by riyasingh1004** [comment]
@cweitat kindly review, I have implemented the changes.

**Comment by neel1998** [comment]
@riyasingh1004  again, This toast seems unnecessary.

**Comment by riyasingh1004** [comment]
Its just a suggestion to make the app more interactive @neel1998

**Comment by neel1998** [comment]
@riyasingh1004  but don't you think it obvious that user would tap on device to do anything. What else user is gonna do!!. Information provided by this toast is completely intuitive and doesn't need to be displayed

**Comment by riyasingh1004** [comment]
Ya maybe you are right .I will try to add some other guide message which is not so obvious.

**Comment by neel1998** [comment]
@riyasingh1004  why do we need a guide message in first place. At least the launching activity of an app doesn't require a guide message

**Comment by cweitat** [comment]
Also, i agree with what @neel1998 said as well

**Comment by harsh-2711** [comment]
@riyasingh1004 I don't think this PR is needed in the current state of the app so I am closing this PR.

**Pull request closed without merging**
