### PR TITLE
feat:Creating a toast message for home screen

### LINKED ISSUE #1577: A start message for guiding new users
**Actual Behaviour**

No message appears on home screen when the user starts the application.

**Expected Behaviour**
A start message should appear to guide new users.

**Would you like to work on this issue**
Yes

### PR DESCRIPTION
**Pull request by riyasingh1004**
Fixes #1577

**Screenshot/s for the changes**
screenshot_2019-03-04-15-41-24-90 1

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for Testing**
[msg_testing.zip](https://github.com/fossasia/pslab-android/files/2926283/msg_testing.zip)

### CODE REVIEW

**Comment by riyasingh1004** [comment]
@CloudyPadmal please review

**Comment by riyasingh1004** [comment]
@cweitat due to some errors I deleted the forked repository in through which I made the pull request.
So can I make a new pull request with the changes included.

**Comment by cweitat** [comment]
sure. you can close this issue and do a new PR

**Comment by riyasingh1004** [comment]
Okay, thank you

**Comment by riyasingh1004** [comment]
I wanted to ask do I need to commit changes to string.xml file in the pull request.

**Comment by riyasingh1004** [comment]
Or just using the string resources in activity file is enough. @cweitat

**Comment by abhinavraj23** [comment]
@riyasingh1004 yes you definitely have to commit changes to string.xml file in the pull request otherwise it would give an error when it will be merged

**Pull request closed without merging**
