### PR TITLE
ch1 and ch2 simultaneous output working fine in oscilloscope

### LINKED ISSUE #1757: Oscilloscope gives weird output on displaying 2 channels simultaneously
**Actual Behaviour**
The graph gets distorted on enabling 2 channels in oscilloscope

**Expected Behaviour**
There should be desired plot for both the channels

**Steps to reproduce it**
Generate 2 waves in wave generator and view them in oscillator simultaneously

**Screenshots of the issue**
Screenshot_20190530-175707
Screenshot_20190530-180253

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by neel1998**
Fixes #1757 

**Changes**: out put of ch1 and ch2 simultaneously doesn't give weird output

**Screenshot/s for the changes**:

before:
Screenshot_20190530-175707

after: 

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**:

[osciloscope_2.zip](https://github.com/fossasia/pslab-android/files/3293895/osciloscope_2.zip)

### CODE REVIEW

**Comment by CloudyPadmal** [comment]
Looks pretty cool @neel1998

**Comment by CloudyPadmal** [comment]
Still wip? Seems complete :thinking:

**Comment by neel1998** [comment]
> Still wip? Seems complete

Yes . I will update the title. It is working fine. There is some changes required to have ch1 and built in mic together. but i will make separate PR for that, since there already is one separate issue regarding that. This PR can be merged

**Comment by CloudyPadmal** [comment]
@AakashMallik can you too test the apk and submit a review?

**Comment by cweitat** [comment]
Did you try to increase the timebase?

**Comment by neel1998** [comment]
@cweitat  thanks for pointing out. i think the app crashes when we try to decrease the time base after we have increased once. I am on it

**Comment by cweitat** [comment]
If you can fix the signals, do look at #1518 , #1389 and #874, you can solve 4 similar issues.

**Comment by neel1998** [comment]
@cweitat  yes. I will make a separate PR for #874 after the current fix, simultaneous signals are working fine, i just need to add proper conditions and AsyncTasks for audio channel. I will do that . Regarding #1389 i haven't been able to get distorted signals for many tries i made after i made changes in this PR, it would be great if you can check once your self. thanks

**Comment by cweitat** [comment]
For #1389, I think we need get someone with access to oscilloscope to test. @CloudyPadmal can you do that or you know anyone?

For #1518, please update your issue description if the updates have been pushed.

**Comment by neel1998** [comment]
@cweitat  i fixed the smal timebase bug. For now waves generated through wave generator are working fine on higher time base as well. I have updated the apk in the PR. please chek. Regarding the realted issues, i will try to fix them once this once gets merged

**Comment by neel1998** [comment]
@cweitat  i think this can be merged

**Comment by cweitat** [comment]
Codacy

**Comment by neel1998** [comment]
@cweitat  @CloudyPadmal  please merge this

**Pull request merged**
