### PR TITLE
Experiment Setup for Piezo Buzzer and Resistance Measurement

### PR DESCRIPTION
**Pull request by harsh-2711**
Changes: Piezo Buzzer Experiment Setup and Resistance Measurement Experiment Setup added. Also schematic of Piezo Buzzer in .svg format added.

### CODE REVIEW

**Comment by harsh-2711** [comment]
@CloudyPadmal  Please review this.

**Comment by harsh-2711** [comment]
@viveksb007  @asitava1998 @akarshan96  Please review my PR

**Comment by akarshan96** [comment]
The PR looks good 👍. Can you give apk for testing?

**Comment by CloudyPadmal** [comment]
@harsh-2711 can you upload the APK so we can merge this PR if it's working?

**Comment by harsh-2711** [comment]
Here is the apk
[app-debug.zip](https://github.com/fossasia/pslab-android/files/1802161/app-debug.zip)

**Comment by harsh-2711** [comment]
@CloudyPadmal  @akarshan96  I have provided the apk file... Please review it

**Comment by akarshan96** [comment]
Aren't PR #746 and this PR solving the same issue?

**Comment by harsh-2711** [comment]
PR #746 was created by mistake and so this is my final PR.. I have mentioned about this in our channel

**Comment by akarshan96** [comment]
@harsh-2711 okay, let me close PR #746.

**Comment by harsh-2711** [comment]
@viveksb007  @asitava1998  Please review my PR

**Pull request merged**
