### PR TITLE
Fixes Issues #712 #722 #727

### PR DESCRIPTION
**Pull request by Vipul999ujawane**
Fixes issue #712 #722 #727 
Changes: [Add here what changes were made in this issue and if possible provide links.] 
1.Added Figures for :  Clipper, Clamper, Phase Shift Oscillator, Series Clipper, Series Clamper, Wein Bridge Oscillator
2. Fixed Small Image Issue in BJT CB Characteristics Experiment
3. Created MD Files for Op-AMP Inverting and Non-Inverting Experiments

Screenshots for the change: 
screenshot_20180227-201355
screenshot_20180227-201339
screenshot_20180227-201333

APK : 
[app-debug.zip](https://github.com/fossasia/pslab-android/files/1764200/app-debug.zip)

### CODE REVIEW

**Comment by CloudyPadmal** [comment]
Can you give it a try to give one PR per one issue? Also can you double check the phase shift oscillator? And also put values for the passive components. You can simulate the circuit and calculate the best values for those resistors and caps! :)

**Comment by Vipul999ujawane** [comment]
screenshot_20180228-172409
 Done 
I tried squashing the commits, but I am not able to squash the merged PR commit. Sorry for that

**Comment by CloudyPadmal** [comment]
Could you please again double check the schematics for values? Also the annotations are normally like `C1, C2`. Could you check them again?

**Comment by Vipul999ujawane** [comment]
Actually, I created simulations only for the experiments where values will matter like the oscillator, where it needs to be stable. Other places like diode clippers and clampers, any value is practically usable.

**Comment by CloudyPadmal** [comment]
@Vipul999ujawane yes so please add a practical value to those components which is easily available in the market! :+1:

**Pull request merged**
