### PR TITLE
Fixes #549 : PerformExperiments adapter switch cases

### LINKED ISSUE #549: PerformExperimentAdapter contains lot of if clauses
**Actual Behaviour**

`PerformExperimentAdapter` contains lot of if clauses inside `public Fragment getItem(int position)` method to configure the relevant fragment. As in this case every if clause is evaluated if the last fragment is the one to be processed, it is not a good programming practice to use if clauses like that

**Expected Behaviour**

These if clauses should be replaced with switch case statements to improve performance.

**Steps to reproduce it**

Refer the [java](https://github.com/fossasia/pslab-android/blob/development/app/src/main/java/org/fossasia/pslab/adapters/PerformExperimentAdapter.java#L49) file lines

**LogCat for the issue**

> Not available

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by CloudyPadmal**
Fixes issue #549 

Changes: 
- Added switch cases to if statements
- Since values needed to be constant, couldn't use string resources

APK for testing:
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1236842/app-debug.apk.zip)

### CODE REVIEW

**Comment by viveksb007** [comment]
@CloudyPadmal I don't think this improves much of performance and we are losing flexibility too. Any change in experiment title won't be reflected here. 
What do you think?

**Comment by CloudyPadmal** [comment]
Hi @viveksb007 ! It will improve performance as there are a lot of saved experiments. Please [refer](https://stackoverflow.com/questions/4334339/disadvantages-to-using-lots-of-if-statements) to this article. There will be a lag when there are many experiments are implemented and user clicked on one of the last experiments if `if` statements are used.

**Comment by viveksb007** [comment]
From what I understand. A lot of comparisons are made in case below, and all conditions are mutually exclusive
```
if(condition)
// do something
if(condition)
// do  something
if(condition)
// do  something
```
But in our case its,
```
if(condition)
return
if(condition)
return
if(condition)
return
```
So performance is same. Same comparisons would be made in our current implementation and the switch case you propose.

**Comment by CloudyPadmal** [comment]
Switch case uses hash tables which makes it faster in accessing elements where mutually exclusive if statements are dependable on what item user clicks. [Reference](https://stackoverflow.com/questions/22110707/how-is-string-in-switch-statement-more-efficient-than-corresponding-if-else-stat)

**Comment by viveksb007** [comment]
@CloudyPadmal Thanks for the reference that cleared the doubt.

**Comment by CloudyPadmal** [comment]
Thanks all for the review! :+1:

**Pull request merged**
