### PR TITLE
feat: csv logging

### LINKED ISSUE #967: Implement data set export feature
**Actual Behaviour**

In many instruments data sets captured can not be saved textually or graphically

**Expected Behaviour**

Captured data points needs to be saved in CSV and TXT format.

**Steps to reproduce it**

> Not applicable

**LogCat for the issue**

> Not applicable

**Screenshots of the issue**

> Not applicable

**Would you like to work on the issue?**

Work will be taken by the development team

### PR DESCRIPTION
**Pull request by CloudyPadmal**
Fixes #967 

**Changes**: 
- Added CSV logging functionality

**Screenshot/s for the changes**: 
> Not a UI change

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [X] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [X] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [X] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [X] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 
[csv.zip](https://github.com/fossasia/pslab-android/files/2160035/csv.zip)

### CODE REVIEW

**Comment by Vikum94** [comment]
Could you please provide the apk :smile:

**Comment by CloudyPadmal** [comment]
Oh I haven't saved the modified PR message body with the screenshot and all. I'll update it soon :+1:

**Comment by CloudyPadmal** [comment]
@Vikum94 @abhinavraj23 @Avjeet @harsh-2711 please review this

**Comment by Vikum94** [comment]
1. App didn't have permission so the folder didn't created. Will it be a good idea to have a toast or permission request to the files.
2. After giving permission the folder was created, but no file was there in the folder.

**Comment by CloudyPadmal** [comment]
@Vikum94 mine there wasn't any permission issue. Read/Write permission was already there in the manifest. I'll check that.
Have you tried clicking the menu button to start recording data?

**Comment by harsh-2711** [comment]
@CloudyPadmal There are few points of suggestion:
1. Please change the folder name from PSLab_Data to PSLab Data as all apps on my phone uses this type of convention
2. Also please increase the time interval in taking data as logging data for only 3 seconds produces 12390 entries in the sheet.
3. Please add some headers for each column in the csv file as it is not possible for a user to understand which column shows what data

**Comment by CloudyPadmal** [comment]
@harsh-2711 
1. In my device, there are no spaces between folder names. Also as a Linux person I don't encourage using spaces for file names.

| Screen 1 | Screen 2 |
| ---- | ---- |
| screenshot_2018-07-03-20-37-26 | screenshot_2018-07-03-20-37-33 |

2. I cannot modify data set captured in each instrument. It's beyond scope of this PR. In this implementation it is recording all the data displayed to user. In case you didn't notice, I have opened an issue #1170 as in Luxmeter, there are too many redundant data points and assigned it to @Vikum94. Once it is fixed, there will be a lot lesser data set.

3. Headers is a good idea! Let me make a fix for that! :+1:

**Comment by Avjeet** [comment]
@CloudyPadmal I have recorded for only one time then instead of one, two csv files are getting generated in which one is having size of 0B. Could you plz look into this.
image

**Comment by CloudyPadmal** [comment]
Ahh yes @Avjeet ! I was creating a file for the next batch. Let me change that one. That needs to be removed! Now it's fixed!

**Pull request merged**
