### PR TITLE
Add Language to PSLab Android

### LINKED ISSUE #2037: Adding language - Arabic
**Actual Behaviour**
App only has two languages

**Expected Behaviour**
Adding Arabic translation for strings.xml

**Steps to reproduce it**

strings.xml in Arabic

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by aryanguls**
Fixes #2037 and #2014 

**Changes**: For the purpose of the above request I have added an extra language in the form of polish to PSLab android app as there seemed to be a lack of languages.

**Screenshot/s for the changes**:

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [ ] I have requested reviews from other members

@hpdang @mariobehling Mentors please review.

### CODE REVIEW

**Comment by mariobehling** [comment]
Please ask your friends and co-contributors on the chat channel to help review this.

**Comment by pranavkarthik10** [comment]
👍LGTM, do you have any screenshots of it working?

**Comment by aryanguls** [comment]
PSLab_Lang
@pranavkarthik10 Thanks for the review.

**Comment by aryanguls** [comment]
Sorry did not mean to close it. I did it by mistake.

**Pull request merged**
