### PR TITLE
Initialisation and runInitSequence Completed and tested successfully

### PR DESCRIPTION
**Pull request by viveksb007**
Fixes issue #183 #184 

Changes:

- Modified runInitSequence for successful initialisation of device and added a Initialisation status for User.
- Transferred initialisation work on another thread  so UI thread isn't blocked.

Screenshots for the change: 
Some Logs 

screenshot from 2017-06-17 13-02-16

[APK Link](https://drive.google.com/open?id=0B30IF3fyX4Q3X1FEMGxpNEZjaDA) to test.

### CODE REVIEW

**Comment by viveksb007** [comment]
@akarshan96 never happened when I was testing, still its good that it happened. I made some changes adn updated apk link : https://drive.google.com/open?id=0B30IF3fyX4Q3X1FEMGxpNEZjaDA . Could you test again?

**Comment by asitava1998** [comment]
@viveksb007  @akarshan96  I tested it around 10 times and it worked fine . I didn't experience any crash.

**Comment by viveksb007** [comment]
Yeah but, the change I did should be done logically. Its USB bulkTransfer API, which doesn't provide quite flexible read, write methods.
Still you could also check with the new one. If this one is also Okay, then we are good to merge.

**Comment by akarshan96** [comment]
@viveksb007 the new apk works fine 👍

**Comment by viveksb007** [comment]
@akarshan96 I guess you can approve the PR now.
And @asitava1998 @akarshan96 please open issues for implementing functionalities now that calibration and initialisation roadblock is out of way, we can speed up with development and testing.

**Pull request merged**
