### PR TITLE
fix: Solved the issue of file creation on record button click in Lux Meter

### LINKED ISSUE #1341: New CSV file created in Lux Meter on record button press
**Actual Behaviour**

New CSV file is created everytime the record button is pressed.

**Expected Behaviour**

The CSV file should only be created if Export Data is pressed.

**Steps to reproduce it**

Go to Lux Meter -> Press Record and Analyze

**LogCat for the issue**

Not applicable

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by harsh-2711**
Fixes #1341 

**Changes**: Added code to delete the file as soon as the instrument is closed if it isn't exported

**Screenshot/s for the changes**

**Checklist**: [Please tick following check boxes with `[]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2271920/app-debug.zip)

### CODE REVIEW

**Comment by Avjeet** [comment]
@harsh-2711 I have made PRs to moved the export functionality from lux meter activity into the Data Logger Activity so I don't think this PR is needed as data is first to get stored in realm database and then export to CSV if the user wants.

**Comment by harsh-2711** [comment]
@Avjeet You have three linked PRs related to this issue. So, I think it's better to merge this PR so that there won't be any issues in next release.

**Comment by Avjeet** [comment]
@harsh-2711 The PRs are merged now if test them thoroughly and if any issue please create another issue of that and report me.

**Comment by CloudyPadmal** [comment]
@harsh-2711 @Avjeet is this PR now necessary as data handling is done at a database level?

**Comment by Avjeet** [comment]
@CloudyPadmal no this PR is not needed

**Pull request closed without merging**
