### PR TITLE
fix: implement functionality in power source instrument

### LINKED ISSUE #953: Implement PV sources in Power Source Instrument
**Actual Behaviour**

Current Power Source instrument is just boilerplate code.

**Expected Behaviour**

Programmable Voltage Sources need to be implemented and tested.

**Steps to reproduce it**

1. Open app
2. Go to `Power Sources`

**LogCat for the issue**

> Not available

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by CloudyPadmal**
Fixes #953 

Changes: 
- Added controllability of power sources using Android app

TODO:
- Long click on increment decrement buttons to update values repeatedly #996 
- Dialog box to show information #997
- Make changes to instrument tile #998
- Add device connectivity menu buttons #999
- Save user set values throughout the app #1000

Screenshots for the change: 

| Device | Multimeter |
| -------- | -------------- |
| device-2018-06-08-181541 | multimeterresult |

APK for testing: 
[PowerSources.apk.zip](https://github.com/fossasia/pslab-android/files/2084397/PowerSources.apk.zip)

### CODE REVIEW

**Comment by CloudyPadmal** [comment]
Hello @harsh-2711 ! I didn't get what you meant by objects?

**Comment by harsh-2711** [comment]
By saying objects, I mean to say the header, buttons and edit text box. There size can be reduced as they are very big at present.

**Comment by CloudyPadmal** [comment]
@harsh-2711 can you please suggest me a layout with smaller objects with proper use of screen space and usability?

**Comment by harsh-2711** [comment]
Sure. I will provide the layout soon..

**Pull request merged**
