### PR TITLE
fix: Revised schematics

### PR DESCRIPTION
**Pull request by harsh-2711**
Fixes issue #864 

Changes: All the minor changes that are needed as described in the issue are fixed

APK for testing:
[app-debug.zip](https://github.com/fossasia/pslab-android/files/1997479/app-debug.zip)

### CODE REVIEW

**Comment by harsh-2711** [comment]
@CloudyPadmal  Please review

**Comment by harsh-2711** [comment]
@CloudyPadmal  Changes done as requested

**Comment by harsh-2711** [comment]
@CloudyPadmal  @abhinavraj23 @Avjeet Please review

**Comment by CloudyPadmal** [comment]
Yes @Vikum94 that makes sense!

**Comment by mariobehling** [comment]
No longer needed.

**Pull request closed without merging**
