### PR TITLE
feat: Reading built in accelerometer and displaying values

### PR DESCRIPTION
**Pull request by Vikum94**
First steps for issues #993 

**Changes**: 
Reading the built in accelerometer sensor and displaying the values, max and min in the three axes

**Screenshot/s for the changes**: 

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 
[Updated apk](https://github.com/fossasia/pslab-android/files/2124207/accel_built_in.zip) 
[Initial apk](https://github.com/fossasia/pslab-android/files/2095044/builtin_accel_readings.zip)

### CODE REVIEW

**Comment by Vikum94** [comment]
@abhinavraj23 @harsh-2711 @Avjeet Please review. Thanks

**Comment by harsh-2711** [comment]
@Vikum94  The colors used in the small images showing axis is not identical. Also please center align the main text showing constantly changing axis

**Comment by akarshan96** [comment]
@Vikum94 please remove conflicts :)

**Comment by Vikum94** [comment]
Updated apk
[accel_built_in.zip](https://github.com/fossasia/pslab-android/files/2124207/accel_built_in.zip)

**Pull request merged**
