### PR TITLE
Fixes #228 : Resolutions set to required amounts in control UI

### LINKED ISSUE #228: Field values have a higher resolution than required in Control UI
**Actual Behaviour**

The Control UI input boxes has nearly 8 decimal places.

**Expected Behaviour**

The precision for voltages should be set to 3 decimal places & frequency should be set to one decimal place

**Steps to reproduce it**

1. Open App
2. Go to `Applications`
3. Proceed to `Control`
4. Try sliding the sliders to set values to input boxes and observe

**LogCat for the issue**

> Not available

**Screenshots of the issue**

screenshot_2017-06-24-08-00-45

**Would you like to work on the issue?**

Yes!

### PR DESCRIPTION
**Pull request by CloudyPadmal**
Fixes issue #228 

Changes: 
- Added `DecimalFormat` to set required decimal places into input boxes

Screenshots for the change: 
edit

### CODE REVIEW

**Comment by asitava1998** [comment]
@CloudyPadmal I just have a small query, what is the least count of the waveform generator? Does it have decimal places?

**Comment by jithinbp** [comment]
Resolution of the waveform generators (sine) are variable. In the sub 100Hz range, two decimals are available, beyond 4KHz, least count is around 2Hz. Below 5Hz, three decimals are possible.
Which is why the actual set value(returned by the function) must be displayed to the user. 1001Hz might be 1001+/-0.xHz depending on the hardware limitations

**Comment by jithinbp** [comment]
And the same goes for programmable voltage sources, and pwm generators . All digital signals have finite step sizes that must be considered

**Comment by CloudyPadmal** [comment]
Thanks guys! 
@asitava1998 Minimum value is 10 in all three (Wave1, Wave2 and Square) wave generators.
@jithinbp The required resolution is as follows? --->
> 0 - 5 Hz -> XX.XXX
> 5 - 100 Hz -> XX.XX
> 101 - 3.999 kHz -> XXXX
> 4 kHz and above -> XXXX &plusmn; 2

**Comment by jithinbp** [comment]
@CloudyPadmal those were approximate numbers. If you look at how a sine wave is generated from the wavetable, I'm sure some sort of equation regarding the resolution as a function of frequency can be derived. In order to improve the resolution further, I have used two sine tables per wavegen. A long table for frequencies lower than 1100 , and a shorter on for higher frequencies.
However, for all practical purposes I think we can provide one decimal point, and correct the value after the user has set it.

**Comment by asitava1998** [comment]
@CloudyPadmal  Well, as far as I remember, the approximate least count for voltage values is 2.5 mV . So, you need to have 4 places for voltages actually (like 3.0025 V).

**Comment by CloudyPadmal** [comment]
@asitava1998 I can set the pattern as #.#### then right? It will support 4 decimal places then!

**Comment by jithinbp** [comment]
@CloudyPadmal that's not what the sine table plot should look like. I just tried plotting sineTable1 , and here are my results:
psl_sinetable

```python
from pylab import *
x= [256, 252, 249, 246, 243, 240, 237, 234, 230, 227, 224, 221, 218, 215, 212, 209, 206, 203, 200, 196, 193, 190, 187, 184, 181, 178, 175, 172, 169, 166, 164, 161, 158, 155, 152, 149, 146, 143, 141, 138, 135, 132, 130, 127, 124, 121, 119, 116, 114, 111, 108, 106, 103, 101, 98, 96, 93, 91, 89, 86, 84, 82, 79, 77, 75, 73, 70, 68, 66, 64, 62, 60, 58, 56, 54, 52, 50, 48, 47, 45, 43, 41, 40, 38, 36, 35, 33, 32, 30, 29, 27, 26, 25, 23, 22, 21, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 8, 7, 6, 6, 5, 4, 4, 3, 3, 2, 2, 2, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 4, 4, 5, 6, 6, 7, 8, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 21, 22, 23, 25, 26, 27, 29, 30, 32, 33, 35, 36, 38, 40, 41, 43, 45, 47, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 73, 75, 77, 79, 82, 84, 86, 89, 91, 93, 96, 98, 101, 103, 106, 108, 111, 114, 116, 119, 121, 124, 127, 130, 132, 135, 138, 141, 143, 146, 149, 152, 155, 158, 161, 164, 166, 169, 172, 175, 178, 181, 184, 187, 190, 193, 196, 200, 203, 206, 209, 212, 215, 218, 221, 224, 227, 230, 234, 237, 240, 243, 246, 249, 252, 256, 259, 262, 265, 268, 271, 274, 277, 281, 284, 287, 290, 293, 296, 299, 302, 305, 308, 311, 315, 318, 321, 324, 327, 330, 333, 336, 339, 342, 345, 347, 350, 353, 356, 359, 362, 365, 368, 370, 373, 376, 379, 381, 384, 387, 390, 392, 395, 397, 400, 403, 405, 408, 410, 413, 415, 418, 420, 422, 425, 427, 429, 432, 434, 436, 438, 441, 443, 445, 447, 449, 451, 453, 455, 457, 459, 461, 463, 464, 466, 468, 470, 471, 473, 475, 476, 478, 479, 481, 482, 484, 485, 486, 488, 489, 490, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 503, 504, 505, 505, 506, 507, 507, 508, 508, 509, 509, 509, 510, 510, 510, 511, 511, 511, 511, 511, 511, 511, 511, 511, 511, 511, 510, 510, 510, 509, 509, 509, 508, 508, 507, 507, 506, 505, 505, 504, 503, 503, 502, 501, 500, 499, 498, 497, 496, 495, 494, 493, 492, 490, 489, 488, 486, 485, 484, 482, 481, 479, 478, 476, 475, 473, 471, 470, 468, 466, 464, 463, 461, 459, 457, 455, 453, 451, 449, 447, 445, 443, 441, 438, 436, 434, 432, 429, 427, 425, 422, 420, 418, 415, 413, 410, 408, 405, 403, 400, 397, 395, 392, 390, 387, 384, 381, 379, 376, 373, 370, 368, 365, 362, 359, 356, 353, 350, 347, 345, 342, 339, 336, 333, 330, 327, 324, 321, 318, 315, 311, 308, 305, 302, 299, 296, 293, 290, 287, 284, 281, 277, 274, 271, 268, 265, 262, 259]
plot(x)
show()
```
When you change the nature of the wave, by setting the type to triangle or arbitrary, the entire table is overwritten for the selected wave generator. The corresponding smaller wavetable is also rewritten.

**Comment by CloudyPadmal** [comment]
@jithinbp thanks a lot for the update! :) It's the same data set and I used Google sheets to draw the plot after appending a new line to every value using a simple python script. That must be buggy and the data set doesn't show variations like the graph I plotted!

**Comment by jithinbp** [comment]
@CloudyPadmal  Instead of #.#### , you could also consider changing units to mV and display ####.# . Seems friendlier to me.
You could also use something similar to the `applySIPrefix` function used in pslab-desktop-apps to create a more user friendly notation.
```
def applySIPrefix(value, unit='',precision=2 ):
		neg = False
		if value < 0.:
			value *= -1; neg = True
		elif value == 0.:  return '0 '  # Mantissa & exponent both 0
		exponent = int(np.log10(value))
		if exponent > 0:
			exponent = (exponent // 3) * 3
		else:
			exponent = (-1*exponent + 3) // 3 * (-3)

		value *= (10 ** (-exponent) )
		if value >= 1000.:
			value /= 1000.0
			exponent += 3
		if neg:
			value *= -1
		exponent = int(exponent)
		PREFIXES = "yzafpnum kMGTPEZY"
		prefix_levels = (len(PREFIXES) - 1) // 2
		si_level = exponent // 3
		if abs(si_level) > prefix_levels:
			raise ValueError("Exponent out range of available prefixes.")
		return '%.*f %s%s' % (precision, value,PREFIXES[si_level + prefix_levels],unit)
```
applySIPrefix(0.0025,'V',2) ->  2.50mV
applySIPrefix(2500,'V',2) ->  2.50KV

**Comment by CloudyPadmal** [comment]
Wow that's a really nice point @jithinbp ! That improves readability of values as well. I'll open a new issue and fix it there?

**Comment by jithinbp** [comment]
@CloudyPadmal thanks for considering it. I don't know how complex it might be to implement, especially since you're dealing with SpinBoxes, not simple Labels. do whatever you feel is convenient. :+1:

**Comment by CloudyPadmal** [comment]
That's a good thought @viveksb007 ! Let's do like that! :+1: and thanks guys for the reviews! :+1:

**Pull request merged**
