### PR TITLE
Updated MCP4728, DACCHANNEL, AnalogAquasitionChannel, AnalogConstants

### PR DESCRIPTION
**Pull request by akarshan96**
I have temporary reverted AnalogInputSource in order to resolve the merge conflicts. I will create a new PR for the same.

### CODE REVIEW

**Comment by viveksb007** [comment]
@akarshan96 there are build errors in your PR.
Did you checked your code by running it on device/emulator?
Plus I would suggest you to squash similar commits.

**Comment by akarshan96** [comment]
I have fixed the issue, thanks @viveksb007. Now the app is working fine. As I mentioned earlier I am new to GitHub, I am learning squashing the commits.

**Comment by akarshan96** [comment]
I have fixed the issue, thanks @viveksb007. Now the app is working fine. As I mentioned earlier I am new to GitHub, I am learning squashing the commits.

**Comment by viveksb007** [comment]
No worries, learn it first and then squash them as once merged, its not advised to change commit history.
Try to squash these 18 commits into 5 which shows the major changes/work you did.

**Comment by akarshan96** [comment]
@viveksb007, I am on it.
Thanks

**Pull request closed without merging**
