### PR TITLE
feat: Add wave generator preview

### LINKED ISSUE #1938: Wave Generator: Add visualization of wave
A wave visualization would be a useful tool to understand what is going on in the app. Compare to other apps on the playstore for example: https://play.google.com/store/apps/details?id=com.luxdelux.frequencygenerator
Screenshot_20190815_125122_com luxdelux frequencygenerator

### PR DESCRIPTION
**Pull request by neel1998**
Fixes #1938

**Changes**: wave generator preview working fine

**Screenshot/s for the changes**:

**Analog Mode**

**Digital Mode**

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**:
[wave_gen_preview.zip](https://github.com/fossasia/pslab-android/files/3551415/wave_gen_preview.zip)

@CloudyPadmal @mariobehling  I have added the preview feature to the wave generator UI. It is really looking good. Please review.  I have made a getSamplePoints() function which I will use again to produce sound for different waves for the issue #1937

### CODE REVIEW

**Comment by neel1998** [comment]
fixing codacy in a minute...

**Comment by CloudyPadmal** [comment]
Nice. For phase, would be better if we can show a reference waveform and with respect to that the changes.

**Comment by neel1998** [comment]
Oh okay. I can do that.. i will keep the reference wave with zero phase and grey color. Sounds right?

**Comment by CloudyPadmal** [comment]
Yes. And for vertical axis labels, make them 0V at the bottom and 5V at top

**Comment by neel1998** [comment]
> Yes. And for vertical axis labels, make them 0V at the bottom and 5V at top

I was thinking of removing the y axis labels. Since we can change the amplitude in oscilloscope. These labels might confuse the users

**Comment by neel1998** [comment]
@CloudyPadmal  I have added reference wave as you suggested... Hace updated GIFs and apk.

**Comment by neel1998** [comment]
@mariobehling please review and merge this. I need a function implemented in this PR to add sound feature in wave generator. Thanks

**Pull request merged**
