### PR TITLE
Added code to obtain permission to access USB device explicitly for API Level < 18

### LINKED ISSUE #179: Add code to obtain permission to access USB device explicitly
**Actual Behaviour**

Currently App crashes when opened manually launched as App doesn't have permission to access USB device explicitly. Previously Activity is launched by ```intent``` ```action-filter``` and permission is given by system.

**Expected Behaviour**

If permission is not given by system, then ask user to access USB device, this would prevent app from crashing.

**Steps to reproduce it**

Latest device have option to check, and them system gives permission automatically in manual case too. But in devices with API level 15, system might not be able to give permission automatically.
Uninstall App and re-install it, connect device when system asks for permission deny. Open the App it crashes.

**LogCat for the issue**

Log is available in Parent Issue : https://github.com/fossasia/pslab-android/issues/156

**Screenshots of the issue**

None

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by akarshan96**
Fixes #179
Changes:
Permission to access USB device explicitly for API levels < 18 will be asked from the user.

Screenshots for the change: 

screenshot_1497722241

On selecting cancel

screenshot_1497722696

### CODE REVIEW

**Comment by jithinbp** [comment]
Neat  :+1: .  Can I get the APK directly somewhere, or should I pull your branch and try it?
the 'please grant permissions...' is a Toast, right?  Does it make sense to turn it into a temporary button that says 'grant permissions ..' ? And if the user clicks it, the dialog pops up again?  This way an app restart/device replugging won't be needed

**Comment by akarshan96** [comment]
@jithinbp here is the [link](https://drive.google.com/file/d/0B423XEmWL9vKbm1nYTFyOEpaN1U/view?usp=sharing) of the apk. Let me try to create a button to pop up the dialog again.
Thanks

**Comment by jithinbp** [comment]
Thanks for the link.

I tried it on the API 15 tablet, and it was stuck at 'initializing wait... ' for about a minute or two. During which time the OS raised a 'force close?' dialog which I cancelled.
And then the message became 'initialization completed' . 
But version string was not displayed. I'll give logs in the morning. 
Some other points
- no graph displayed in the oscilloscope app( maybe it's because of the low display Resolution). The right sidebar takes up the whole screen.
- logic analyser app forces portrait mode

**Comment by akarshan96** [comment]
@jithinbp, I have made some changes in Oscilloscope UI to support API level 15. [link ](https://drive.google.com/file/d/0B423XEmWL9vKREtzWnBWaUtZSU0/view?usp=sharing) of the apk.

**Comment by jithinbp** [comment]
@akarshan96 I can confirm that the oscilloscope UI has been fixed, and I that can see the graph now. Initialization still takes over a minute or two.

Two finger scroll works along the time axis, and is smooth.
When I change the voltage range for CH1, the grid is changed,  but the existing grid of CH2(right axis) is still there. This makes odd combinations for the grid appearance. Should we emulate the desktop-app , or try something else?

CH1,CH3,MIC are linked to the left axis. So when the range for CH1 is changed, visible portion of CH3 and MIC is also changed, although that should not be the case.
Should we go with a standard oscilloscope UI, where Volts/div is shown against each channel, and a fixed grid is used?  If the user wants detailed voltage readings from the graph, a touch activated crosshair can be enabled. thoughts? @viveksb007 @CloudyPadmal

**Comment by jithinbp** [comment]
@akarshan96 cancel the remarks on the initialisation. I think I was testing with faulty hardware. It took 3-5 seconds with one that works (bear in mind that the API 15 tablet is pretty slow, so this is probably not indicative of the performance on newer phones)
But in light of what happened, I think the initialisation routine should only be called if the version check was a success. I'll record logs with the faulty device in the morning.
Also, the initialisation message can be updated as the routine progresses. This will keep the user in the loop, and will probably also prevent the OS from thinking the app has frozen up.
Thanks

**Comment by viveksb007** [comment]
@jithinbp Actually, initialisation is still going on in the main UI thread. Another thread just calls initialise function after 1 sec., In that 1 sec. version string and ```Initialisation Wait``` status is set up, then UI would be too laggy for 3-4 sec. because initialisation is taking place. After initialisation is completed UI is fully responsive again ( Then message is changes to ```Initialisation Completed``` )  . 
Shifting all variables from main thread to another thread then only UI thread would be free ( Not sure UI thread could access those variables later,as that thread's lifetime needs to be extended till Application context, Its a bit confusing and OS related stuff I am not sure too ).
I was thinking of shifting initialisation to splash screen, but splash screen taking 3-4 sec would that be okay?
And in modern mobiles too it takes 3-4 sec, maybe its limited communication speed or something, what might be the reason?
About Oscilloscope UI, I think Volt/div for each channel would be okay, as user can inspect the division and calculate on its own.

**Comment by CloudyPadmal** [comment]
@jithinbp that's a very good thought. I guess that implementation will simplify things without getting into much of a trouble to generalize axis for different ranges! :)

**Comment by akarshan96** [comment]
@jithinbp, I will work on your suggestion regarding Oscilloscope UI 👍 . @viveksb007 moving initialisation to splash screen is a great idea. @CloudyPadmal, using `Snackbar` is a great idea and I will make a new issue and implement it.

**Comment by jithinbp** [comment]
@viveksb007 splash screen is a nice idea :) . We can put it on the wishlist for better UX, since things are working fine now, and we can start addressing the activities.
speed issue is probably because we split the calibration read. The scheduler tries to manage other pending tasks in between reads, and the whole process becomes much much slower. Bulk read is faster because the CPU is focussed on that. We'll modify the calibration routine to address this

**Comment by jithinbp** [comment]
@viveksb007 I raised an issue regarding graceful handling of faulty hardware. As I had suspected, the read routine just goes through a number of timeouts without checking for data validity.
The logs are in the issue #193
I'd say we should first try a version read. If that fails/times out, then don't go for any further reads.
:+1:

**Comment by viveksb007** [comment]
@jithinbp that's a nice way to handle it. So if I couldn't read version I would tell user that **version check failed. Maybe fault in hardware.**, and some way to send logs to developer or any other thing that user can do to handle it.

**Comment by akarshan96** [comment]
Made some suggested changes. New commits fix #192 and #191.
Changes:
- Added Oscilloscope UI support for API levels < 18
- Added Snackbar to ask user to grant permission if not provided

Link of the apk - https://drive.google.com/file/d/0B423XEmWL9vKeWVSUld2ZXBROEk/view?usp=sharing

Screenshots of change

screenshot_1497783700
screenshot_1497783724

**Comment by viveksb007** [comment]
@akarshan96 I am still getting same error.

- I installed the app after uninstalling old one.
- I connect pslab device automatic permission pops up, I denied it.
- When I open app, it crashes with logs below. I am not getting the permission dialog. Did the same procedure worked in your device?

```
06-18 20:00:36.703 8116-8116/org.fossasia.pslab E/UsbManager: exception in UsbManager.openDevice
                                                              java.lang.SecurityException: User has not given permission to device UsbDevice[mName=/dev/bus/usb/001/002,mVendorId=1240,mProductId=223,mClass=239,mSubclass=2,mProtocol=1,mManufacturerName=Microchip Technology Inc.,mProductName=MCP2200 USB Serial Port Emulator,mVersion=2.0,mSerialNumber=0001462046,mConfigurations=[
                                                              UsbConfiguration[mId=1,mName=null,mAttributes=128,mMaxPower=50,mInterfaces=[
                                                              UsbInterface[mId=0,mAlternateSetting=0,mName=null,mClass=2,mSubclass=2,mProtocol=1,mEndpoints=[
                                                              UsbEndpoint[mAddress=130,mAttributes=3,mMaxPacketSize=8,mInterval=2]]
                                                              UsbInterface[mId=1,mAlternateSetting=0,mName=null,mClass=10,mSubclass=0,mProtocol=0,mEndpoints=[
                                                              UsbEndpoint[mAddress=3,mAttributes=2,mMaxPacketSize=32,mInterval=0]
                                                              UsbEndpoint[mAddress=131,mAttributes=2,mMaxPacketSize=64,mInterval=0]]
                                                              UsbInterface[mId=2,mAlternateSetting=0,mName=null,mClass=3,mSubclass=0,mProtocol=0,mEndpoints=[
                                                              UsbEndpoint[mAddress=129,mAttributes=3,mMaxPacketSize=16,mInterval=1]
                                                              UsbEndpoint[mAddress=1,mAttributes=3,mMaxPacketSize=16,mInterval=1]]]]
                                                                  at android.os.Parcel.readException(Parcel.java:1620)
                                                                  at android.os.Parcel.readException(Parcel.java:1573)
                                                                  at android.hardware.usb.IUsbManager$Stub$Proxy.openDevice(IUsbManager.java:418)
                                                                  at android.hardware.usb.UsbManager.openDevice(UsbManager.java:317)
                                                                  at org.fossasia.pslab.communication.CommunicationHandler.open(CommunicationHandler.java:75)
                                                                  at org.fossasia.pslab.communication.ScienceLab.<init>(ScienceLab.java:85)
                                                                  at org.fossasia.pslab.others.ScienceLabCommon.openDevice(ScienceLabCommon.java:23)
                                                                  at org.fossasia.pslab.activity.MainActivity.onCreate(MainActivity.java:102)
                                                                  at android.app.Activity.performCreate(Activity.java:6303)
                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2402)
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509)
                                                                  at android.app.ActivityThread.access$1000(ActivityThread.java:153)
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                  at android.os.Looper.loop(Looper.java:154)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5529)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
06-18 20:00:36.703 8116-8116/org.fossasia.pslab D/CommunicationHandler: Claiming interfaces, count=3
06-18 20:00:36.703 8116-8116/org.fossasia.pslab D/CommunicationHandler: Control interface=UsbInterface[mId=0,mAlternateSetting=0,mName=null,mClass=2,mSubclass=2,mProtocol=1,mEndpoints=[
                                                                        UsbEndpoint[mAddress=130,mAttributes=3,mMaxPacketSize=8,mInterval=2]]
06-18 20:00:36.704 8116-8116/org.fossasia.pslab D/AndroidRuntime: Shutting down VM
06-18 20:00:36.704 8116-8116/org.fossasia.pslab E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: org.fossasia.pslab, PID: 8116
                                                                  java.lang.RuntimeException: Unable to start activity ComponentInfo{org.fossasia.pslab/org.fossasia.pslab.activity.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.hardware.usb.UsbDeviceConnection.claimInterface(android.hardware.usb.UsbInterface, boolean)' on a null object reference
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2449)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509)
                                                                      at android.app.ActivityThread.access$1000(ActivityThread.java:153)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5529)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
                                                                   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.hardware.usb.UsbDeviceConnection.claimInterface(android.hardware.usb.UsbInterface, boolean)' on a null object reference
                                                                      at org.fossasia.pslab.communication.CommunicationHandler.open(CommunicationHandler.java:81)
                                                                      at org.fossasia.pslab.communication.ScienceLab.<init>(ScienceLab.java:85)
                                                                      at org.fossasia.pslab.others.ScienceLabCommon.openDevice(ScienceLabCommon.java:23)
                                                                      at org.fossasia.pslab.activity.MainActivity.onCreate(MainActivity.java:102)
                                                                      at android.app.Activity.performCreate(Activity.java:6303)
                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2402)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509) 
                                                                      at android.app.ActivityThread.access$1000(ActivityThread.java:153) 
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                      at android.os.Looper.loop(Looper.java:154) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5529) 
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629) 

```

**Comment by asitava1998** [comment]
@akarshan96  I am also getting the same error as Vivek mentioned in the previous comment. I am attaching the log of the bug from my phone.

**Comment by CloudyPadmal** [comment]
@akarshan96 can we update branch from here or will you update with the fixes? :)

**Pull request closed without merging**
