### PR TITLE
chore: removed unused resources

### LINKED ISSUE #1702: Removing Unused Files
**Actual Behaviour**
Removing Unused Styles, Strings, Drawables, etc

**Would you like to work on the issue?**
YEP

### PR DESCRIPTION
**Pull request by adityastic**
Fixes #1702 

**Changes**: 
- Removed All Unused Drawables
- Removed All Unused colors, styles, dimens

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [ ] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [ ] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [ ] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [ ] My code does not contain any extra lines or extra spaces
- [ ] I have requested reviews from other members

**Test Application**
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/3169731/app-debug.apk.zip)

### CODE REVIEW

**Comment by adityastic** [comment]
@CloudyPadmal

**Comment by neel1998** [comment]
@adityastic  can you provide an apk so that I can once test the changes

**Comment by adityastic** [comment]
@neel1998 sure. Give me 3 hrs

**Comment by CloudyPadmal** [comment]
Conflicts to resolve :bell:

**Comment by adityastic** [comment]
@CloudyPadmal Review

**Comment by adityastic** [comment]
@neel1998 Updated Test APK

**Pull request merged**
