### PR TITLE
indicator added at the top of timeline

### LINKED ISSUE #1749: Add current position indicator to servo controller time line and functionality of play/pause/stop buttons
**Actual Behaviour**
Currently there is no indicator of current position in timeline of servo controller . Also functionality of Play/Pause/Stop buttons needs to be implemented

**Expected Behaviour**
Add a vertical bar which moves one second forward when play button is pressed. 

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by neel1998**
Fixes #1749 

**Changes**:a Red indicator added at the top of time line.

**Screenshot/s for the changes**:

Screenshot_20190530-005553

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [ ] I have requested reviews from other members

### CODE REVIEW

**Comment by adityastic** [comment]
Why not a horizontal progress bar?

**Comment by neel1998** [comment]
> Why not a horizontal progress bar?

I tried using the horizontal progress bar, but since time line is divided into 60 parts and we can't give fractional value to horizontal progress bar, we can't have exact indicator as we want.

**Comment by neel1998** [comment]
@CloudyPadmal since @ho-dor  is going to work on this PR. i think this can be merged with the current changes, rest will be updated in next PRs

**Comment by ho-dor** [comment]
I will resolve the unused imports codacy issue in future PRs

**Pull request merged**
