### PR TITLE
fix: input filter to robot arm

### LINKED ISSUE #2071: Add limit in input value
cc: @cweitat @CloudyPadmal @mariobehling

**Actual Behaviour**
In Robotic Arm Screen, the User can input as large value as they can in servo sections, Which causes the value out of its view bounds.

**Expected Behaviour**
Users should not be allowed to input more than 360. 

**Steps to reproduce it**

- Open the Application.
- Navigate to a Robotic-arm screen.
- Enter large values like "338439483" in any servo section.
- You will found that the values cross the view bounds.

**Screenshots of the issue**

WhatsApp Image 2020-01-13 at 5 00 11 PM

**Would you like to work on the issue?**
Yes, I would like to work on the issue.

### PR DESCRIPTION
**Pull request by juniorjainsahab**
Fixes #2071 

**Changes**
- Applied Input filters to all the editText of servo sections.
- Set max length to 3 into the editText of 'servo_controller_layout.xml'

**Screenshot/s for the changes**: 

output

**Checklist**
- [X] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [X] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [X] My code does not contain any extra lines or extra spaces

**APK for testing**: 
[app-apk.zip](https://github.com/fossasia/pslab-android/files/4064895/app-apk.zip)

### CODE REVIEW

**Comment by CloudyPadmal** [comment]
Hello @juniorjainsahab , there are some conflicts in this PR needs to be resolved.

**Comment by juniorjainsahab** [comment]
@CloudyPadmal The PR was perfectly fine from my side and without conflicts. But @mariobehling merges #2073 for the same issue which is responsible for the conflicts. As the way of raising #2073 was quite wrong but we can't do anything in this So, this PR ends up like nothing.

**Comment by CloudyPadmal** [comment]
Hello @juniorjainsahab , I understand that there's been an issue but it's hard to block one from making a PR. It looks like in the meantime you were waiting for an approval, #2073 was raised and maintainers have gone with that. It was kinda not nice to work on an issue when someone has already answered **Yes** to **Would you like to work on the issue?** @991rajat without discussing it through with the original author. Let's do it right from now onwards..

Once an issue is raised, don't wait for any approval. Start with a fix right away and make a PR.

I would close this PR as #2073 is same.

**Comment by juniorjainsahab** [comment]
I understand it's hard to block people from raising a PR but this is an open-source community which we are building over here and such a lax attitude from maintainers would only spoil the whole environment. Sorry to be hard on this, but maintainers on this project needs to be little cognizant about such matters. This case should be treated as plagiarism. 
cc: @CloudyPadmal @mariobehling 

@991rajat there is something called integrity which you have to possess when you will be working as a professional. `Closing the issue` you said but instead, you deleted your comment afterward says a lot about your integrity in this case. 

image

**Pull request closed without merging**
