### PR TITLE
values-zh/string.xml created

### PR DESCRIPTION
**Pull request by ThisIsNSH**
First Step for issue #776 

Changes: Converted string.xml into chinese.

Screenshots for the change: None 

APK for testing: None

### CODE REVIEW

**Comment by ThisIsNSH** [comment]
@CloudyPadmal @akarshan96 @viveksb007 please review the changes in string.xml. 
I have chosen Chinese as it is one of the most spoken language. Further I will work on other languages to make the app localized.
Please suggest some languages if the idea of localization is ok.

**Comment by ThisIsNSH** [comment]
I used google translation @mariobehling. Suggest me something..

**Comment by CloudyPadmal** [comment]
@ThisIsNSH accuracy of Google translation would be questionable. A translation better done by a native speaker!

**Comment by CloudyPadmal** [comment]
@ThisIsNSH yes that's nice! :100:

**Pull request closed without merging**
