### PR TITLE
Guide for robotic arm

### LINKED ISSUE #1803: Create Guide for robotic arm
**Actual Behaviour**

Currently no guide in robotic arm

**Expected Behaviour**

A guide like all the other instruments should be there.

**Steps to reproduce it**
N/A

**LogCat for the issue**

N/A

**Screenshots of the issue**

N/A

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by ho-dor**
Fixes #1803 

**Changes**: Added bottomsheet guide for robotic arm.

**Screenshot/s for the changes**:

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [ ] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [ ] I have requested reviews from other members

**APK for testing**: 
[guide.zip](https://github.com/fossasia/pslab-android/files/3306450/guide.zip)

### CODE REVIEW

**Comment by ho-dor** [comment]
@CloudyPadmal @neel1998 i have a doubt , the bottomsheet requires Co-cordinatorLayout as parent and hence , returning null when I try to add it to robotic arm as it has linear layout and changing it to co-ordinator layout is messing it up completely . So , what should I do ? Use something else and not bottomsheet or build the UI of robotic arm with co-ordinator layout again ?

**Comment by neel1998** [comment]
Have you tried passing liners layout to bottom sheet?

**Comment by ho-dor** [comment]
Can you please explain ?

**Comment by CloudyPadmal** [comment]
Adding a coordinator layout might fix this issue :thinking:

**Comment by ho-dor** [comment]
> Adding a coordinator layout might fix this issue 🤔

It does , but the UI of robotic arm gets all messed up. I will just try to re-arrange the layout with co-ordinator layout.

**Comment by ho-dor** [comment]
Tried it but still the same issue 
`Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.view.View.getLayoutParams()' on a null object reference
        at android.support.design.widget.BottomSheetBehavior.from(BottomSheetBehavior.java:981)
        at io.pslab.activity.RoboticArmActivity.setUpBottomSheet(RoboticArmActivity.java:531)
        at io.pslab.activity.RoboticArmActivity.onCreate(RoboticArmActivity.java:93)
        at android.app.Activity.performCreate(Activity.java:7327)
        at android.app.Activity.performCreate(Activity.java:7318)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3095)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3258) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7073) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974) 
`
I have used the same implementation as in LA and oscilloscope . @CloudyPadmal @neel1998

**Comment by neel1998** [comment]
Are you using binder anywhere ? Try "Clean Project" and "Rebuild project" once

**Comment by ho-dor** [comment]
@neel1998 @CloudyPadmal please check. Was probably an issue with android studio , restarted it, worked fine.

**Comment by mariobehling** [comment]
@marcoag Could you help with the text, please?

**Comment by marcoag** [comment]
I believe this feature shouldn't be specific to a robotic arm, what it's really doing is just moving 4 servos, it can be a robotic arm or any other servo powered machine. Therefore the name, title and description should be focused on how to use this feature to move 4 servos.

**Comment by ho-dor** [comment]
@mariobehling please review the google doc . Shall I update it ?

**Comment by ho-dor** [comment]
@CloudyPadmal @mariobehling @neel1998 review

**Comment by CloudyPadmal** [comment]
We need to have instructions here in guide. Which pin gets connected to what pin and how to set values (long click and drag etc..). May be for now we can have the UI part merged and work on content in a separate PR.

**Comment by neel1998** [comment]
@ho-dor why all the merged commits included in your PR? what did you do?

**Comment by ho-dor** [comment]
@neel1998 silly mistake . resolved

**Comment by mariobehling** [comment]
Ok, let's add the details instructions in a follow up PR. Thanks!

**Pull request merged**
