### PR TITLE
fixes #2048 - add a Polish language

### LINKED ISSUE #2048: Add a language - Polish
**Actual Behaviour**

The app does not have a Polish language

**Expected Behaviour**

Full support for one additional language - Polish

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by rradzzio**
Fixes #2048 

**Changes**: Added a Polish language to strings.xml 

**Screenshot/s for the changes**: 
80557674_526457268218016_3566200676893589504_n
80631947_442273616650570_691511497255288832_n

### CODE REVIEW

**Comment by makoteq** [comment]
@rradzzio tłumaczyłeś to ręcznie?

**Comment by rradzzio** [comment]
@makoteq yes, with a little help from google translator

**Comment by CloudyPadmal** [comment]
@rradzzio anything wrong with this PR that you closed it? :thinking:

**Comment by cweitat** [comment]
@CloudyPadmal please review this. PR is person from Poland

**Pull request merged**
