### PR TITLE
fix: Actionbar added to Oscilloscope and Robotic Arm

### LINKED ISSUE #1929: Oscilloscope: UI issues and improvements
Please fix the following issues in the Oscilloscope UI:
* Fix cut of words on all screens in different resolutions, e.g. "Rang-e"
Screenshot_20190814_215422_io pslab

* At points the bottom control bar of the phone appears without reason when some functions are used. Only show the control bar when actually required.
Screenshot_20190814_215358_io pslab

* Some text buttongs have different sizing, color and position than text with similar or same functionality. Use same text across different Oscilloscope components
* Implement a top bar and move Record and ? button to the top bar

### PR DESCRIPTION
**Pull request by neel1998**
Fixes #1929 #1930

**Changes**: Actionbar added to Oscilloscope and Robotic Arm

**Screenshot/s for the changes**: 

**Oscilloscope main layout**

**Oscilloscope Playback**

**Robotic Arm**

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 
[actionbar.zip](https://github.com/fossasia/pslab-android/files/3510711/actionbar.zip)

@CloudyPadmal  @mariobehling  I will add action bar to Logic Analyzer in separate PR... Since the implementation of LA is quite different (inflating a fragment in activity) i think I will have to come up with some hack or change the implementation. For now action bar works fine in oscilloscope and Robotic Arm. Thanks

### CODE REVIEW

**Comment by neel1998** [comment]
@CloudyPadmal sure... Sorry I forgot to squash in hurry...

**Comment by neel1998** [comment]
@CloudyPadmal i think this can be merged

**Comment by CloudyPadmal** [comment]
Test all the features and make sure they're working as intended.

**Comment by neel1998** [comment]
@CloudyPadmal sure I will test. That white space doesn't appear on my device. Maybe it's screen size issue... Will fix it. Thanks for the review

**Comment by neel1998** [comment]
@CloudyPadmal  i have set playback layout width to match_parent... please check if that white space still there. Also I was not able to reproduce the infinite loop you mentioned for looged data.. Can you please give me exact steps or a GIF. Thanks

**Comment by neel1998** [comment]
@CloudyPadmal please review

**Pull request merged**
