### PR TITLE
Fixes Issue #727 : Inverting Op-Amp and Non Inverting Op-Amp not showing up

### PR DESCRIPTION
**Pull request by ThisIsNSH**
Fixes issue #727 

Changes: The PeformExperimentAdapter had two cases which returned wrong instances. Two markdown files are created for the same which were missing.

Screenshots for the change:

### CODE REVIEW

**Comment by ThisIsNSH** [comment]
Screenshot:

screenshot_2018-03-07-22-39-15-388_org fossasia pslab
screenshot_2018-03-07-22-39-21-270_org fossasia pslab

**Comment by Vipul999ujawane** [comment]
This issue has been sorted out in my PR. This issue was assigned to me.

**Comment by ThisIsNSH** [comment]
@Vipul999ujawane ok. I didn't see it.

**Comment by CloudyPadmal** [comment]
@ThisIsNSH I'm closing this since it was fixed in #739

**Pull request closed without merging**
