### PR TITLE
Guide re-open accelerometer issue solved

### LINKED ISSUE #1459: Unable to open the guide from bottom of the screen of Accelerometer
**Actual Behaviour**

When we try to re-open the guide from the bottom of the screen, it isn't opening

**Expected Behaviour**

When we slide up from the bottom of the screen, the guide should re-open

**Steps to reproduce it**

Open the Accelerometer and slide up from the bottom of the screen

**LogCat for the issue**

Not Applicable

**Screenshots of the issue**

Not Applicable

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by ho-dor**
Fixes #1459 

**Changes**: onTouchEvent method added in the AccelerometerActivity

**Screenshot/s for the changes**:accelerometer

**Checklist**: 
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**:
[accelerometer.zip](https://github.com/fossasia/pslab-android/files/2684948/accelerometer.zip)

### CODE REVIEW

**Comment by ho-dor** [comment]
@CloudyPadmal please review . This is the same PR that I had closed due to errors.

**Comment by CloudyPadmal** [comment]
This motion event implementation is added in PSLabSensor abstract class. (Line 466)

**Comment by ho-dor** [comment]
What about the guide re-open issue for logic analyser and barometer and lux meter and compass ? Is that also solved due to the abstract class ? Thanks .

**Comment by CloudyPadmal** [comment]
Barometer and Luxmeter already extends the PSLabSensor class, so they are resolved. Logic Analyzer cannot extend that class. Compass is not complete yet.

**Pull request closed without merging**
