### PR TITLE
Fixes #146 creates read section of Control UI

### LINKED ISSUE #146: Control UI implementation - Read
The parent issue is #41 . The thread has important discussion regarding the same. This thread would include the portion of using PSLab as a measurement unit to get resistance, capacitance, voltage etc.

-  [ ]  Layout design
-  [ ]  Code for adding functionalities

The current mockup is here:-
control

The actual UI is here:-

The design changes will also be done to make the UI better

### PR DESCRIPTION
**Pull request by asitava1998**
Fixes Issue #146
Changes: 
* Changed the UI for resistance & capacitance labels.
* Added methods for Control Read section. (haven't been tested, so commented till then)
* Temporarily replaced Butterknife due to a null object exception error. Need to identify the actual cause of the problem that led to this.(will find it out)

Screenshots for the change:

### CODE REVIEW

**Comment by mariobehling** [comment]
Please remove the label [WIP] when you are done with this PR.

**Comment by mariobehling** [comment]
@viveksb007 @akarshan96 @CloudyPadmal I am confused: How can you accept this PR, when it is still WIP?

**Comment by viveksb007** [comment]
@mariobehling based on changes mentioned in description, this PR is acceptable. 
Code for functionality is commented out, because that part hasn't been tested yet. Once @akarshan96 is done with Adding calls for initailzing and runInitSequence, we can test the code for functionality added here.

**Comment by mariobehling** [comment]
@viveksb007 In that case the commit message needs to be changed first and [WIP] needs to be taken out.

**Comment by asitava1998** [comment]
@mariobehling In that case let me change the commit message. I will create a fresh issue for testing of functionality.

**Comment by mariobehling** [comment]
Thanks. Seems like it was not changed in the actual commit. Well, let's follow this more closely next time together. Before you want a commit merged, please take out "WIP". Thanks.

**Pull request merged**
