### PR TITLE
Added Thermometer UI

### LINKED ISSUE #1629: New instrument : Thermometer
**Actual Behaviour**

There is no device to calculate temperature in the app.

**Expected Behaviour**

Using the inbuilt android ambient temperature sensor , create a thermometer.

**Steps to reproduce it**

Not applicable

**LogCat for the issue**

Not Applicable

**Screenshots of the issue**

Not applicable

**Would you like to work on the issue?**

Yes .

### PR DESCRIPTION
**Pull request by ho-dor**
Fixes #1629 

**Changes**: Added UI for thermometer

**Screenshot/s for the changes**: 
Screenshot_20190528-003046_PSLab

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**:
[thermo.zip](https://github.com/fossasia/pslab-android/files/3225735/thermo.zip)

### CODE REVIEW

**Comment by neel1998** [comment]
@ho-dor  the UI looks a bit out of place as compared to other instruments in terms of colors and shapes. It doesn't look consistent with the whole app @mariobehling @CloudyPadmal  have a look at this

**Comment by neel1998** [comment]
Also we need to discuss the functionality of logging data in thermometer , temperature won't change rapidly like luxmeter or compass.... So just recording data for few seconds doesn't make sense. We can have something like a service that records the data in background for lo ger period, which can be useful for analysis. But recording like compass, or luxmeter or other instruments won't make much sense here. we need to think possible options

**Comment by cweitat** [comment]
@neel1998 With regards to what Neel said, there could be a implementation of a setting to let user choose the record period. 
@ho-dor standardise the background to white. currently thermomether background is gray. Also, the thermomether only has a range between 35 to 42 celsius? There's a lot of white space in between. You can increase the font size of the thermomether

**Comment by ho-dor** [comment]
@neel1998 please review

**Comment by cweitat** [comment]
Only available in Farenheit?
Also, please take note of the uploaded file format. Is .apk not .zip

**Comment by ho-dor** [comment]
@cweitat for now I have only added Fahrenheit . Moving forward , I will add an option for user to change between units . 
Also , the file is zip . Apk format is not supported anyway when we upload it .

**Comment by cweitat** [comment]
What I meant was to zip the apk instead of just renaming the apk to zip. This way, it is easier to download and install through chrome. Chrome can't open your zip file on mobile.

**Comment by ho-dor** [comment]
But I have used the convertio chrome extension to convert to zip.

**Comment by cweitat** [comment]
Refer to Neel's zip in his PR. You know what I mean.

**Comment by mariobehling** [comment]
Thank you! Please follow up on further features in follow up issues/PRs. Keep it up!

**Pull request merged**
