### PR TITLE
Accelerometer code refactored

### LINKED ISSUE #1812: Accelerometer has a lot of Redundant Codes
**Actual Behaviour**

A lot of redundant code in accelerometer.

**Expected Behaviour**

Should be more like gyroscope.

**Steps to reproduce it**

N/A

**LogCat for the issue**

N/A

**Screenshots of the issue**

N/A

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by ho-dor**
Fixes #1812 

**Changes**:Accelerometer code changed more like gyroscope

**Screenshot/s for the changes**: N/A

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [ ] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 
[refactor.zip](https://github.com/fossasia/pslab-android/files/3319454/refactor.zip)

### CODE REVIEW

**Comment by neel1998** [comment]
Codacy

**Comment by ho-dor** [comment]
Not crashing in my device @neel1998 . Can you please send a gif or log of the crash

**Comment by ho-dor** [comment]
https://drive.google.com/file/d/1-Bu1MopzBFHZHCi-oXqA5uZugOccMFNX/view?usp=sharing

**Comment by neel1998** [comment]
Why is it showing no data fetched when you played the log. I am trying from the apk..Is the apk in the PR the latest one?.. please check

**Comment by neel1998** [comment]
Also make screen taps visible when you make a gif...It's hard to understand which buttons you are pressing from this gif

**Comment by ho-dor** [comment]
> Why is it showing no data fetched when you played the log. I am trying from the apk..Is the apk in the PR the latest one?.. please check

Ya I found that error now . I will update and send the apk

**Comment by CloudyPadmal** [comment]
@neel1998 it would be helpful if you can submit the crash log

**Comment by ho-dor** [comment]
@neel1998 does your device have the gyroscope sensor ? If yes, can you send a gif of logged data.

**Comment by ho-dor** [comment]
@neel1998 @CloudyPadmal  please check.

**Comment by ho-dor** [comment]
@neel1998 the issue is actually deeper than I thought . I am going to try and make a PR tomorrow

**Comment by neel1998** [comment]
@ho-dor  cool. No problem.

**Comment by ho-dor** [comment]
@neel1998 @CloudyPadmal I have updated the apk.

**Comment by neel1998** [comment]
@ho-dor  pause button while playing back is not working. Even if i click on play the graphs continue to move forward

**Comment by ho-dor** [comment]
@neel1998  updated the apk . Check

**Comment by ho-dor** [comment]
@neel1998 please review this . Its been pending

**Comment by CloudyPadmal** [comment]
Tested the provided apk. It's not crashing though :thinking:

**Comment by ho-dor** [comment]
Yeah, it has been resolved, the logged data doesn't start on it's own either and pauses when it should. I think this good to go.

**Comment by neel1998** [comment]
@CloudyPadmal  It's not suppose to crash after the fix. So i think the PR is good to go

**Comment by CloudyPadmal** [comment]
@neel1998 @ho-dor all ok?

**Pull request merged**
