### PR TITLE
Fixes #263 : Read section in control supports HDPI screens

### LINKED ISSUE #263: Read section of Control UI doesn't support hdpi screens
**Actual Behaviour**

`Read` section of control UI doesn't support hdpi screens

**Expected Behaviour**

App should support hdpi screens as well

**Steps to reproduce it**

1. Open App
2. Go to `Applications`
3. Open `Control` and click on `Read` tab
4. Observe the text lables

**LogCat for the issue**

> Not available

**Screenshots of the issue**

Where-ever possible add a screenshot of the issue.

screenshot_2017-07-03-09-09-07

Let us know if this issue should be assigned to you or tell us who you think could help to solve this issue.

Yes!

### PR DESCRIPTION
**Pull request by CloudyPadmal**
Fixes issue #263 

Changes:
- Added two layout files to support hdpi and xhdpi screens separately in Read section in Control UI

Screenshots for the change: 

| HDPI | XHDPI |
| ------- | -------- |
| hdpi | xhdpi |

APK for testing
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1118406/app-debug.apk.zip)

### CODE REVIEW

**Comment by viveksb007** [comment]
@CloudyPadmal the layout is not according to material guidelines, actually by making background of everything Red, you are making it difficult for user to identify what are buttons and what are labels.
By looking at the screenshot a new user won't be able to tell the difference between buttons and labels. And you done this to almost all screens in control main. Please revert back. And Please follow [material guidelines](https://developer.android.com/design/material/index.html).

**Comment by CloudyPadmal** [comment]
Thanks for the review @viveksb007 ! :+1: I'll make the changes and update this PR!!

**Comment by CloudyPadmal** [comment]
Hello @viveksb007 ! I've made the changes as follows
- Textviews with no background as labels
- Added selectors to buttons

| hdpi | xhdpi |
| ------ | ------- |
| hdpi | xhdpi |

APK for testing -> [app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1121136/app-debug.apk.zip)

**Comment by viveksb007** [comment]
@CloudyPadmal 
screenshot_2017-07-04-12-13-23-508_org fossasia pslab

This is what I am having now. It was okay before when @asitava1998 made. Now things are getting complicated and instead of testing functionality we are stuck with UIs for quite long now.

**Comment by viveksb007** [comment]
screenshot_2017-07-04-12-27-33-828_org fossasia pslab

This is what we currently have in the repo, what we can do is have border around TextView so that its clear that there is a TextView, Rest things look okay to me.

**Comment by CloudyPadmal** [comment]
Ah there seems an issue! Sure @viveksb007 I'll make the changes! :+1: For a hdpi screen it displays only 'Count' and 'Pulses' is been cut off. That's why I opened up this issue and made it compatible! Can you please see if this [app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1121210/app-debug.apk.zip) fixes it in your device ? Thanks a lot!

**Comment by viveksb007** [comment]
Yes UI in current apk is good.

**Comment by CloudyPadmal** [comment]
That is superb!! :+1: Here I'm sending the commit so! Thanks for the review @viveksb007 !!

**Comment by viveksb007** [comment]
@CloudyPadmal could you provide final apk for testing this PR? After testing we can merge this PR.

**Comment by CloudyPadmal** [comment]
Sure @viveksb007 ! Thanks a lot! :+1: 

This is the built APK -> [app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1128034/app-debug.apk.zip)

**Comment by viveksb007** [comment]
UI is okay is my device @akarshan96  and @asitava1998  could you also check on your devices for some issue. If not we can improve UI from here in next iterations.

**Pull request merged**
