### PR TITLE
Implemented graph in HMC5883L

### LINKED ISSUE #318: Implement graph in hmc5883l fragment
**Actual Behaviour**

Graphs in hmc5883l fragment is not implemented yet

**Expected Behaviour**

Graph should be implemented in hmc5883l

**Steps to reproduce it**

> None

**LogCat for the issue**

> None

**Screenshots of the issue**

> None

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by akarshan96**
Fixes #318 

Changes: 
- Added real-time graph 

Note: 
1) for now raw data points are plotted with the time gap of 500 milliseconds.
2) @asitava1998 is looking into the conversion of raw data to Gauss.

Screenshots for the change: 
screen shot 2017-07-17 at 10 38 55 pm

### CODE REVIEW

**Comment by viveksb007** [comment]
@akarshan96 horizontal grid lines doesn't seem to be uniform. What could be the reason?

**Comment by asitava1998** [comment]
The better if lines are at 0, 2, -2, 4, -4 etc. and not at 0, 1, -1, 3, -3. Maintains the uniform gap everywhere.

**Comment by akarshan96** [comment]
@viveksb007 @asitava1998 let me look what's causing this.

**Comment by akarshan96** [comment]
@asitava1998 I have made the suggested changes, can you test the apk and share the screenshot
Apk: 
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1156382/app-debug.apk.zip)

**Comment by asitava1998** [comment]
@akarshan96 @viveksb007  here is the latest screenshot. The problem of non-uniform grid lines is now corrected.

**Pull request merged**
