### PR TITLE
Created Oscilloscope UI

### LINKED ISSUE #33: Oscilloscope UI
This is the first step towards the development Oscilloscope's UI.

screenshot_1491903305

screenshot_1491903314

The above image showcase the landscape mode of the Oscilloscope Activity. 
Gestures will also be integrated, like
-pinch zoom for changing the timebase.
-double tap on the graph to freeze.
-swipe down to save.

Please give suggestions on:
-layout and what needs to be improved.
-real-time graph api to be used ( I have used GraphView http://www.android-graphview.org). We can also use MPAndroidChart https://github.com/PhilJay/MPAndroidChart).
-I have researched on 3D graphs libraries but they are paid.
-any other thing I missed.

### PR DESCRIPTION
**Pull request by akarshan96**
fixes #33 
Sorry for the long PR, it might be difficult to review. From next time I will break the issue into sub-issues.
video link - https://goo.gl/photos/mdbNoaGZHk8MBoreA
Screenshots
screenshot_2017-06-10-16-42-05-325_org fossasia pslab

**Channel Parameters**

screenshot_2017-06-10-16-42-24-515_org fossasia pslab

**Timebase and Tigger**

screenshot_2017-06-10-16-42-39-945_org fossasia pslab

**Data Analysis**

screenshot_2017-06-10-16-42-51-463_org fossasia pslab

**XY Plot**

### CODE REVIEW

**Comment by jithinbp** [comment]
The video was pretty neat. :)
Can you also enable "Show Touches (Show visual feedback for touches )" on you phone's developer options section for future screencasts? Settings>Developer Options> Input > Show touches. Since there is no visible cursor, we can really know the user input behaviour. Thank you

For CH1, if you change the mapping to some other analog input, does the label also change?  Or should we convert the label itself into a combobox?

**Comment by akarshan96** [comment]
@jithinbp I will keep that in mind. 
A combo box is provided where the user can select the analog inputs, I forgot to open it in the video. There is no label for the same.

**Comment by viveksb007** [comment]
@CloudyPadmal from what I can see its only UI as Issue #33 states. Actual functionality needs to be implemented yet. 
@akarshan96 Communication between Fragments and Activity has been established through interface but  nothing is being communicated like which channel  selected, channel parameters, etc. If you are going to do that during actual functionality implementation. Open an issue for it ( **implement Oscilloscope functionality wrt this UI** ) please.
Good work :+1:

**Comment by CloudyPadmal** [comment]
Ah! Thank you Vivek! that's cleared now @viveksb007 :+1:

**Comment by asitava1998** [comment]
@akarshan96 Can you please check your code in phones of different resolutions like one in 1920x1080, 1280x720 etc. and see if everything is fitting properly in all the cases?

**Comment by jithinbp** [comment]
Mine's 1280*720 . I'll check it tomorrow.

I also have a 10" (1024*600) tab. Will send a few screenshots from that too.

**Comment by akarshan96** [comment]
Yes, @viveksb007 I have left that part. This PR only deals with UI, I will create an issue for implementing Oscilloscope functionality with respect to this UI.
Thanks

**Comment by jithinbp** [comment]
@akarshan96 I ran into build errors . deleted and cloned afresh, but it's still there. Any pointers?

Error:(41, 0) Gradle DSL method not found: 'compile()'
Possible causes:<ul><li>The project 'pslab-android' may be using a version of the Android Gradle plug-in that does not contain the method (e.g. 'testCompile' was added in 1.1.0).
<a href="fixGradleElements">Upgrade plugin to version 2.3.1 and sync project</a></li><li>The project 'pslab-android' may be using a version of Gradle that does not contain the method.
<a href="open.wrapper.file">Open Gradle wrapper file</a></li><li>The build file may be missing a Gradle plugin.
<a href="apply.gradle.plugin">Apply Gradle plugin</a></li>

The last link gives me a list of plugins to apply.

**Comment by akarshan96** [comment]
@jithinbp Let me look into this issue, I will get back to you asap.

**Comment by jithinbp** [comment]
@akarshan96 error message : 
```
4:33 PM	Gradle sync failed: Could not find method compile() for arguments [com.android.support:cardview-v7:25.2.0] on DefaultExternalModuleDependency{group='com.android.support', name='appcompat-v7', version='25.2.0', configuration='default'} of type org.gradle.api.internal.artifacts.dependencies.DefaultExternalModuleDependency.
					Consult IDE log for more details (Help | Show Log)
```
I think I can manage this based on this [input from stackoverflow](https://stackoverflow.com/questions/29284236/failed-to-resolve-com-android-supportappcompat-v722-and-com-android-supportre)

**Comment by jithinbp** [comment]
@akarshan96 I've tested the scope UI on my Xiaomi Redmi 3S . 1280*720, 5.5" screen.
Video Link : https://goo.gl/photos/r91doAYFKL9KtfHp9

**Comment by jithinbp** [comment]
@akarshan96 regarding the 10" tab, the code no longer works. App crashes on startup.
```
06-11 19:16:43.584 2168-2168/org.fossasia.pslab W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x40a121f8)
06-11 19:16:43.594 2168-2168/org.fossasia.pslab E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  java.lang.NoSuchMethodError: android.hardware.usb.UsbDeviceConnection.bulkTransfer
                                                                      at org.fossasia.pslab.communication.CommunicationHandler.write(CommunicationHandler.java:149)
                                                                      at org.fossasia.pslab.communication.PacketHandler.sendByte(PacketHandler.java:60)
                                                                      at org.fossasia.pslab.communication.PacketHandler.getVersion(PacketHandler.java:43)
                                                                      at org.fossasia.pslab.communication.ScienceLab.getVersion(ScienceLab.java:431)
                                                                      at org.fossasia.pslab.activity.MainActivity.getHomeFragment(MainActivity.java:147)
                                                                      at org.fossasia.pslab.activity.MainActivity.access$000(MainActivity.java:46)
                                                                      at org.fossasia.pslab.activity.MainActivity$1.run(MainActivity.java:118)
                                                                      at android.os.Handler.handleCallback(Handler.java:605)
```

The API level is 15, and I had to reduce minSdkLevel to 15 from 18. So i guess this tablet is not something a lot of people will have [ Simmtronics Xtab 1010 ] . but It's still available for purchase, and the presence of two USB ports made it great  for hardware development.
I might have a 7" nexus tab, and I'll try to test on that.

**Comment by viveksb007** [comment]
@jithinbp That error is because of  [bulkTransfer](https://developer.android.com/reference/android/hardware/usb/UsbDeviceConnection.html#bulkTransfer) method that I used, it took care of offset implicitly. So I used it, min API level for it to use is 18. 
To support [ Simmtronics Xtab 1010 ] device I can add another method that uses write function on device by checking their API version.
Could you open an issue regarding this with logs?

**Comment by akarshan96** [comment]
@jithinbp before you try it on Nexus 7, let me add the code for tablet support. I have already made some changes and will be creating a PR today itself. I am using Nexus 7 emulator and I think the app would not crash on it.

**Comment by jithinbp** [comment]
@viveksb007 don't prioritize that task. The percentage of API 15 devices is 0.8% . API15 + OTG will be a small number. I'll make the issue anyway.
@akarshan96 No issues. I'll wait. I'll also borrow an Aakash tablet and a lenovo A7 tablet in the meantime

**Comment by akarshan96** [comment]
Latest commit fixes #152
Added Tablet screen size support for Oscilloscope UI. 

The following are the screenshots of Oscilloscope UI running on Nexus 10 emulator

screenshot_1497208067

screenshot_1497208075

screenshot_1497208080

screenshot_1497208085

**Comment by viveksb007** [comment]
@akarshan96 please solve the merge conflicts in strings.xml file

**Pull request merged**
