### PR TITLE
Fixes #375 : Minimum value for wave generating seekbars

### LINKED ISSUE #375: Control Main Wave generating seekbar minimum is not zero
**Actual Behaviour**

Minimum values of seek bars related to wave1, wave2 and square in control main is not set to zero but to 10

**Expected Behaviour**

In desktop application, minimum wave values are 0.

**Steps to reproduce it**

1. Open app
2. Go to `Applications`
3. Open `Control`
4. Try setting minimum values for `Wave1`, `Wave2`, `Square` seekbars

**LogCat for the issue**

> Not available

**Screenshots of the issue**

issueincontrolmain

| Knob 1 | Knob 2 |
| ------ | ------ |
| dapp1 | dapp2 |

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by CloudyPadmal**
Fixes issue #375 

Changes: 
- Set minimum values for `Wave1`, `Wave2`, `Square` according to desktop application

Screenshots for the change: 

fixedcontrolmain

APK for testing:
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1175856/app-debug.apk.zip)

### CODE REVIEW

**Comment by viveksb007** [comment]
@CloudyPadmal less than 10Hz frequency isn't generated in PSLab hardware that range was for that I guess. @asitava1998 could you confirm?

**Comment by asitava1998** [comment]
@CloudyPadmal   @viveksb007 is correct. PSLab can't generate waveforms below 10 Hz. So, the minimum was set to 10 and maximum at 5000.

**Comment by CloudyPadmal** [comment]
Oh! I thought since in desktop application minimum is zero PSLab can generate low frequencies like that! I'll make the changes! :+1:

**Comment by CloudyPadmal** [comment]
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1176916/app-debug.apk.zip)

**Comment by CloudyPadmal** [comment]
@viveksb007 , @akarshan96 , @jithinbp Hello guys! Can you have a look at this PR? :)

**Pull request merged**
