### PR TITLE
fix:No crash on saving graph when sensor absent

### LINKED ISSUE #1736: App crashes when save image button clicked in all instruments where sensor not present
**Actual Behaviour**

App crashes when save image button clicked in Compass logged data

**Expected Behaviour**

App should not crash

**Steps to reproduce it**

Record data in compass and play it , click on save image button on top right corner.

**LogCat for the issue**

java.lang.ArrayIndexOutOfBoundsException: Out of range  in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsResults.cpp line 103(requested: 0 valid: 0)
        at io.realm.internal.OsResults.nativeGetRow(Native Method)
        at io.realm.internal.OsResults.getUncheckedRow(OsResults.java:330)
        at io.realm.OrderedRealmCollectionImpl.get(OrderedRealmCollectionImpl.java:124)
        at io.realm.RealmResults.get(RealmResults.java:72)
        at io.pslab.fragment.CompassDataFragment.saveGraph(CompassDataFragment.java:235)
        at io.pslab.models.PSLabSensor.onOptionsItemSelected(PSLabSensor.java:396)
        at android.app.Activity.onMenuItemSelected(Activity.java:3630)
        at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:436)
        at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:196)
        at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
        at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
        at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:64)
        at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:204)
        at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
        at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
        at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:981)
        at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:625)
        at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
        at android.view.View.performClick(View.java:7339)
        at android.widget.TextView.performClick(TextView.java:14222)
        at android.view.View.performClickInternal(View.java:7305)
        at android.view.View.access$3200(View.java:846)
        at android.view.View$PerformClick.run(View.java:27788)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7073)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974)

**Screenshots of the issue**

N/A

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by ho-dor**
Fixes #1736

**Changes**: No crash when save image button clicked

**Screenshot/s for the changes**:N/A

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**:
[app-debug (2).zip](https://github.com/fossasia/pslab-android/files/3219444/app-debug.2.zip)

### CODE REVIEW

**Comment by ho-dor** [comment]
@neel1998 please review

**Comment by neel1998** [comment]
@ho-dor i was unable to generate this crash with compass even though my device didn't have sensor. I think we don't need this change since if there is no sensor "0" would be set as default data and that would be have just as normal. Kindly check if you have latest version of the code

**Comment by ho-dor** [comment]
@neel1998 I have rechecked with compass , it does get crashed . The same Logcat as in the issue .

**Comment by neel1998** [comment]
@ho-dor  Send the steps in detail or a gif

**Comment by neel1998** [comment]
Did following on the latest braanch... didn't get the crash

1. Open Compass (No sensor present)
2. Recorded data
3. Opened Log data activity
4. Opened the latest log
5. Tried saving the graph without playing and while playing
6. .jpg is stored without any crash

**Comment by ho-dor** [comment]
https://drive.google.com/open?id=1--n3MeajNvVnUWcfa3JDsErB4BoGo5W0

**Comment by neel1998** [comment]
I think your branch is not updated. You shoudn't have no data fetched toast, also the Bx, By, Bz values shoud be "0.0" not "0"

**Comment by ho-dor** [comment]
We are missing something . The Toast "No data fetched" is there in the updated branch in playdata() method . Check the upstream/fossasia repo to confirm and the image below shows that for me it is 0.0 and not 0. But in the video it showed 0 . Something is wrong. 
Screenshot_20190525-210422_PSLab

**Comment by ho-dor** [comment]
I have double checked , my branch is updated

**Comment by neel1998** [comment]
Mine as well
Screenshot from 2019-05-25 21-10-12

**Comment by ho-dor** [comment]
I have detected the error , please to the following steps in order :-  
1. Record data in compass and open it through menu.
2. Now open the logged data..
3. click on save image button and open it through snackbar.
4. Delete the logged data that you see.
5. Now go back using the back button of your phone and you will end up at the logged data which was deleted . This activity should not be shown when we go back since it is deleted .Now if you press save image , it crashes and that is obvious.

**Comment by neel1998** [comment]
Okaay... Adding onBackPressed() { fiinish(); } would solve the problem

**Comment by neel1998** [comment]
I don't think we need all the changes you have made in this PR. Kindly close this one and ope new one

**Comment by ho-dor** [comment]
Ya . Same thing that I was thinking . finish() will work here.

**Pull request closed without merging**
