### PR TITLE
Creates Layout and Fragment files for BH1750 and BMP180

### PR DESCRIPTION
**Pull request by asitava1998**
Fixes issue #313 

Changes: 
* Created layout files for `BH1750` and `BMP180`.
Changes remaining:
* Create fragment files for the above

Screenshots for the change: 

There are similar errors in the values displayed here like the previous ones.

### CODE REVIEW

**Comment by viveksb007** [comment]
@asitava1998 could you update this PR with screenshots of layout created?
Thanks

**Comment by asitava1998** [comment]
I haven't updated it and requested for reviews because i am still waiting for the sensors to arrive and then test them. Hopefully, it will be done by tomorrow.

**Comment by viveksb007** [comment]
resolve the conflicts and please change name of object such that it differs from class name to increase readability. Like ```BH1750 sensorBH1750``` instead of ```BH1750 BH1750``` in all the PRs. And create a new package named ```SensorFragments``` and put all sensor fragment files in it because Sensor files would increase from here.
Thanks

**Comment by asitava1998** [comment]
I will rename the objects but I think it would be better to create a new directory for `sensorfragments` after these 3 PRs are merged otherwise it would again cause conflicts.

**Comment by mariobehling** [comment]
Please resolve conflicts.

**Pull request merged**
