### PR TITLE
chore: updated build script to generate bundles

### LINKED ISSUE #1901: Master branch Playstore APKs not being built
**Actual Behaviour**

Once a release is made (i.e. push to master), master apks should be generated and supply them to fastlane for Google Play store. Build is ending without proceeding to next steps from https://github.com/fossasia/pslab-android/blob/master/scripts/upload-apk.sh#L24

**Expected Behaviour**

Generate signed apks and fastlane sends them to Google Play

**Steps to reproduce it**

> Not available

**LogCat for the issue**

https://travis-ci.org/fossasia/pslab-android/builds/565944930#L1705

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

@neel1998

### PR DESCRIPTION
**Pull request by adityastic**
Fixes #1901 

Changes:
- Updated Script to support aabs for both branches

### CODE REVIEW

**Comment by adityastic** [comment]
@neel1998 @CloudyPadmal

**Comment by neel1998** [comment]
@adityastic we will need to change .aab file name in fastlane command as well now.

**Comment by adityastic** [comment]
@neel1998 oh yes. Thanks

**Comment by adityastic** [comment]
@neel1998 updated have a look

**Comment by CloudyPadmal** [comment]
https://travis-ci.org/fossasia/pslab-android/builds/566083574#L1739
`1739: mv: cannot stat ‘app-playstore-debug.apk’: No such file or directory`

**Pull request merged**
