### PR TITLE
Fixes #1999 Replaced Toast Messages with Snackbar messages

### LINKED ISSUE #1999: Replace Toast with Snackbar
**Actual Behaviour**

Currently brief messages at some places in the app use Toast to display brief messages to the user.

**Expected Behaviour**

According to android documentation - 
> Snackbar is now the preferred way to display brief, transient messages to the user.

[https://developer.android.com/training/snackbar/](url)

Therefore it would be better to replace the Toast with Snackbar, as it is possible that in the future the support for Toast might end.

**Steps to reproduce it**

- Toast is displayed when the user tries to exit the app
- Toast message is displayed when the user tires to use an option which requires PSLab device without actually connecting the PSLab device.

**LogCat for the issue**

N/A

**Screenshots of the issue**
toast_issue1

toast_issue3

toast_issue4

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by reckoner1429**
Fixes #1999 

**Changes**:
Replaced all the occurrence of `Toast` with `Snackbar`. The class `io.pslab.others.CustomSnackbar` was used to make Snackbars.

**Screenshot/s for the changes**: 
issue1999_ss1
issue1999_ss2
issue1999_ss3
issue1999_ss4
issue1999_ss5
issue1999_ss6
issue1999_ss7

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [ ] I have requested reviews from other members

**APK for testing**:
[issue1999fix.zip](https://github.com/fossasia/pslab-android/files/3871021/issue1999fix.zip)

### CODE REVIEW

**Comment by neel1998** [comment]
Please don't open and close PR for same issue multiple times. Make changes to the same PR. Thank you.

**Comment by reckoner1429** [comment]
Sorry for that, will

**Comment by reckoner1429** [comment]
Sorry for that! Will be careful hence. Thanks :)

**Comment by reckoner1429** [comment]
Replaced Toast with Snackbar, please have a look and suggest changes if any.

**Comment by reckoner1429** [comment]
Hi people! Could someone please tell what should i do with this pull request, does it need any changes? I am new to open source contributions so I am not aware of the usual duration that it takes for a pull request to be reviewed and approved/rejected.

**Comment by reckoner1429** [comment]
Thanks and also you are welcome! @neel1998 :)

**Pull request merged**
