### PR TITLE
updated setupGuideLayout in abstract class PSLabSensor to hide image if not available in a sensor's bottomsheet guide

### PR DESCRIPTION
**Pull request by Ekagra**
Fixes: [empty imageview is sensors bottomsheet guide]

**Changes**: [updated setupGuideLayout in abstract class PSLabSensor to hide image if not available in a sensor's bottomsheet guide]

**Screenshot/s for the changes**: 
`Before-------------------------------------------------------------------------------------------------------------After`

<p float="left">
  
   
</p>

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

### CODE REVIEW

**Review by asaikarthikeya — COMMENTED** [review]
In every other instrument this space is filled with a PSlab hardware related image , I think adding a image would be better since it improve regularity in app . This would be a optimal solution till we get a image. Thank you.

**Review by CloudyPadmal — CHANGES_REQUESTED** [review]
Add an image instead of hiding the view.

**Comment by CloudyPadmal** [comment]
Also try to shorten the PR title

**Comment by Ekagra** [comment]
@CloudyPadmal what image should I add?

**Comment by Ekagra** [comment]
The view is only hidden if there's no image to display like right now, do you want me to add a placeholder?

**Review by CloudyPadmal — APPROVED** [review]

**Pull request merged**
