### PR TITLE
fix: pslab logo in nav menu

### LINKED ISSUE #2502: Navigation header partially cut off on tablet devices
**Actual Behaviour**

The header of the navigation is partially cut off / hidden on tablets.

**Expected Behaviour**

The header should be fully visible.

**Steps to reproduce it**

Start app on a tablet device in horizontal orientation.

**Screenshots of the issue**
### Actual Behaviour (tablet)
Screenshot_20240625-234458

### Expected Behaviour (phone)
Screenshot_20240625-235011

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by Dishebh**
Fixes #2502

## Changes 
- fixed pslab logo in nav menu 

## Screenshots / Recordings  

Screenshot 2024-09-08 at 11 27 20 PM

**Checklist**: 
- [ ] **No hard coding**: I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard coding any value.
- [ ] **No end of file edits**: No modifications done at end of resource files `strings.xml`, `dimens.xml` or `colors.xml`.
- [ ] **Code reformatting**: I have reformatted code and fixed indentation in every file included in this pull request.
- [ ] **No extra space**: My code does not contain any extra lines or extra spaces than the ones that are necessary.

### CODE REVIEW

**Comment by Dishebh** [comment]
@marcnause can you review this please?

**Review by marcnause — COMMENTED** [review]
Thank you for the PR. Good catch finding that the padding was the problem! I would like to propose a different solution (see https://github.com/fossasia/pslab-android/pull/2547/commits/94ee431ab5b6a554886bd2a734a2565d9c0be733) though.

The original change fixed the problem that the logo was cut off, but it also caused the text below the logo to be misaligned with the icons of the menu below.

Screenshot_20240908-230754

With the proposed different solution the screen looks like this:
Screenshot_20240908-231600

@Dishebh What are your thoughts on this?

**Comment by marcnause** [comment]
@sourcery-ai review

**Comment by Dishebh** [comment]
yea, this makes sense. Thanks @marcnause! I missed to check the "Not Connected" string alignment here (or rather, I just found out about this, this is me getting started with android development 😅 , sorry for the hiccup). Let me know if you would want me to do some other change?

**Review by marcnause — APPROVED** [review]
Thank you for your reply, @Dishebh! I think the visibility of the string also depended on the resolution of the test device.

I will merge the proposed change in a minute. You don't need to make any changes. I wanted to wait for your feedback though, in case you saw any reasons against the proposal.

Thank you for your effort and welcome to Android development! :smiley:

**Pull request merged**
