### PR TITLE
feat: Adding onboarding guide for instruments

### LINKED ISSUE #972: Implement 'How to use' section in all the instruments
**Actual Behaviour**
Right now there are no directions on how to use a particular instrument or a document helping new users implemented in the app.

**Expected Behaviour**
We must have one to help new users get acquainted to the app by themselves or can use it in some confusion.

**Steps to reproduce it**
Open app and open any instrument

**LogCat for the issue**
Not applicable

**Screenshots of the issue**
Not required

**Would you like to work on the issue?**
Yes I would like to implement a help button on the top which can be clicked to refer to the 'How to use' guide.

### PR DESCRIPTION
**Pull request by yatri1609**
First Step of #972 

Changes: 
Added guide to buttons in Multimeter and Oscilloscope 

Screenshots for the change: 

screenshot_2018-06-09-20-10-24-783_org fossasia pslab
screenshot_2018-06-09-20-10-29-116_org fossasia pslab
screenshot_2018-06-09-20-12-22-900_org fossasia pslab
screenshot_2018-06-09-20-13-55-666_org fossasia pslab

APK for testing: 
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2087053/app-debug.zip)

### CODE REVIEW

**Comment by yatri1609** [comment]
@Avjeet It was working fine in my phone when I tested it. Can someone else also have a look?  And I'll make guide to be shown just once.

**Comment by Avjeet** [comment]
Also in the PR change it to "First steps of issue " as this PR doesn't contain Guide for all instruments.

**Comment by yatri1609** [comment]
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2087155/app-debug.zip)

This is the updated apk please test it and for other instruments I'll be updating this guide once their new layout gets updated.

**Comment by yatri1609** [comment]
Ohk I'll have a look at the above issue

**Comment by yatri1609** [comment]
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2087865/app-debug.zip)

Check the updated apk in this I have fixed the issue for the multimeter and I'm still not sure of the problem with the cutting down of text.. I'm looking into it.

**Comment by yatri1609** [comment]
Closing this PR till we find a suitable library according to the requirements.

**Pull request closed without merging**
