### PR TITLE
feat: implementing barometer

### LINKED ISSUE #1331: Implement the barometer
**Actual Behaviour**

Currently the barometer can just be used with built in sensor available in very less devices

**Expected Behaviour**

The barometer should work with external sensors as well.

**Steps to reproduce it**

Go to instruments->barometer

**LogCat for the issue**

Not applicable

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by CloudyPadmal**
Fixes #1331 

**Changes**:
- Added barometer functionalities similar to luxmeter
- Added screenshots for instrument images

**Screenshot/s for the changes**: 

|  |  |
| -------- | -------- |
|  |  |

**Checklist**: 
- [X] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [X] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [X] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [X] My code does not contain any extra lines or extra spaces
- [X] I have requested reviews from other members

**APK for testing**: 
[BaroMeter.apk.zip](https://github.com/fossasia/pslab-android/files/2682566/BaroMeter.apk.zip)

### CODE REVIEW

**Comment by CloudyPadmal** [comment]
I'll have to merge the changes from #1472 into this one once it gets merge. (Stop button etc.)

**Comment by mariobehling** [comment]
Please also add the screenshots to the docs img folder.

**Comment by cweitat** [comment]
@CloudyPadmal some codacy issues.

**Comment by cweitat** [comment]
Also spelling of barometer. Is joined, not separated. 
Other than that all good.

**Comment by CloudyPadmal** [comment]
Thank you for the review @cweitat ! I'll update the PR with changes. :+1:

**Comment by CloudyPadmal** [comment]
Hi @cweitat ! I've made the changes. Can you have a look? :D

**Pull request merged**
