### PR TITLE
fixed #2190 At navigation drawer, The menu option of help & Report a …

### LINKED ISSUE #2190: At navigation drawer, The menu option of help & Report a Bug is missing ..
**Actual Behaviour**
At navigation drawer, The menu option of help & Report a Bug is missing ..

**Expected Behaviour**
After creating the report a bug & help option, navigation drawer, if any user sees any issue or bug in app, then that user will click on this option and then he will come to the issue option of github repository of app so that he can create his new issue .

**Steps to reproduce it**
Creating a menu option for report a bug at navigation drawer.

**Screenshot**
WhatsApp Image 2021-02-04 at 10 06 04 AM

**Would you like to work on the issue?**
yes

### PR DESCRIPTION
**Pull request by Prashant830**
Fixes #2190 

**Changes**: 
added to menu option(report a bug & help) at navigation drawer.
**Short Video/s for the changes**: [Add screenshot/s of the layout where you made changes or a `*.gif` containing a demonstration]

https://user-images.githubusercontent.com/72181295/106849605-fdaeea00-66d8-11eb-951b-cae3ec4fdbe7.mp4

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [ ] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: [Compress the `app-debug.apk` file into a `<feature>.rar` or `<feature>.zip` file and upload it here]

### CODE REVIEW

**Review by asaikarthikeya — COMMENTED** [review]
Most of the general questions user may encounter are listed in FAQ section. And Report option is a part of Google play store rating IG .If we implement this way user is forced to create a gitter account and join the room. Thankyou.

**Comment by Prashant830** [comment]
@asaikarthikeya I know but if someone finds a bug or issues then where will they report. Will you report in the issue folder of github repository yes or not, so I created the option of report or bug, which I have shared only the link with issue option of github repository and talked about, what we do in the help Is there any problem coming example, how to login, how to do it, then we ask for help, so I have added the gitter channel.

**Review by CodeWithSouma — COMMENTED** [review]
Both of the features already present in the about us section.

**Comment by CloudyPadmal** [comment]
Nice work @Prashant830 and thanks for your effort on this feature. But I think we better keep it as it is since the drawer gets bit crowded with so many options.

**Comment by Prashant830** [comment]
@CloudyPadmal OK, no problem

**Pull request closed without merging**
