### PR TITLE
feat: added Position Controls

### LINKED ISSUE #2458: Oscilloscope: Add new feature for Position Controls
This is for the addition of the following proposed feature:-

**Horizontal & Vertical Position Controls**:
- Another feature would be to control the horizontal and vertical position of the waveform on the oscilloscope display, for manual measurements.
- The horizontal position control moves the waveform back and forth on the display and can be used to either align the waveform with the horizontal divisions of the display or to view different sections of the waveform.
- The vertical position control moves the waveform up and down on the display and can be used for manual measurements in a similar way as the horizontal position control.

**Actual Behaviour**
Currently, the app doesn't have any such feature to control the position of the waveform.

**Expected Behaviour**
Such a feature is an integral part of dedicated oscilloscope devices, and thus, our app should also be having it.

**Steps to reproduce it**
N/A

**LogCat for the issue**
N/A

**Screenshots of the issue**
N/A

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by AsCress**
Resolves #2458 
Adds the Position Controls feature to the Oscilloscope screen.

**Horizontal & Vertical Position Controls**:
- Another feature would be to control the horizontal and vertical position of the waveform on the oscilloscope display, for manual measurements.
- The horizontal position control moves the waveform back and forth on the display and can be used to either align the waveform with the horizontal divisions of the display or to view different sections of the waveform.
- The vertical position control moves the waveform up and down on the display and can be used for manual measurements in a similar way as the horizontal position control.

The UI for the feature is implemented in the _DataAnalysisFragment_, using _Spinners_ for selecting the channels and _SeekBars_ for choosing the offset value, arranged in a layout as discussed with everyone before.

## Changes 
- app/src/main/java/io/pslab/fragment/DataAnalysisFragment.java
- app/src/main/java/io/pslab/activity/OscilloscopeActivity.java
- app/src/main/java/io/pslab/fragment/TimebaseTriggerFragment.java
- app/src/main/res/layout/fragment_data_analysis.xml
- app/src/main/res/layout/fragment_data_analysis_main.xml
- app/src/main/res/layout/position_controls.xml

## Screenshots / Recordings  
Here is a demo of the feature using the _In-Built MIC_-

https://github.com/fossasia/pslab-android/assets/125425881/f5d4f58d-cb07-4588-a652-8a09c616b3f4

**Checklist**: 
- [x] **No hard coding**: I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard coding any value.
- [x] **No end of file edits**: No modifications done at end of resource files `strings.xml`, `dimens.xml` or `colors.xml`.
- [x] **Code reformatting**: I have reformatted code and fixed indentation in every file included in this pull request.
- [x] **No extra space**: My code does not contain any extra lines or extra spaces than the ones that are necessary.

@marcnause @CloudyPadmal @mariobehling This feature is now ready for testing and review.

### CODE REVIEW

**Comment by marcnause** [comment]
I tested the current state of the UI on my small test phone and I think the screen looks good with the additional UI elements.

Once you add the _TextViews_, the space for the _Spinners_ may be a little bit small on small screens.

Screenshot_20240608-233813

**Comment by AsCress** [comment]
@marcnause I have developed this feature and updated this PR accordingly. It is now ready for testing. Could you please test this feature with all the other channels and provide feedback ?
I have also improved the layout for several other elements in the _DataAnalysisFragment_ for them to populate well on all screen sizes and fit in correctly with the newly added UI elements.

**Comment by marcnause** [comment]
@AsCress As far as I can tell, it works well. I have tested with the PSLab and different channels.

Is this feature ready to be reviewed or would you like to add a possibility to set the values directly by entering the values?

**Review by CloudyPadmal — APPROVED** [review]

**Comment by AsCress** [comment]
@marcnause I guess this is ready to be reviewed. Manual inputs using _EditTexts_ change the focus of the screen, something which leads to not a very nice user experience. That's why according to me, we should have the inputs through the _SeekBar_ only since the range of the _SeekBars_ is set according to the axes scales, which provides an adequate experience. Let me know your views on this.

**Review by marcnause — APPROVED** [review]

**Comment by marcnause** [comment]
@AsCress I used a device with a small screen for testing and the _Seekbars_ worked well thanks to the axes scales. I was only asking because I think you mentioned _EditTexts_ earlier, but I think you are right about the user experience problems.

**Comment by AsCress** [comment]
> @AsCress I used a device with a small screen for testing and the _Seekbars_ worked well thanks to the axes scales. I was only asking because I think you mentioned _EditTexts_ earlier, but I think you are right about the user experience problems.

@marcnause Thanks for testing. Yes, you are right. However, we can still do think of adding the _EditTexts_, if we find some way to configure them with the current configuration of the oscilloscope screen. I'll try this and maybe handle this in a separate PR.

**Pull request merged**
