### PR TITLE
fix: app bar and back button in all sensor activity and add missing MPU925X sensor in sensor list index 

### LINKED ISSUE #2157: Add app bar and back button in all sensor activity and add missing MPU925X sensor in sensor list index
**Actual Behaviour**

1. Please check sensor activity and all sensors don't have the app bar and back button. 
2. When we click the auto-scan button then in sensors list MPU925X missing  

**Expected Behaviour**

1. For the first problem: - All the instruments of our app have the app bar so I think this is very useful for navigating.
2. For the second problem:-   When we click the auto-scan button then in the sensors list MPU925X should be indexed.

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by CodeWithSouma**
# Add app bar and back button in all sensor activity and add missing MPU925X sensor in sensor list index, Fix #2157 
@CloudyPadmal 
1. Add app bar in all sensor activity
2. Add missing MPU925X sensor in sensor list index
<pre>     <b>Before change UI look like this</b>                         <b>After change UI look like this</b></pre>
Before change UI looks like this    After change UI look like this

**PSLab apk (before the change):**[before change PSLab.zip](https://github.com/fossasia/pslab-android/files/5791814/before.change.PSLab.zip)

**PSLab apk (after the change):**[after change PSLab.zip](https://github.com/fossasia/pslab-android/files/5791820/after.change.PSLab.zip)

### CODE REVIEW

**Comment by CodeWithSouma** [comment]
@CloudyPadmal  sir, please check this PR

**Comment by CodeWithSouma** [comment]
@CloudyPadmal  @mariobehling  please review this PR

**Review by CloudyPadmal — COMMENTED** [review]
Looks good. Nice work @CodeWithSouma . Can you clean up the branch? There seem to be a lot of commits from development

**Comment by CodeWithSouma** [comment]
> Looks good. Nice work @CodeWithSouma . Can you clean up the branch? There seem to be a lot of commits from development

Sir, I don't how to squash commit please do something

**Comment by CloudyPadmal** [comment]
Aha. They look like small commits for this one PR. I'll squash it. Something similar to https://github.com/fossasia/pslab-android#how-to-git-squash will help squashing commits in future.

**Review by CloudyPadmal — APPROVED** [review]

**Pull request merged**
