### PR TITLE
feat: extended record button to start sensor data fetching and recording

### LINKED ISSUE #1304: lux is always running
**Actual Behaviour**

Currenlty lux meter is always fetching data from sensors and keeps running continously

**Expected Behaviour**

The lux meter should have play pause functionality so that the user can start fetching the lux data whenever it wants.

**Steps to reproduce it**

LuxMeterFragmentData -> create functionality to start sensor fetching on the play button click

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by Avjeet**
Fixes #1304 

**Changes**: 

- Extended the record button to start the meter and graph plotting(i.e sensor data fetching) and also to record data.
- Added new record button

> To do  
Store data in realm instead of CSV file.(That will be done in PR #1323 )

**Screenshot/s for the changes**: 

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [ ] I have requested reviews from other members

**APK for testing**:
[play.zip](https://github.com/fossasia/pslab-android/files/2272179/play.zip)

### CODE REVIEW

**Comment by harsh-2711** [comment]
@Avjeet  In my opened PR I have added play pause functionalities along with added functionality of deleting and exporting. So, I think it's better to go with one PR.

**Comment by CloudyPadmal** [comment]
@Avjeet please resolve the conflicts soon

**Comment by Avjeet** [comment]
@cweitat done with the changes

**Comment by harsh-2711** [comment]
@Avjeet This is the screen when I open the Lux Meter
screenshot_20180809-013148

Lux Meter isn't working. Please fix this issue. Also, the record icon has a different color than other icons.

**Comment by Avjeet** [comment]
@harsh-2711 The lux will only run when you click on the record button

**Comment by Avjeet** [comment]
icons updated

**Comment by cweitat** [comment]
@Avjeet for the icons, can we have the same font size for both REC and STOP instead of squeezing the STOP text within the range? thanks

**Comment by Avjeet** [comment]
@cweitat The text is inside the SVG image so it is getting squeezed automatically by Android to fit menu icon space

**Comment by Avjeet** [comment]
@cweitat Updated icons


image

**Comment by Avjeet** [comment]
@cweitat Updated icons

**Comment by Avjeet** [comment]
@CloudyPadmal PLz review and merge it asap

**Comment by cweitat** [comment]
@Avjeet now REC is squashed and STOP looks normal?
Can't we have like this?
image
image

**Comment by Avjeet** [comment]
@cweitat increased text size of rec in icon

**Comment by harsh-2711** [comment]
@Avjeet Even I was unable to figure out how to run Lux then how can we expect that users will understand? Also, the record and play button have a different meaning. If you are referencing PhyPhox, then they are using play button so that it is clear to the user. What do you think?

**Comment by Avjeet** [comment]
@harsh-2711 
This is done due to two reason:-

1. The lux meter uses the sensor from the phone so if we kept the lux meter always running then there is the unnecessary usage of phone resources, having lux meter run only on play button resolve that issue.

2. Second lux meter is a virtual electronic instrument and not a video player so I don't think the record button can confuse the user in any way. Moreover we can include that in the guide which could take care of that.

**Comment by cweitat** [comment]
@Avjeet so both now look the same?

**Comment by Avjeet** [comment]
@cweitat yeah now I have  increased the text size to make it similar to stop text

**Comment by Avjeet** [comment]
@cweitat there was a minor change and yeah now both looks similar see the ss below:

**Pull request merged**
