### PR TITLE
New Designing of Applications and added correct schematics and extensions

### PR DESCRIPTION
**Pull request by harsh-2711**
Fixes issue : #821  #822 #832 

Changes: Missing schematic added and extensions of some wrong files are changed. Also, the build.gradle file is updated according to new version of android studio. Also complete designing of Applications Section is done as per mentor guideline.

Screenshots for the change: 
**Portrait Mode** 
screenshot_20180506-012450

**Landscape Mode**
screenshot_20180506-012512

**Piezo Buzzer Experiment**
screenshot_20180506-012542

**Ultrasonic Range Finder Experiment**
screenshot_20180506-012558

APK for testing: 
[app-debug.zip](https://github.com/fossasia/pslab-android/files/1977050/app-debug.zip)

### CODE REVIEW

**Comment by harsh-2711** [comment]
Sorry I forgot to create new branch and so will merge PR #823 with this PR  and will then close it.

**Comment by harsh-2711** [comment]
We can overlap text on the image once final images are obtained from the designer by removing the paddings from the ImageView. Till then I have kept text above the image.

**Comment by CloudyPadmal** [comment]
@Avjeet agreed! @harsh-2711 we don't have a separate designer. Find/Design suitable images and present them in the gitter channel so everyone can review and select proper background images.

**Comment by harsh-2711** [comment]
Should I close this PR?

**Pull request closed without merging**
